// @ts-nocheck — seed data file, PayloadCMS collection types vary at runtime
import type { getPayload as getPayloadType } from "payload"

function textToLexical(text: string) {
  return {
    root: { type: "root" as const, direction: "ltr" as const, format: "" as const, indent: 0, version: 1,
      children: text.split("\n\n").filter(Boolean).map((para) => ({
        type: "paragraph" as const, direction: "ltr" as const, format: "" as const, indent: 0, version: 1,
        children: [{ type: "text" as const, text: para, format: 0 }],
      })),
    },
  }
}

export const CATEGORIES = [
  { slug:"seo-geo", ja:{name:"SEO/GEO", desc:"検索エンジン最適化とAI検索対策の最新情報"}, en:{name:"SEO/GEO", desc:"Latest insights on search engine optimization and AI search"}, color:"indigo" as const, sort:1 },
  { slug:"ai-automation", ja:{name:"AI・自動化", desc:"AI活用・業務自動化・DX推進の実践ノウハウ"}, en:{name:"AI & Automation", desc:"Practical know-how for AI adoption, automation, and DX"}, color:"violet" as const, sort:2 },
  { slug:"web-production", ja:{name:"Web制作", desc:"Webサイト制作・リニューアルのノウハウと最新トレンド"}, en:{name:"Web Development", desc:"Best practices and trends in web development and redesign"}, color:"emerald" as const, sort:3 },
  { slug:"digital-marketing", ja:{name:"デジタルマーケティング", desc:"集客・成約率改善・データ活用の総合マーケティング情報"}, en:{name:"Digital Marketing", desc:"Comprehensive marketing insights for lead generation, CVR, and data utilization"}, color:"amber" as const, sort:4 },
]

interface SeedPost {
  slug: string; ja: { title: string; excerpt: string; cat: string; read: string; content: string }; en: { title: string; excerpt: string; cat: string; read: string; content: string }
  tags: string[]; date: string
}

const POSTS_PART1: SeedPost[] = [
  { slug:"geo-2025-complete-guide", ja:{title:"GEO完全ガイド 2025 — AI検索時代のSEO戦略", excerpt:"ChatGPT、Perplexity、Google AI Overviews。AIが回答を生成する時代に、検索流入を獲得する新手法GEOの全貌を解説。従来SEOとの違い、具体的な最適化手法、12カ国語対応の実践戦略まで。", cat:"SEO/GEO", read:"12分", content:`## GEOとは何か\n\nGEO（Generative Engine Optimization）は、ChatGPT、Perplexity、Google AI Overviews、Claude、Geminiといった生成AIエンジンにおいて、自社コンテンツが引用・参照されるよう最適化する新しい分野です。従来のSEOが「Googleの青リンク10件」の中での上位表示を目指すのに対し、GEOは「AIが生成する回答」の中に自社情報を組み込ませることを目的とします。\n\n## なぜ今GEOが必要なのか\n\n2025年現在、検索行動は大きく変化しています。Google検索でもAI Overviewsが上部に表示され、ユーザーは青リンクをクリックする前にAIの回答を読んで満足してしまうケースが増えています。PerplexityやChatGPT Searchの利用率も急増しており、従来型SEOだけでは獲得できないトラフィックが拡大しています。\n\n## GEOとSEOの決定的な違い\n\nSEOが「クローラー向けの技術最適化＋被リンク獲得」であるのに対し、GEOは「AIが学習・引用したくなる情報価値」が核心です。一次データ・独自統計の保有、権威ある外部ソースからの被引用実績、構造化された明確な情報設計、質問に対する直接的で簡潔な回答が重要です。\n\n## 具体的なGEO最適化手法\n\nTL;DR要約を冒頭に配置、独自統計・データを提示、外部引用シグナルを強化、構造化データ（JSON-LD）を完璧に実装、多言語展開でグローバルAI検索をカバー。Paradigmでは12カ国語対応のGEO最適化を提供しています。`}, en:{title:"GEO 2025 Complete Guide — SEO Strategy for the AI Search Era", excerpt:"ChatGPT, Perplexity, Google AI Overviews. A complete guide to GEO — the new discipline for winning traffic in the AI-generated answer era. Differences from traditional SEO, concrete optimization methods, and a 12-language practical strategy.", cat:"SEO/GEO", read:"12 min", content:`## What is GEO\n\nGEO (Generative Engine Optimization) is a new discipline focused on optimizing content so that AI engines — ChatGPT, Perplexity, Google AI Overviews, Claude, Gemini — cite and reference your brand in their generated answers. While traditional SEO targets ranking among Google's blue links, GEO aims to embed your information directly into AI-generated responses.\n\n## Why GEO Matters Now\n\nSearch behavior has shifted dramatically. Google's own AI Overviews now dominate the top of search results, and users often find answers without ever clicking a link. Perplexity and ChatGPT Search adoption is accelerating, creating traffic channels that traditional SEO alone cannot capture.\n\n## Key Differences\n\nSEO focuses on technical crawler optimization and backlinks. GEO centers on the information value that makes AI want to cite you: original data, citation track record, clear information architecture, and direct concise answers.\n\n## Practical GEO Optimization\n\nPlace TL;DR summaries at the top, present original statistics, strengthen external citation signals, implement complete structured data (JSON-LD), and cover global AI search through multilingual deployment. Paradigm provides GEO optimization across 12 languages.`}, tags:["GEO","AI検索","ChatGPT","Perplexity","SEO"], date:"2025-08-01" },
  { slug:"seo-technical-checklist-2025", ja:{title:"【2025年版】テクニカルSEO完全チェックリスト", excerpt:"Core Web Vitals、モバイルファースト、構造化データ、サイト速度。検索順位を左右するテクニカルSEOの全要素を50項目で網羅。INP対応やNext.js最適化も解説。", cat:"SEO/GEO", read:"15分", content:`## テクニカルSEOの重要性\n\nテクニカルSEOは、検索エンジンがサイトを正しくクロール・インデックスできるようにする基盤整備です。コンテンツが素晴らしくても技術的な問題で検索順位が上がらないケースは非常に多くあります。\n\n## 2025年の重要トピック\n\nGoogleはINP（Interaction to Next Paint）をCore Web Vitalsの正式指標に採用しました。FIDに代わるこの指標はユーザー操作への応答速度を測定します。\n\n## 主要チェック項目\n\nクロール・インデックス: XML Sitemapの自動生成と送信、robots.txtの適切な設定、canonicalタグの正しい実装。構造化データ: Organizationスキーマ、BreadcrumbListスキーマ、FAQスキーマ、Articleスキーマ。Core Web Vitals: LCP 2.5秒以内、INP 200ms以内、CLS 0.1以内、画像のWebP/AVIF化。モバイル: レスポンシブデザイン、タップターゲットサイズ、コンテンツパリティ。\n\n## Next.jsサイトの最適化\n\nnext/image活用、動的メタデータのgenerateMetadata実装、ISRによるパフォーマンス最適化、適切なキャッシュ戦略の設定が重要です。`}, en:{title:"2025 Technical SEO Complete Checklist", excerpt:"Core Web Vitals, mobile-first indexing, structured data, site speed. A complete 50-item checklist covering every technical SEO factor that impacts rankings, including INP and Next.js optimization.", cat:"SEO/GEO", read:"15 min", content:`## The Importance of Technical SEO\n\nTechnical SEO is the foundation that enables search engines to correctly crawl and index your site. Even with exceptional content, technical issues frequently prevent sites from ranking well.\n\n## Key 2025 Topics\n\nGoogle adopted INP (Interaction to Next Paint) as a Core Web Vitals metric. This replacement for FID measures responsiveness to user interactions.\n\n## Major Checklist Items\n\nCrawl & Index: XML Sitemap, proper robots.txt, correct canonical tags. Structured Data: Organization, BreadcrumbList, FAQ, Article schemas. Core Web Vitals: LCP under 2.5s, INP under 200ms, CLS under 0.1, WebP/AVIF images. Mobile: Responsive design, tap target sizing, content parity.\n\n## Next.js Optimization\n\nPay attention to next/image usage, dynamic metadata via generateMetadata, ISR performance optimization, and proper cache strategy configuration.`}, tags:["テクニカルSEO","Core Web Vitals","チェックリスト","Next.js"], date:"2025-07-20" },
  { slug:"keyword-research-ai-era", ja:{title:"AI時代のキーワード戦略 — 検索意図の深掘りとトピッククラスター設計", excerpt:"従来のキーワード単位のSEOは限界を迎えています。AI検索時代に必要な「検索意図マッピング」「トピッククラスター」「エンティティ最適化」の3本柱を解説します。", cat:"SEO/GEO", read:"8分", content:`## キーワードSEOの限界\n\n「ビッグキーワードで1位を取る」という従来型SEO戦略はもはや十分ではありません。AI検索の台頭によりユーザーは単一キーワードではなく複雑な質問を投げかけるようになっています。\n\n## 検索意図マッピング\n\nキーワードの背後にあるユーザーの真の意図を情報型（知りたい）、ナビゲーション型（行きたい）、商標型（比べたい）、取引型（買いたい）の4象限で分類します。\n\n## トピッククラスター戦略\n\nピラーページを中心に関連するクラスターページを放射状に配置しサイト全体の専門性と権威性を高めます。\n\n## エンティティ最適化\n\nGoogleのKnowledge GraphやAIのナレッジベースに自社や商品を「エンティティ」として正しく認識させる手法です。Schema.orgの適切な実装、Wikipedia/Wikidataとの連携、外部メディアでの一貫した言及が重要です。`}, en:{title:"Keyword Strategy in the AI Era", excerpt:"Keyword-level SEO is reaching its limits. Learn the three pillars needed in the AI search era: search intent mapping, topic clusters, and entity optimization.", cat:"SEO/GEO", read:"8 min", content:`## The Limits of Keyword SEO\n\nThe traditional strategy of ranking #1 for a big keyword is no longer sufficient. AI search users ask complex questions rather than typing single keywords.\n\n## Search Intent Mapping\n\nClassify true user intent into four quadrants: Informational, Navigational, Commercial, Transactional.\n\n## Topic Cluster Strategy\n\nA hub-and-spoke structure with pillar pages at the center builds site-wide expertise and authority.\n\n## Entity Optimization\n\nEnsure AI knowledge bases correctly recognize your brand as an entity through proper Schema.org implementation, Wikipedia/Wikidata integration, and consistent external mentions.`}, tags:["キーワード戦略","検索意図","トピッククラスター","SEO"], date:"2025-07-10" },
  { slug:"meo-google-maps-ranking", ja:{title:"MEO対策の全て — Googleマップで上位表示するための15の施策", excerpt:"Googleビジネスプロフィールの最適化から口コミ戦略、投稿運用、ローカルSEO連携まで。地域ビジネスがGoogleマップで上位表示されるための具体的施策を全公開します。", cat:"SEO/GEO", read:"10分", content:`## MEO対策とは\n\nMEO（Map Engine Optimization）はGoogleマップ検索での上位表示を目指す施策です。特に実店舗を持つビジネスや地域密着型のサービスにとって集客の生命線です。\n\n## GBP最適化のポイント\n\nビジネス名・住所・電話番号の正確な一致（NAP整合性）、営業時間・定休日の正確な設定、カテゴリの適切な選択、ビジネス説明文へのキーワード自然な組み込み、高品質な写真の定期投稿、Q&Aセクションの整備。\n\n## 口コミ戦略\n\n口コミの数と質、返信率がMEO順位に大きく影響します。全口コミへの24時間以内の返信、ポジティブ口コミへの感謝＋サービスの再訴求、ネガティブ口コミへの誠実な対応が重要です。\n\n## 投稿運用\n\nGBPの投稿機能を活用し最新情報・イベント・特典を定期的に発信します。投稿は14日間で期限切れになるため最低週1回の更新が推奨されます。`}, en:{title:"Complete MEO Guide — 15 Tactics to Rank Higher on Google Maps", excerpt:"From Google Business Profile optimization to review strategy, post management, and local SEO integration. Everything local businesses need to rank higher on Google Maps.", cat:"SEO/GEO", read:"10 min", content:`## What is MEO\n\nMEO (Map Engine Optimization) focuses on achieving top rankings in Google Maps search. For businesses with physical locations, MEO is a critical customer acquisition channel.\n\n## GBP Optimization Essentials\n\nExact NAP consistency, accurate hours including holidays, proper category selection, natural keyword inclusion in description, regular high-quality photo uploads, Q&A section setup.\n\n## Review Strategy\n\nReview quantity, quality, and response rate significantly impact MEO rankings. Respond to all reviews within 24 hours, thank positive reviewers, address negative reviews with genuine plans.\n\n## Post Management\n\nUse GBP posts to regularly share updates and offers. Posts expire after 14 days, so aim for at least weekly updates.`}, tags:["MEO","Googleマップ","ローカルSEO","口コミ","集客"], date:"2025-06-25" },
  { slug:"structured-data-seo-guide", ja:{title:"構造化データ完全入門 — JSON-LDで検索表示を劇的に改善する方法", excerpt:"リッチリザルト、ナレッジパネル、サイトリンク検索ボックス。構造化データの正しい実装方法とビジネス成果に直結する7つのスキーマタイプを実例付きで解説します。", cat:"SEO/GEO", read:"9分", content:`## 構造化データとは\n\n構造化データはWebページの内容を検索エンジンが理解しやすい形式で記述するマークアップです。正しく実装することでリッチリザルト（星評価、価格、イベント日程など）として検索結果に表示されCTRを大幅に向上させます。\n\n## 必須スキーマタイプ7選\n\nOrganization（企業情報）、WebSite（サイトリンク検索ボックス）、BreadcrumbList（パンくず）、Article/BlogPosting（記事）、FAQ（アコーディオン表示）、LocalBusiness（地域ビジネス）、Product（EC商品）。\n\n## Next.jsでの実装方法\n\nApp RouterでgenerateMetadataと併せて構造化データをscriptタグで埋め込みます。dangerouslySetInnerHTMLでJSON-LDを出力し型安全なTypeScriptでスキーマオブジェクトを構築します。`}, en:{title:"Structured Data Complete Guide", excerpt:"Rich results, knowledge panels, sitelink search boxes. A practical guide to implementing structured data correctly, with examples of 7 schema types that directly impact business outcomes.", cat:"SEO/GEO", read:"9 min", content:`## What is Structured Data\n\nStructured data is markup that describes web page content in a format search engines can easily parse. When implemented correctly, it enables rich results in search results, dramatically improving CTR.\n\n## 7 Essential Schema Types\n\nOrganization, WebSite, BreadcrumbList, Article/BlogPosting, FAQ, LocalBusiness, Product.\n\n## Implementation in Next.js\n\nIn App Router, embed structured data via script tags alongside generateMetadata. Output JSON-LD with dangerouslySetInnerHTML, constructing schema objects with type-safe TypeScript.`}, tags:["構造化データ","JSON-LD","リッチリザルト","スキーマ"], date:"2025-06-15" },
  // AI・自動化
  { slug:"ai-business-automation-2025", ja:{title:"中小企業のAI業務自動化 — 2025年に導入すべき5つのツールと導入手順", excerpt:"Dify、n8n、DeepSeek、Make、Zapier。2025年、中小企業がコストを抑えてAI自動化を実現するためのツール選定と導入手順を、実際の業務フローに沿って解説します。", cat:"AI・自動化", read:"10分", content:`## AI自動化の現実解\n\n「AIで全部自動化」は幻想です。現実的なアプローチは人間の判断が必要な部分と自動化できる部分を分離し徐々に自動化範囲を広げていくことです。\n\n## 2025年おすすめツール5選\n\nDify: AIアプリ構築プラットフォーム。チャットボット、文章生成、データ分析をノーコードで実装可能。n8n: オープンソースのワークフロー自動化。1000以上のサービスと連携。DeepSeek V4: 高精度・低コストLLM。Context Cachingで入力コスト90%OFF。Make: 視覚的なシナリオビルダー。Zapier: 7000以上のアプリ連携。\n\n## 導入ステップ\n\n業務の棚卸しと自動化候補の洗い出し、優先度・効果試算によるロードマップ作成、PoCの小規模実施、本番展開とモニタリング、継続的な改善サイクルの確立。`}, en:{title:"AI Business Automation for SMBs — 5 Tools to Deploy in 2025", excerpt:"Dify, n8n, DeepSeek, Make, Zapier. A practical guide to cost-effective AI automation tools for SMBs in 2025, with implementation steps mapped to real business workflows.", cat:"AI & Automation", read:"10 min", content:`## The Reality of AI Automation\n\nAI automating everything is a fantasy. The realistic approach is separating human judgment from automatable tasks and gradually expanding scope.\n\n## Top 5 Tools for 2025\n\nDify: No-code AI app platform. n8n: Open-source workflow automation with 1000+ integrations. DeepSeek V4: High-accuracy, low-cost LLM with 90% input cost reduction. Make: Visual scenario builder. Zapier: 7000+ app integrations.\n\n## Implementation Steps\n\nAudit operations, build roadmap with ROI estimates, run small-scale PoC, production deployment and monitoring, establish continuous improvement cycles.`}, tags:["AI","自動化","Dify","n8n","DX","業務改善"], date:"2025-08-05" },
  { slug:"dify-ai-chatbot-build", ja:{title:"DifyではじめるAIチャットボット構築 — ノーコードで自社専用AIを作る完全ガイド", excerpt:"プログラミング不要で自社専用AIチャットボットを構築できるDifyの使い方を徹底解説。ナレッジベース設定、ワークフロー設計、Webサイト埋め込みまで。", cat:"AI・自動化", read:"12分", content:`## Difyとは\n\nDifyはLLMを活用したAIアプリケーションをノーコードで構築できるプラットフォームです。カスタマーサポートチャットボット、社内向けナレッジQ&A、コンテンツ生成ツールなど幅広い用途に対応します。\n\n## ナレッジベースの構築\n\nAIに自社情報を学習させる核となるのがナレッジベースです。Webサイトの内容、製品マニュアル、FAQ、社内文書などをアップロードすることでAIが自社専用の回答を生成できるようになります。\n\n## ワークフロー設計のポイント\n\n条件分岐や外部API連携を含む複雑なワークフローも設計できます。問い合わせ内容に応じて適切な部署に振り分ける、在庫確認APIを呼び出して回答するといった高度な自動化が可能です。\n\n## Webサイトへの埋め込み\n\nDifyで構築したチャットボットは数行のJavaScriptコードで既存のWebサイトに埋め込めます。カスタムCSSでブランドに合わせたデザイン変更も可能です。`}, en:{title:"Building AI Chatbots with Dify — A Complete No-Code Guide", excerpt:"A comprehensive guide to Dify — the no-code platform for building custom AI chatbots. Covers knowledge base setup, workflow design, and website embedding.", cat:"AI & Automation", read:"12 min", content:`## What is Dify\n\nDify is a no-code platform for building AI applications powered by LLMs. It supports chatbots, internal knowledge Q&A, content generation, and more.\n\n## Building a Knowledge Base\n\nThe knowledge base teaches AI your business information. Upload website content, manuals, FAQs, and internal documents.\n\n## Workflow Design Tips\n\nDesign complex workflows with conditional branching and external API integration. Route inquiries or call inventory APIs for real-time responses.\n\n## Website Embedding\n\nDify chatbots embed into any website with a few lines of JavaScript. Custom CSS enables brand-aligned design.`}, tags:["Dify","AIチャットボット","ノーコード","ナレッジベース","DeepSeek"], date:"2025-07-25" },
  { slug:"deepseek-v4-business-use", ja:{title:"DeepSeek V4のビジネス活用術 — 月額数千円ではじめるAI導入", excerpt:"Context Cachingで入力コスト90%OFF。大量の問い合わせ自動応答、多言語コンテンツ生成、営業資料の自動作成など具体的なビジネス活用事例とコスト試算を公開します。", cat:"AI・自動化", read:"8分", content:`## DeepSeek V4の特長\n\nDeepSeek V4は高精度と低コストを両立するLLMです。Context Cachingにより同一プロンプトのキャッシュヒット時に入力コストが90%OFFになります。\n\n## 具体的な活用事例\n\nカスタマーサポート自動応答: FAQと問い合わせ履歴をキャッシュし高精度な一次回答を自動生成。多言語コンテンツ生成: 日本語の記事を12カ国語に一括翻訳。営業資料の自動作成: 企業データから業界分析・提案書のたたき台を自動生成。\n\n## 月額コスト試算\n\n月間10,000件の問い合わせ自動応答でキャッシュヒット率70%ならAPIコストは月額5〜10ドル程度。人件費換算で月数十万円の削減効果が期待できます。`}, en:{title:"DeepSeek V4 for Business — Start AI for Just a Few Dollars a Month", excerpt:"DeepSeek V4 with Context Caching cuts input costs by 90%. Real business use cases and cost estimates for automated responses, multilingual content, and sales material creation.", cat:"AI & Automation", read:"8 min", content:`## DeepSeek V4 Highlights\n\nDeepSeek V4 balances high accuracy with low cost. Context Caching cuts input costs by 90% on cache hits.\n\n## Real-World Use Cases\n\nAutomated customer support with cached FAQs. Multilingual content generation translating Japanese into 12 languages. Automated sales materials from company data.\n\n## Monthly Cost Estimate\n\nFor 10,000 automated responses at 70% cache-hit rate, API costs run just $5-10/month — thousands in labor-cost savings.`}, tags:["DeepSeek","LLM","コスト削減","AI活用"], date:"2025-07-15" },
  { slug:"dx-small-business-roadmap", ja:{title:"中小企業DXの羅針盤 — 3ステップではじめるデジタル改革", excerpt:"DXは大企業だけのものではありません。中小企業が今日から始められるDXの3ステップ「デジタル化 → 自動化 → 高度化」を具体的な費用感とともに解説します。", cat:"AI・自動化", read:"7分", content:`## DXは難しくない\n\nDXに圧倒される中小企業経営者は少なくありません。しかし本質はシンプルです。「デジタル技術を使って今の業務をより良くする」ことです。\n\n## ステップ1：デジタル化\n\n紙の書類をクラウドに移行し情報共有をスムーズに。Google WorkspaceやMicrosoft 365の導入、クラウド会計ソフトへの移行、電子契約の導入から始めましょう。\n\n## ステップ2：自動化\n\n繰り返し作業をツールで自動化。n8nで「メール→Slack通知→スプレッドシート記録」のようなルーチンを自動化、AIチャットボットで一次問い合わせ対応を自動化します。\n\n## ステップ3：高度化\n\n蓄積したデータを分析しAIを活用した予測や意思決定支援を行います。在庫予測、売上予測、顧客離反予測などの高度な分析をクラウドAIツールで実現できます。`}, en:{title:"SMB DX Roadmap — A 3-Step Guide to Digital Transformation", excerpt:"DX isn't just for enterprises. A practical 3-step framework for SMBs — Digitalize → Automate → Advance — with concrete cost estimates and actionable starting points.", cat:"AI & Automation", read:"7 min", content:`## DX Isn't Hard\n\nMany SMB leaders feel overwhelmed by DX but the essence is simple: use digital technology to make current operations better.\n\n## Step 1: Digitalize\n\nMove paper to the cloud. Start with Google Workspace or Microsoft 365, cloud accounting, and electronic contracts.\n\n## Step 2: Automate\n\nAutomate repetitive tasks with n8n workflows and AI chatbots for first-response inquiries.\n\n## Step 3: Advance\n\nAnalyze data and leverage AI for prediction and decision support — inventory forecasting, sales prediction, churn prediction with cloud AI tools.`}, tags:["DX","デジタル化","中小企業","業務改善"], date:"2025-07-01" },
  { slug:"ai-tool-comparison-2025", ja:{title:"【2025年比較】ビジネスAIツール完全ガイド — ChatGPT vs Claude vs Gemini vs DeepSeek", excerpt:"ビジネス用途で最適なAIツールはどれか。4大LLMを精度・コスト・機能・日本語対応の4軸で徹底比較します。", cat:"AI・自動化", read:"11分", content:`## 4大LLMの比較軸\n\nAIツール選定で重要なのは「どのタスクにどのモデルが最適か」です。日本語生成精度、APIコスト、機能、エコシステムの4軸で比較します。\n\n## 各モデルの特徴\n\nChatGPT（OpenAI）: エコシステムが最も充実。プラグイン、GPTs、API連携が豊富。日本語精度は高いがAPIコストは最高。Claude（Anthropic）: 長文処理と安全性に強み。200Kトークンのコンテキストウィンドウ。Gemini（Google）: マルチモーダル最強。画像・動画・音声の理解力が高い。DeepSeek V4: コストパフォーマンス最強。Context Cachingで入力コスト90%OFF。\n\n## 用途別おすすめ\n\nカスタマーサポート自動化 → DeepSeek（低コスト・高精度）。長文レポート作成 → Claude。画像・動画解析 → Gemini。社内AIアシスタント → ChatGPT。`}, en:{title:"2025 Business AI Tool Comparison — ChatGPT vs Claude vs Gemini vs DeepSeek", excerpt:"Which AI tool is best for business? A thorough 4-axis comparison of ChatGPT, Claude, Gemini, and DeepSeek — accuracy, cost, features, and Japanese support.", cat:"AI & Automation", read:"11 min", content:`## Comparison Framework\n\nThe key question: which model for which task? Compare Japanese quality, API cost, features, and ecosystem.\n\n## Model Highlights\n\nChatGPT: Richest ecosystem. Claude: Long-form processing, 200K context. Gemini: Best multimodal. DeepSeek V4: Best cost-performance, 90% input cost reduction.\n\n## Recommendations\n\nSupport automation → DeepSeek (low cost, high accuracy). Reports → Claude. Image/video → Gemini. Internal assistant → ChatGPT.`}, tags:["AI比較","ChatGPT","Claude","Gemini","DeepSeek"], date:"2025-06-20" },
]

const POSTS_PART2: SeedPost[] = [
  // Web制作
  { slug:"web-production-cost-2025", ja:{title:"Webサイト制作の費用相場 2025 — 発注前に知っておくべき予算のすべて", excerpt:"HP制作、LP制作、ECサイト構築。2025年のWeb制作費用相場を制作タイプ別・発注先別に徹底解説。見積もりの読み方、失敗しない発注のコツも紹介します。", cat:"Web制作", read:"11分", content:`## Web制作費用の全体像\n\nWebサイト制作の費用は「何を作るか」「誰に頼むか」で大きく変動します。\n\n## 制作タイプ別費用相場\n\nシンプルなコーポレートサイト（5ページ程度）: 30〜80万円。10ページ以上の本格サイト: 80〜200万円。LP1枚: 15〜50万円。ECサイト（Shopify等）: 100〜500万円。フルカスタムWebアプリ: 300万円〜。\n\n## 発注先別の特徴\n\n大手制作会社: 300万円〜。品質は高いが高額。中小制作会社: 50〜200万円。バランスが良い。フリーランス: 20〜100万円。コスパは良いが属人化リスクあり。\n\n## 見積もりの読み方\n\n見積書には制作費だけでなくサーバー代・ドメイン代・保守費用・追加修正費用が含まれているか確認しましょう。サブスク型の保守費用は要注意です。`}, en:{title:"Web Development Cost Guide 2025", excerpt:"A comprehensive 2025 web development cost guide by project type and vendor category. Learn to read quotes, spot hidden costs, and commission with confidence.", cat:"Web Development", read:"11 min", content:`## Web Development Cost Overview\n\nWeb development costs vary significantly based on what you're building and who you hire.\n\n## Cost Ranges by Project Type\n\nSimple corporate site: ¥300K-800K. Full site (10+ pages): ¥800K-2M. Single LP: ¥150K-500K. Ecommerce: ¥1M-5M. Custom web app: ¥3M+.\n\n## Vendor Categories\n\nLarge agencies: ¥3M+. Mid-size: ¥500K-2M. Freelancers: ¥200K-1M. Offshore: ¥100K-500K.\n\n## Reading Proposals\n\nCheck whether quotes include hosting, domains, maintenance, and revision costs beyond the base fee.`}, tags:["Web制作","費用","見積もり","発注","相場"], date:"2025-08-10" },
  { slug:"nextjs-vs-wordpress-2025", ja:{title:"Next.js vs WordPress — 2025年Web制作の技術選定で失敗しないための比較", excerpt:"Webサイト制作の2大選択肢をパフォーマンス、運用コスト、拡張性、SEO、セキュリティの5軸で徹底比較。", cat:"Web制作", read:"10分", content:`## 2大プラットフォームの現在地\n\n2025年、最もよく議論されるのがNext.js vs WordPressです。\n\n## パフォーマンス比較\n\nNext.jsはSSG/SSRによりLighthouseスコア95+が標準的。WordPressは適切なキャッシュと最適化で80+を達成できますがプラグイン依存度で変動します。\n\n## 運用コスト比較\n\nWordPressは非エンジニアでもコンテンツ更新が容易。Next.jsはヘッドレスCMSが必要ですがパフォーマンスとセキュリティで優位です。\n\n## どちらを選ぶべきか\n\nWordPress: 頻繁なコンテンツ更新が必要なブログ・メディア向け。Next.js: 高いパフォーマンスが求められるコーポレートサイト、多言語グローバルサイト、カスタムWebアプリ向け。`}, en:{title:"Next.js vs WordPress — How to Choose the Right Web Technology in 2025", excerpt:"The two major options for web development: Next.js vs WordPress. A thorough 5-axis comparison covering performance, costs, scalability, SEO, and security.", cat:"Web Development", read:"10 min", content:`## The Two Platforms Today\n\nIn 2025, the most common debate is Next.js vs WordPress.\n\n## Performance\n\nNext.js with SSG/SSR achieves Lighthouse 95+. WordPress can reach 80+ with proper caching but varies by plugin load.\n\n## Operating Costs\n\nWordPress offers easy content updates for non-engineers. Next.js needs a headless CMS but gains performance and security advantages.\n\n## Choosing\n\nWordPress: content-heavy blogs/media. Next.js: high-performance corporate sites, global multilingual sites, custom web apps.`}, tags:["Next.js","WordPress","技術選定","Web制作","比較"], date:"2025-07-30" },
  { slug:"web-design-trends-2025", ja:{title:"2025年Webデザイントレンド10選 — 集客につながる最新デザイン手法", excerpt:"Bentoグリッド、ダークモード対応、マイクロインタラクション、AIパーソナライゼーション。具体的な実装方法と集客効果の観点から解説。", cat:"Web制作", read:"8分", content:`## 2025年のWebデザイン方向性\n\n「情報設計の明瞭さ」と「ブランドの個性表現」の両立がテーマです。\n\n## 注目トレンド10選\n\nBentoグリッドレイアウト、可変フォント、スクロールドリブンアニメーション、グラスモーフィズム2.0、ダークモード完全対応、マイクロインタラクション、AIパーソナライゼーション、3D/WebGLの実用化、タイポグラフィ主導デザイン、カーボンアウェアデザイン。\n\n## 実装のポイント\n\nTailwindCSSやshadcn/uiを使えば多くのトレンドが標準機能として利用可能です。モダンなUIライブラリの活用でトレンド対応と保守性を両立できます。`}, en:{title:"10 Web Design Trends for 2025", excerpt:"Bento grids, dark mode, micro-interactions, AI personalization. 2025 web design trends explained with implementation methods and impact on lead generation.", cat:"Web Development", read:"8 min", content:`## 2025 Design Direction\n\nBalancing clear information architecture with distinctive brand expression.\n\n## 10 Notable Trends\n\nBento grids, variable fonts, scroll-driven animation, glassmorphism 2.0, full dark mode, micro-interactions, AI personalization, practical 3D/WebGL, typography-led design, carbon-aware design.\n\n## Implementation Tips\n\nModern UI libraries like TailwindCSS and shadcn/ui make many trends accessible as standard features.`}, tags:["Webデザイン","トレンド","UI/UX","デザイン"], date:"2025-07-05" },
  { slug:"cms-selection-guide", ja:{title:"CMSの選び方完全ガイド — WordPressからヘッドレスCMSまで徹底比較", excerpt:"WordPress、PayloadCMS、Strapi、Contentful、microCMS。多言語対応、運用コスト、拡張性、UI/UXの4軸で比較。", cat:"Web制作", read:"9分", content:`## CMS選定の重要性\n\nCMSはサイト運用の中心です。一度選ぶと移行に多大なコストがかかるため初期選定が極めて重要です。\n\n## 2025年のCMS選択肢\n\nWordPress: 世界シェア43%。プラグイン豊富だがセキュリティリスクあり。PayloadCMS: Next.jsネイティブのヘッドレスCMS。多言語対応と高い開発者体験が強み。Strapi: オープンソース。カスタマイズ性が高い。Contentful: SaaS型。信頼性高いが従量課金。microCMS: 国産。日本企業向けサポート充実。\n\n## 選定の4基準\n\n多言語対応: 海外展開予定なら多言語標準装備のCMSを。運用コスト: 月額費用だけでなく人件費も含めて試算。拡張性: 将来の機能追加を見据えた設計か。UI/UX: 実際に更新する担当者が使いやすいかが鍵。`}, en:{title:"Complete CMS Selection Guide", excerpt:"WordPress, PayloadCMS, Strapi, Contentful, microCMS. A 4-axis comparison covering multilingual support, costs, scalability, and UI/UX.", cat:"Web Development", read:"9 min", content:`## Why CMS Selection Matters\n\nYour CMS is the operational heart of your site. Migration is costly.\n\n## 2025 CMS Options\n\nWordPress: 43% share. PayloadCMS: Next.js-native. Strong multilingual. Strapi: Open-source, customizable. Contentful: SaaS, reliable. microCMS: Japanese, great local support.\n\n## 4 Selection Criteria\n\nMultilingual, operating costs (fees + staffing), scalability, UI/UX for content editors.`}, tags:["CMS","WordPress","ヘッドレスCMS","PayloadCMS","比較"], date:"2025-06-10" },
  { slug:"web-accessibility-basics", ja:{title:"Webアクセシビリティの基本 — 2025年に対応すべき最低限の5項目", excerpt:"2024年4月の法改正で民間企業のWebアクセシビリティ対応が努力義務化。対応すべき最低限の5項目と具体的な実装方法を解説。", cat:"Web制作", read:"7分", content:`## 法的背景\n\n2024年4月、障害者差別解消法の改正により民間事業者のWebアクセシビリティ対応が義務へと引き上げられました。\n\n## 最低限対応すべき5項目\n\n画像にalt属性を付与、キーボード操作に対応（Tab/Enterで全操作可能に）、十分なカラーコントラスト（WCAG 2.1 AA 4.5:1以上）、フォームに適切なラベルを付与、見出しの適切な階層構造（h1→h2→h3）。\n\n## 実装時のポイント\n\nTailwindCSSやshadcn/ui（Radix UIベース）を使えばアクセシビリティ対応が比較的容易です。WAI-ARIA対応が標準で組み込まれています。`}, en:{title:"Web Accessibility Basics — 5 Minimum Requirements for 2025", excerpt:"Japan's 2024 legal revision made web accessibility a duty of care. Learn the 5 minimum requirements and implementation methods.", cat:"Web Development", read:"7 min", content:`## Legal Background\n\nJapan's disability discrimination law was amended in April 2024 making accessibility mandatory.\n\n## 5 Minimum Requirements\n\nAlt attributes on images, keyboard navigation, sufficient color contrast (WCAG 2.1 AA 4.5:1+), proper form labels, correct heading hierarchy.\n\n## Implementation Tips\n\nTailwindCSS and shadcn/ui (Radix UI) include WAI-ARIA support by default, making accessibility significantly easier.`}, tags:["アクセシビリティ","Web制作","法改正","UI/UX"], date:"2025-06-05" },
  // デジタルマーケティング
  { slug:"digital-marketing-framework-2025", ja:{title:"デジタルマーケティング全体設計 — 集客から成約までの5ステップフレームワーク", excerpt:"バラバラになりがちな施策を集客→興味喚起→比較検討→成約→育成の5ステップで体系化。具体的なKPIとともに解説。", cat:"デジタルマーケティング", read:"10分", content:`## なぜ全体設計が必要か\n\n多くの企業ではSEO、SNS広告、メルマガ、展示会などの個別施策がバラバラに実施されています。1つのフレームワークに統合することで相乗効果が生まれ投資対効果が大きく改善します。\n\n## 5ステップフレームワーク\n\n集客: SEO/GEO、MEO、SNS、広告で認知獲得。興味喚起: LP、ホワイトペーパー、動画で関心を深める。比較検討: 事例、お客様の声、料金表で信頼構築。成約: フォーム、チャット、電話で受注。育成: メルマガ、SNS、セミナーでリピート・紹介促進。\n\n## 各ステップのKPI\n\n集客: 検索流入数、SNSインプレッション数。興味喚起: LPのCVR。比較検討: 事例ページ回遊率。成約: 問い合わせ数、成約率。育成: リピート率、紹介経由問い合わせ数。`}, en:{title:"Digital Marketing Architecture — A 5-Step Framework", excerpt:"Systematize scattered digital marketing with a 5-step framework: Acquisition → Interest → Consideration → Conversion → Nurture. Concrete KPIs included.", cat:"Digital Marketing", read:"10 min", content:`## Why Architecture Matters\n\nIntegrating scattered tactics into one framework creates synergy and dramatically improves ROI.\n\n## The 5-Step Framework\n\nAcquisition: SEO/GEO, MEO, social, ads. Interest: LPs, white papers, video. Consideration: case studies, testimonials, pricing. Conversion: forms, chat, phone. Nurture: email, social, seminars.\n\n## KPIs Per Stage\n\nAcquisition: search traffic, impressions. Interest: LP CVR. Consideration: case study depth. Conversion: inquiries, close rate. Nurture: repeat rate, referrals.`}, tags:["デジタルマーケティング","フレームワーク","集客","KPI"], date:"2025-08-15" },
  { slug:"landing-page-optimization", ja:{title:"成約率を2倍にするLP改善 — 心理トリガーを活用した10の施策", excerpt:"CVRが上がらないLPの多くは心理トリガーの使い方が不十分です。希少性、社会的証明、返報性、一貫性など行動経済学に基づいた10施策を紹介。", cat:"デジタルマーケティング", read:"9分", content:`## LP改善の考え方\n\nLP改善は勘や好みではなくデータと心理原則に基づいて行うべきです。\n\n## 10の心理トリガー施策\n\n希少性（「残り3席」）、社会的証明（導入実績・お客様の声）、返報性（無料資料で先に価値提供）、一貫性（小さな「はい」から始める）、権威（専門家推薦・資格）、好意（共感ストーリー）、損失回避（「導入しないリスク」の提示）、アンカリング（高額プランを先に）、バンドワゴン効果（「多くの企業が選んでいます」）、単純化（選択肢を絞る）。`}, en:{title:"Double Your Conversion Rate — 10 LP Optimization Tactics", excerpt:"Low-converting LPs often underuse psychological triggers. 10 tactics based on behavioral economics: scarcity, social proof, reciprocity, consistency, and more.", cat:"Digital Marketing", read:"9 min", content:`## LP Optimization Mindset\n\nOptimization should be driven by data and psychological principles, not intuition.\n\n## 10 Psychological Trigger Tactics\n\nScarcity, Social proof, Reciprocity, Consistency, Authority, Liking, Loss aversion, Anchoring, Bandwagon effect, Simplification.`}, tags:["LP","CVR","コンバージョン","心理トリガー","改善"], date:"2025-07-28" },
  { slug:"video-marketing-beginners", ja:{title:"動画マーケティング入門 — 予算50万円から始める動画集客のすべて", excerpt:"スマホ1台から始める動画制作、YouTube/Instagram/TikTokの使い分け、動画SEOの基本まで低予算で始める動画集客を解説。", cat:"デジタルマーケティング", read:"8分", content:`## 動画マーケティングの現在地\n\n2025年、インターネットトラフィックの82%が動画コンテンツと言われています。\n\n## プラットフォーム別戦略\n\nYouTube: 検索型。SEOの延長として課題解決動画が有効。Instagram Reels: 発見型。短尺で視覚的インパクト重視。TikTok: トレンド型。UGC的アプローチ。\n\n## 低予算で始める3ステップ\n\n1. スマホ撮影から始める（照明とマイクだけ投資）。2. 編集はCanvaやCapCutで。3. まずは10本作る（質より量。10本で勝ちパターンが見える）。`}, en:{title:"Video Marketing for Beginners", excerpt:"From smartphone production to platform strategy and video SEO basics — how to start video marketing on a budget.", cat:"Digital Marketing", read:"8 min", content:`## Video Marketing Today\n\n82% of internet traffic is video in 2025.\n\n## Platform Strategy\n\nYouTube: Search-driven, problem-solving videos. Instagram: Discovery-driven, short-form visual impact. TikTok: Trend-driven, UGC approach.\n\n## 3 Steps on a Budget\n\n1. Start with smartphone (invest only in lighting/mic). 2. Edit with Canva or CapCut. 3. Make 10 videos first — quantity over quality.`}, tags:["動画マーケティング","YouTube","動画制作","集客"], date:"2025-07-12" },
  { slug:"sns-marketing-strategy-2025", ja:{title:"2025年SNSマーケティング戦略 — プラットフォーム別・業種別の最適解", excerpt:"X、Instagram、LinkedIn、TikTok、Facebook。2025年に注力すべきSNSを業種別・目的別に整理し最新動向と運用のコツを解説。", cat:"デジタルマーケティング", read:"10分", content:`## SNSマーケティングの全体像\n\n2025年、SNSは「情報発信の場」から「購買の場」へと進化しました。\n\n## 業種別おすすめSNS\n\nBtoB（IT・コンサル）: LinkedInを軸にXで専門性発信。BtoC（小売・飲食）: Instagramを軸にTikTokで若年層リーチ。BtoBtoC（不動産・教育）: YouTubeを軸にInstagramで補完。\n\n## 運用のコツ\n\nコンテンツの再利用（1記事をスレッド、リール、ブログに展開）。投稿時間の最適化。コミュニティ運営（コメント返信・DM対応を徹底）。`}, en:{title:"2025 Social Media Marketing Strategy", excerpt:"X, Instagram, LinkedIn, TikTok, Facebook. A platform-by-platform, industry-by-industry breakdown with latest algorithm trends and operating tips.", cat:"Digital Marketing", read:"10 min", content:`## Social Media Landscape\n\nIn 2025, social media has evolved from broadcast channels to purchase channels.\n\n## Platform by Industry\n\nB2B: LinkedIn anchor + X expertise. B2C: Instagram anchor + TikTok for youth. B2B2C: YouTube anchor + Instagram complement.\n\n## Operating Tips\n\nContent repurposing, post timing optimization, community management (prioritize replies and DMs).`}, tags:["SNS","マーケティング","Instagram","LinkedIn"], date:"2025-06-28" },
  { slug:"marketing-automation-intro", ja:{title:"MA（マーケティングオートメーション）入門 — 最小構成ではじめる顧客育成の仕組み", excerpt:"MAツールは高額という先入観を捨てましょう。n8nやMakeを使えば月額数千円からMAを構築できます。実際のワークフロー例とともに解説。", cat:"デジタルマーケティング", read:"8分", content:`## MAは高くない\n\nHubSpotやMarketoのような高額ツールを想像するかもしれませんがn8nやMakeで必要な機能のほとんどを実現できます。\n\n## 最小構成MAの4要素\n\nリード獲得: LPやフォームからのデータを自動でDBに保存。スコアリング: 閲覧・開封・DLなどの行動を自動スコア化。セグメンテーション: スコアや属性で自動リスト分け。ステップメール: セグメントに応じた最適なメールを自動配信。\n\n## n8n実装例\n\n問い合わせフォーム→n8n Webhook→Google Sheets→Slack通知。メルマガ開封者→関連ホワイトペーパー自動送付。未接触リード→自動再アプローチメール。`}, en:{title:"Marketing Automation 101", excerpt:"Forget the notion that MA tools are expensive. With n8n and Make, you can build marketing automation starting at a few dollars a month. Real workflow examples included.", cat:"Digital Marketing", read:"8 min", content:`## MA Isn't Expensive\n\nn8n and Make can deliver most of what expensive tools do.\n\n## 4 Elements of Minimal MA\n\nLead capture: auto-save form data. Scoring: auto-score behaviors. Segmentation: auto-sort leads. Drip email: auto-send optimized emails per segment.\n\n## n8n Examples\n\nContact form→Webhook→Sheets→Slack. Newsletter openers→auto-send white paper. Inactive leads→re-engagement email.`}, tags:["MA","マーケティングオートメーション","n8n","Make"], date:"2025-06-18" },
]

// Combine posts
export const ALL_POSTS: SeedPost[] = [...POSTS_PART1, ...POSTS_PART2]

export const SERVICES = [
  { slug:"jaas", ja:{name:"Japan-as-a-Service (JaaS)", tagline:"海外企業の日本市場参入をフルスタックで支援", features:["市場調査・競合分析（公開データ + AI構造化）","現地法人設立支援（司法書士・税理士コーディネート）","日本語LP/EC構築（12カ国語対応 + GEO最適化）","MEO/SEO/SNS集客の現地運用代行","請求書発行・経理代行（Stripe + 国内決済）","日本人カスタマーサポート（チャット/メール/電話）"]}, en:{name:"Japan-as-a-Service (JaaS)", tagline:"Full-stack market entry support for global SMBs", features:["Market research & competitor analysis","Local entity setup","Japanese LP/EC build (12-language + GEO)","MEO/SEO/Social ops","Invoicing & accounting (Stripe + JP payments)","Japanese customer support"]}, icon:"Globe", sort:1 },
  { slug:"web", ja:{name:"Web制作", tagline:"集客に強いモダンなビジネスサイトを", features:["コーポレートサイト/LP/ECサイト制作","レスポンシブデザイン（スマホ・タブレット対応）","SEO内部対策 + 構造化データ実装","CMS管理画面（PayloadCMS / WordPress）","Next.js + Tailwind CSS + shadcn/ui 採用","12カ国語多言語対応"]}, en:{name:"Web Development", tagline:"Modern, conversion-focused business websites", features:["Corporate/LP/EC site development","Responsive design","On-page SEO + structured data","CMS admin","Next.js + Tailwind CSS + shadcn/ui","12-language i18n"]}, icon:"Globe", sort:2 },
  { slug:"meo", ja:{name:"MEO対策", tagline:"Googleマップで上位表示、地域集客を最大化", features:["Googleビジネスプロフィール最適化","口コミ獲得・返信代行","投稿運用（最新情報・特典の定期発信）","ローカルSEO（地域キーワード対策）","順位レポート・分析レポート（月次）","競合分析と改善提案"]}, en:{name:"MEO (Local SEO)", tagline:"Top Google Maps rankings for maximum local reach", features:["GBP optimization","Review acquisition & response","Post management","Local SEO","Ranking & analytics reports","Competitor analysis"]}, icon:"MapPin", sort:3 },
  { slug:"seo", ja:{name:"SEO / GEO対策", tagline:"検索エンジンとAI検索からの集客を最大化", features:["キーワード戦略立案・検索意図分析","コンテンツSEO（記事制作・リライト）","テクニカルSEO（サイト速度・構造改善）","GEO対策（ChatGPT/Perplexity最適化）","構造化データ（JSON-LD）実装","月次レポート・分析レポート"]}, en:{name:"SEO / GEO", tagline:"Maximize traffic from search engines and AI", features:["Keyword strategy & intent analysis","Content SEO","Technical SEO","GEO (AI search optimization)","Structured data implementation","Monthly reporting"]}, icon:"Search", sort:4 },
  { slug:"ai", ja:{name:"AI導入支援 / DX", tagline:"AIと自動化で業務を革新する", features:["業務分析・自動化設計コンサルティング","Dify構築（AIチャットボット・社内ナレッジQ&A）","n8nワークフロー自動化（1000+サービス連携）","DeepSeek V4統合（低コストLLM活用）","社内研修・AIリテラシー向上支援","運用保守・継続改善"]}, en:{name:"AI Enablement / DX", tagline:"Transform operations with AI and automation", features:["Process analysis & automation consulting","Dify setup","n8n workflow automation","DeepSeek V4 integration","Staff training & AI literacy","Ongoing operations"]}, icon:"Bot", sort:5 },
]

export const PRICING_PLANS = [
  { planJa:"スターター", planEn:"Starter", sid:"web", price:300000, cur:"jpy", bill:"one-time", descJa:"5ページのシンプルなコーポレートサイト。レスポンシブデザイン、問い合わせフォーム付き。", descEn:"Simple 5-page corporate site with responsive design and contact form.", featJa:["レスポンシブデザイン","問い合わせフォーム","SEO基本対策","CMS管理画面","1ヶ月無料保守"], featEn:["Responsive design","Contact form","Basic SEO","CMS admin","1 month free maintenance"], pop:false, ctaJa:"詳細を見る", ctaEn:"Learn More", sort:1 },
  { planJa:"ビジネス", planEn:"Business", sid:"web", price:800000, cur:"jpy", bill:"one-time", descJa:"10ページ以上の本格コーポレートサイト。多言語対応、ブログ機能、アニメーション演出付き。", descEn:"Full corporate site (10+ pages) with multilingual support, blog, and animations.", featJa:["全ページレスポンシブ","CMS + ブログ機能","SEO内部対策 + 構造化データ","多言語対応（3言語まで）","アニメーション演出","3ヶ月無料保守"], featEn:["Fully responsive","CMS + blog","On-page SEO + structured data","3-language support","Animation design","3 months free maintenance"], pop:true, ctaJa:"詳細を見る", ctaEn:"Learn More", sort:2 },
  { planJa:"エンタープライズ", planEn:"Enterprise", sid:"web", price:2000000, cur:"jpy", bill:"one-time", descJa:"フルカスタムWebサイト/アプリケーション。AI機能、外部API連携、12カ国語対応。", descEn:"Fully custom web/application. AI features, API integration, up to 12 languages.", featJa:["フルカスタム設計","AI機能統合","外部API/SaaS連携","12カ国語多言語対応","年間保守・運用付き","専任PM + デザイナー + エンジニア"], featEn:["Full custom design","AI integration","External API integration","12-language i18n","Annual maintenance","Dedicated PM + designer + engineer"], pop:false, ctaJa:"資料請求", ctaEn:"Request Info", sort:3 },
  { planJa:"スターター", planEn:"Starter", sid:"meo", price:30000, cur:"jpy", bill:"monthly", descJa:"Googleビジネスプロフィールの基本最適化。プロフィール整備と月次レポート付き。", descEn:"Basic GBP optimization with profile setup and monthly reports.", featJa:["プロフィール最適化","写真投稿（月4回）","口コミ返信代行","月次順位レポート"], featEn:["Profile optimization","Photo posts (4/month)","Review response","Monthly ranking report"], pop:false, ctaJa:"詳細を見る", ctaEn:"Learn More", sort:4 },
  { planJa:"ビジネス", planEn:"Business", sid:"meo", price:80000, cur:"jpy", bill:"monthly", descJa:"投稿運用 + 口コミ戦略 + 競合分析を含む本格MEO対策。", descEn:"Full MEO including post management, review strategy, and competitor analysis.", featJa:["プロフィール最適化 + 継続改善","投稿運用（週2回）","口コミ獲得戦略 + 返信代行","競合分析 + 改善提案","月次詳細レポート"], featEn:["Profile optimization + improvement","Post management (2/week)","Review strategy + response","Competitor analysis","Monthly detailed report"], pop:true, ctaJa:"詳細を見る", ctaEn:"Learn More", sort:5 },
  { planJa:"プレミアム", planEn:"Premium", sid:"meo", price:150000, cur:"jpy", bill:"monthly", descJa:"複数拠点対応 + ローカルSEO + SNS連携を含むフルパッケージ。", descEn:"Multi-location support + local SEO + social media full package.", featJa:["全MEO機能（ビジネスプラン内容）","複数拠点対応","ローカルSEO対策","SNS連携運用","専任運用担当者"], featEn:["All Business plan features","Multi-location support","Local SEO","Social media integration","Dedicated account manager"], pop:false, ctaJa:"資料請求", ctaEn:"Request Info", sort:6 },
  { planJa:"スターター", planEn:"Starter", sid:"seo", price:50000, cur:"jpy", bill:"monthly", descJa:"キーワード戦略 + コンテンツSEOの基本パッケージ。月2記事の制作代行付き。", descEn:"Basic keyword strategy + content SEO with 2 articles/month.", featJa:["キーワード戦略立案","コンテンツSEO（月2記事）","テクニカルSEO監査","月次レポート"], featEn:["Keyword strategy","Content SEO (2 articles/month)","Technical SEO audit","Monthly report"], pop:false, ctaJa:"詳細を見る", ctaEn:"Learn More", sort:7 },
  { planJa:"ビジネス", planEn:"Business", sid:"seo", price:150000, cur:"jpy", bill:"monthly", descJa:"SEO + GEO統合対策。月4記事制作 + AI検索最適化を含む本格パッケージ。", descEn:"Integrated SEO + GEO. 4 articles/month + AI search optimization.", featJa:["キーワード戦略 + 検索意図分析","コンテンツSEO（月4記事）","テクニカルSEO（サイト改善）","GEO対策（AI検索最適化）","構造化データ実装","月次詳細レポート"], featEn:["Keyword strategy + intent analysis","Content SEO (4 articles/month)","Technical SEO","GEO optimization","Structured data","Monthly detailed report"], pop:true, ctaJa:"詳細を見る", ctaEn:"Learn More", sort:8 },
  { planJa:"エンタープライズ", planEn:"Enterprise", sid:"seo", price:400000, cur:"jpy", bill:"monthly", descJa:"大規模サイト向けSEO + GEO + 被リンク獲得戦略のフルパッケージ。", descEn:"Full SEO + GEO + link-building for large-scale sites.", featJa:["全SEO/GEO機能","被リンク獲得戦略","多言語SEO（12カ国語）","コンテンツマーケティング戦略","専任SEOコンサルタント"], featEn:["All SEO/GEO features","Link-building strategy","Multilingual SEO","Content marketing strategy","Dedicated SEO consultant"], pop:false, ctaJa:"資料請求", ctaEn:"Request Info", sort:9 },
  { planJa:"スターター", planEn:"Starter", sid:"ai", price:100000, cur:"jpy", bill:"monthly", descJa:"業務分析 + Difyチャットボット構築の入門パッケージ。", descEn:"Process analysis + Dify chatbot build starter package.", featJa:["業務分析（1業務）","Difyチャットボット構築","ナレッジベース設定","操作研修（1回）"], featEn:["Process analysis (1 workflow)","Dify chatbot build","Knowledge base setup","Training (1 session)"], pop:false, ctaJa:"詳細を見る", ctaEn:"Learn More", sort:10 },
  { planJa:"ビジネス", planEn:"Business", sid:"ai", price:300000, cur:"jpy", bill:"monthly", descJa:"複数業務の自動化設計 + Dify/n8n導入 + DeepSeek統合。", descEn:"Multi-workflow automation + Dify/n8n + DeepSeek integration.", featJa:["業務分析（3業務）","Dify + n8n導入","DeepSeek V4統合","社内研修（3回）","月次サポート"], featEn:["Process analysis (3 workflows)","Dify + n8n deployment","DeepSeek V4 integration","Training (3 sessions)","Monthly support"], pop:true, ctaJa:"詳細を見る", ctaEn:"Learn More", sort:11 },
  { planJa:"DXパートナー", planEn:"DX Partner", sid:"ai", price:800000, cur:"jpy", bill:"monthly", descJa:"全社DX推進パートナー。専任コンサルタントが伴走しAI化・自動化・データ活用を全面支援。", descEn:"Company-wide DX partner. Dedicated consultant for AI, automation, and data enablement.", featJa:["全社業務棚卸し + DXロードマップ","Dify/n8n/DeepSeekフル導入","カスタムAIアプリ開発","データ分析基盤構築","役員向けAI戦略コンサル","専任DXコンサルタント（週次定例）"], featEn:["Company-wide audit + DX roadmap","Full Dify/n8n/DeepSeek deployment","Custom AI app development","Data analytics foundation","Executive AI strategy consulting","Dedicated DX consultant (weekly)"], pop:false, ctaJa:"お問い合わせ", ctaEn:"Contact Us", sort:12 },
]

export const WORKS = [
  { slug:"sericia-d2c", ja:{title:"Sericia — 日本クラフト食品のグローバルD2Cサイト", industry:"食品・D2C", desc:"日本全国の訳ありクラフト食品を世界80カ国に届けるD2Cブランド", challenge:"海外向け販売のための多言語ECサイト構築と購入導線の最適化", solution:"PayloadCMS + Medusa v2を統合したヘッドレスECをNext.jsで構築。12カ国語対応、AIチャットボット、Push PWA。", metrics:"公開後3ヶ月で月間PV 5万達成、海外売上比率60%"}, en:{title:"Sericia — Global D2C Site", industry:"Food & D2C", desc:"D2C brand delivering Japanese craft food to 80+ countries.", challenge:"Building a multilingual ecommerce site for global sales.", solution:"Built headless ecommerce on Next.js + PayloadCMS + Medusa v2. 12-language, AI chatbot, Push PWA.", metrics:"50K monthly PV within 3 months, 60% overseas revenue."}, tags:["EC","D2C","多言語","Next.js","PayloadCMS"], color:"rose" as const, sort:1 },
  { slug:"appexxme-sales-os", ja:{title:"Appexxme — AI営業自動化プラットフォーム", industry:"SaaS・営業DX", desc:"公開データ×AIで営業リスト作成から診断レポート自動生成までを一貫自動化", challenge:"グローバル8言語×6デザインの営業診断レポートを人手を介さず自動生成する仕組みの構築", solution:"Dify + n8n + DeepSeek V4 + Playwrightによる自律型営業OS。企業情報の自動収集→AI診断→レポート生成→フォーム送信までをイベント駆動で自動化。", metrics:"従来比98%工数削減、月間1,000件の自動診断を実現"}, en:{title:"Appexxme — AI Sales Automation Platform", industry:"SaaS & Sales DX", desc:"End-to-end automation from lead discovery to diagnostic report generation.", challenge:"Building a fully automated pipeline for diagnostic reports in 8 languages × 6 designs.", solution:"Autonomous sales OS with Dify + n8n + DeepSeek V4 + Playwright. Event-driven automation.", metrics:"98% reduction in manual effort, 1,000 automated diagnoses/month."}, tags:["AI","営業自動化","Dify","n8n","DeepSeek"], color:"violet" as const, sort:2 },
  { slug:"airtabi-travel-platform", ja:{title:"AirTabi — AI搭載 多言語トラベルプラットフォーム", industry:"旅行・OTA", desc:"AIが旅程を自動生成する8カ国語対応の旅行予約プラットフォーム", challenge:"8カ国語のSEOコンテンツとAIプランナーを統合した地方創生×インバウンドプラットフォームの構築", solution:"pSEO設計による多言語ページ自動生成、DeepSeek V4によるAI旅程プランナー、Stripe Connectによるパートナー決済基盤", metrics:"8カ国語×主要観光地100エリアのページを自動生成、検索流入の85%が多言語ページ経由"}, en:{title:"AirTabi — AI-Powered Multilingual Travel Platform", industry:"Travel & OTA", desc:"8-language travel booking platform with AI-generated itineraries.", challenge:"Building a regional revitalization × inbound platform with 8-language SEO and AI trip planner.", solution:"Auto-generated multilingual pages via pSEO, AI itinerary planner with DeepSeek V4, Stripe Connect partner payments.", metrics:"Auto-generated pages for 100 tourist areas × 8 languages. 85% of search traffic via multilingual pages."}, tags:["旅行","多言語","AI","pSEO","Stripe"], color:"teal" as const, sort:3 },
  { slug:"paradigm-corporate-site", ja:{title:"Paradigm — コーポレートサイト全面リニューアル", industry:"IT・Web制作", desc:"Next.js + PayloadCMS + 12カ国語対応の自社コーポレートサイト", challenge:"旧WordPressサイトからの完全移行。パフォーマンス改善、多言語対応、ブロックベースページ構築を同時実現。", solution:"Next.js App Router + PayloadCMSで再構築。10種ブロックタイプのビジュアルページビルダー、12カ国語自動翻訳、Lighthouse 95+。", metrics:"Lighthouseパフォーマンス98点、表示速度3.2倍改善、海外問い合わせ3倍増"}, en:{title:"Paradigm — Full Corporate Site Redesign", industry:"IT & Web Dev", desc:"In-house corporate site on Next.js + PayloadCMS with 12-language support.", challenge:"Full migration from legacy WordPress with simultaneous performance, multilingual, and block-based building.", solution:"Rebuilt with Next.js + PayloadCMS. Visual page builder (10 block types), 12-language auto-translation, Lighthouse 95+.", metrics:"Lighthouse 98, 3.2x speed improvement, 3x international inquiries."}, tags:["コーポレートサイト","Next.js","PayloadCMS","多言語","リニューアル"], color:"indigo" as const, sort:4 },
  { slug:"dxdoctor-platform", ja:{title:"DX Doctor — 中小企業DX診断プラットフォーム", industry:"DX・コンサルティング", desc:"Webサイト解析→AI診断→補助金診断までを自動化する中小企業DX診断サービス", challenge:"補助金・DX診断の専門家不足を補う、Webサイトの公開情報だけで高精度な診断を行うAIシステムの構築", solution:"Playwrightによる自動解析、DeepSeek V4による業界別診断、Dify+n8nによるレポート自動生成。人間専門家が最終レビューのみ行うハイブリッドモデル。", metrics:"診断1件あたりの工数90%削減、月間500社の自動診断が可能に"}, en:{title:"DX Doctor — SMB DX Diagnostic Platform", industry:"DX & Consulting", desc:"Automated SMB DX diagnostic service from website analysis to subsidy assessment.", challenge:"Building an AI system for high-accuracy diagnostics from public website data.", solution:"Automated analysis via Playwright, industry diagnosis via DeepSeek V4, auto-reports via Dify+n8n.", metrics:"90% reduction in per-diagnosis effort, capacity for 500 automated diagnoses/month."}, tags:["DX","AI診断","自動化","補助金","DeepSeek"], color:"amber" as const, sort:5 },
  { slug:"temploft-marketplace", ja:{title:"Temploft — Web制作×AI運用のマーケットプレイス", industry:"SaaS・マーケットプレイス", desc:"AIによるWordPressサイト自動運用とテンプレートマーケットプレイスの2軸プラットフォーム", challenge:"WordPressサイトのセキュリティ・更新・バックアップ運用をAIで自動化しつつ日本初の本格テンプレートMPを構築", solution:"AI運用SaaS（自動更新・セキュリティパッチ・パフォーマンス最適化）+ Stripe Connectによるクリエイター向け販売基盤", metrics:"設計フェーズ完了、MVP開発中。CTP（特許出願中）技術をコア差別化要因に。"}, en:{title:"Temploft — Web Dev × AI Operations Marketplace", industry:"SaaS & Marketplace", desc:"Dual-axis platform: AI-powered WordPress management + template marketplace.", challenge:"Building AI automation for WordPress ops alongside Japan's first full-scale template marketplace.", solution:"AI operations SaaS + Stripe Connect creator template sales infrastructure.", metrics:"Design phase complete, MVP in development. CTP (patent-pending) as differentiator."}, tags:["SaaS","WordPress","AI","マーケットプレイス","Stripe"], color:"emerald" as const, sort:6 },
]

export const FAQS = [
  { qJa:"Webサイト制作の期間はどのくらいですか？", qEn:"How long does web development take?", aJa:"制作規模により異なります。5ページ程度のシンプルなコーポレートサイトは1〜2ヶ月、10ページ以上の本格サイトは2〜3ヶ月、ECサイトやフルカスタム開発は3〜6ヶ月が目安です。いずれも企画・設計フェーズを含めた全体期間です。", aEn:"Depends on scope: 5-page corporate site 1-2 months, 10+ page site 2-3 months, ecommerce/custom 3-6 months. All timelines include planning and design.", catJa:"Web制作", catEn:"Web Development", sort:1 },
  { qJa:"MEO対策の効果が出るまでどのくらいかかりますか？", qEn:"How long until MEO shows results?", aJa:"最適化後、即日〜1週間で順位変動が始まります。安定した上位表示には1〜3ヶ月の継続運用が必要です。口コミ数や競合状況で変動します。", aEn:"Ranking changes begin within days to a week. Stable top rankings require 1-3 months of consistent effort.", catJa:"MEO対策", catEn:"MEO", sort:2 },
  { qJa:"SEO対策の費用はいくらですか？", qEn:"How much does SEO cost?", aJa:"月額5万円（スターター）〜40万円（エンタープライズ）の3プランです。サイト規模や目標キーワード数により最適なプランが異なります。まずは無料相談でお見積りします。", aEn:"3 plans from ¥50,000 to ¥400,000/month. Depends on site size and target keywords. Free consultation available.", catJa:"SEO対策", catEn:"SEO", sort:3 },
  { qJa:"多言語対応はどの言語まで可能ですか？", qEn:"How many languages can you support?", aJa:"日本語、英語、韓国語、中国語、ドイツ語、フランス語、スペイン語、ポルトガル語、ロシア語、アラビア語、ベトナム語、インドネシア語の12カ国語です。DeepSeek V4翻訳＋ネイティブチェックで高品質を実現します。", aEn:"12 languages: Japanese, English, Korean, Chinese, German, French, Spanish, Portuguese, Russian, Arabic, Vietnamese, Indonesian. Hybrid of AI translation + native review.", catJa:"多言語対応", catEn:"Multilingual", sort:4 },
  { qJa:"AIチャットボットの導入にはどのくらいの期間が必要ですか？", qEn:"How long does AI chatbot deployment take?", aJa:"既存FAQやマニュアルが整っていれば1〜2週間で初期導入可能です。本格的なワークフロー自動化を含む場合は1〜2ヶ月を見込んでください。", aEn:"1-2 weeks with existing FAQs/manuals. Full workflow automation: 1-2 months.", catJa:"AI導入", catEn:"AI Implementation", sort:5 },
  { qJa:"保守・運用サポートはありますか？", qEn:"Do you provide maintenance and support?", aJa:"はい、全プランに初期無料保守期間（1〜12ヶ月）が含まれます。終了後は月額プランでサーバー管理、セキュリティ更新、コンテンツ更新代行を提供します。", aEn:"Yes, every plan includes free initial maintenance (1-12 months). After that, monthly plans cover server, security, and content updates.", catJa:"運用保守", catEn:"Maintenance", sort:6 },
  { qJa:"全国対応していますか？", qEn:"Do you serve clients nationwide?", aJa:"はい、日本全国対応です。打ち合わせはオンライン（Zoom/Google Meet）を基本とし、必要に応じて訪問も可能です。海外からのお問い合わせも歓迎します。", aEn:"Yes, nationwide. Online meetings primary, in-person available. International inquiries welcome.", catJa:"お取引", catEn:"Business", sort:7 },
  { qJa:"WordPressからNext.jsへの移行は可能ですか？", qEn:"Can you migrate from WordPress to Next.js?", aJa:"可能です。データ移行、URLリダイレクト設計、SEO値保持を含めた完全移行プランがあります。移行期間は既存サイト規模により2週間〜2ヶ月です。", aEn:"Yes. Complete migration covering data transfer, redirects, SEO preservation. 2 weeks to 2 months depending on site size.", catJa:"Web制作", catEn:"Web Development", sort:8 },
  { qJa:"デザインの修正は何回まで可能ですか？", qEn:"How many design revisions?", aJa:"通常2〜3回の大きめな修正と細かな調整は無制限に対応します。追加の大きな方向転換は別途お見積りします。", aEn:"Typically 2-3 major revisions with unlimited minor adjustments. Major directional changes quoted separately.", catJa:"Web制作", catEn:"Web Development", sort:9 },
  { qJa:"支払い方法は何がありますか？", qEn:"What payment methods?", aJa:"銀行振込とStripe経由のクレジットカード（Visa/Mastercard/AMEX）です。請求書払いも可能。月額プランは口座振替またはカード継続決済です。", aEn:"Bank transfer and credit card via Stripe (Visa/Mastercard/AMEX). Invoice payment available. Monthly plans via direct debit or recurring card.", catJa:"お取引", catEn:"Business", sort:10 },
  { qJa:"SEO対策でGoogle1位は保証されますか？", qEn:"Can you guarantee #1 Google ranking?", aJa:"特定キーワードでの1位保証はできません（アルゴリズムは常に変動します）。しかし適切な戦略で上位表示を達成した実績が多数あります。検索流入数と成約数のKPIで成果を評価します。", aEn:"We cannot guarantee #1 for specific keywords (algorithms evolve). However, we have a strong top-ranking track record. We measure by traffic and conversions, not rank guarantees.", catJa:"SEO対策", catEn:"SEO", sort:11 },
  { qJa:"名古屋以外でも打ち合わせは可能ですか？", qEn:"Can we meet outside Nagoya?", aJa:"はい、オンラインを基本としつつ国内主要都市への訪問も可能です。遠方は交通費実費をご請求します。", aEn:"Yes, online primary, major city visits available. Travel expenses billed at cost.", catJa:"お取引", catEn:"Business", sort:12 },
  { qJa:"AI導入にプログラミング知識は必要ですか？", qEn:"Do I need programming knowledge for AI?", aJa:"いいえ。Difyチャットボット構築はノーコード、n8n自動化もドラッグ＆ドロップで完結します。導入研修も含めてサポートします。", aEn:"No. Dify is fully no-code, n8n is drag-and-drop. Training included.", catJa:"AI導入", catEn:"AI Implementation", sort:13 },
  { qJa:"制作実績をもっと見ることはできますか？", qEn:"Can I see more case studies?", aJa:"はい、Worksページで主要プロジェクトを公開中です。個別相談時には業種や課題が近い事例を詳しくご紹介できます。", aEn:"Yes, see our Works page. During consultations, we share detailed matching case studies.", catJa:"その他", catEn:"Other", sort:14 },
  { qJa:"無料相談・お見積もりは可能ですか？", qEn:"Do you offer free consultations?", aJa:"はい、無料で承っています。お問い合わせフォームまたはお電話でお気軽にご連絡ください。初回相談で課題感やご予算をお聞きし最適な提案をします。", aEn:"Yes, free consultations and quotes. Contact us via form or phone. We'll discuss challenges and propose the optimal approach.", catJa:"お取引", catEn:"Business", sort:15 },
]

export const TESTIMONIALS = [
  { author:"田中 健太", titleJa:"代表取締役", titleEn:"CEO", company:"株式会社フードコネクト", quoteJa:"海外展開を検討していた際、JaaSの提案が非常に的確でした。市場調査からLP構築、決済基盤まで一貫支援いただき、わずか3ヶ月で海外売上が全体の40%を超えました。多言語対応の品質も高く海外顧客からの評価も上々です。", quoteEn:"The JaaS proposal was spot-on. End-to-end support from market research to LP and payments helped international sales surpass 40% of revenue in just 3 months.", rating:5, tag:"web" as const, consent:true, pub:true, sort:1 },
  { author:"佐藤 美咲", titleJa:"マーケティング部長", titleEn:"Marketing Director", company:"メイクリーン株式会社", quoteJa:"MEO対策をお願いしてからGoogleマップ表示順位が3ページ目から1位に上がりました。口コミ返信代行も丁寧で顧客満足度向上にも貢献。毎月のレポートも経営会議でそのまま使える資料です。", quoteEn:"Since starting MEO, our Google Maps ranking went from page 3 to #1. Review response service is meticulous and boosted satisfaction. Reports are presentation-ready.", rating:5, tag:"meo" as const, consent:true, pub:true, sort:2 },
  { author:"鈴木 太郎", titleJa:"IT統括部長", titleEn:"Head of IT", company:"山陽工業株式会社", quoteJa:"AIチャットボット導入でカスタマーサポートの一次対応が完全自動化されました。問い合わせ対応時間が平均2時間から3分に短縮されサポートチームの残業もほぼゼロに。ROIは導入後4ヶ月でプラス転換しました。", quoteEn:"AI chatbot completely automated first-response support. Response time dropped from 2 hours to 3 minutes, overtime nearly vanished. ROI positive within 4 months.", rating:5, tag:"ai" as const, consent:true, pub:true, sort:3 },
  { author:"山本 直子", titleJa:"経営企画室", titleEn:"Corporate Planning", company:"株式会社リージョナルフーズ", quoteJa:"SEO/GEO対策を総合的にお願いしました。特にGEOの効果が顕著でChatGPTやPerplexity経由の流入が前年比4倍に。検索意図に沿ったコンテンツ設計のおかげで問い合わせの質も明らかに向上しています。", quoteEn:"Integrated SEO/GEO services. GEO impact is striking — traffic from ChatGPT and Perplexity up 4x YoY. Content designed around search intent elevated inquiry quality.", rating:5, tag:"seo" as const, consent:true, pub:true, sort:4 },
  { author:"伊藤 健一", titleJa:"代表取締役", titleEn:"CEO", company:"株式会社グローカル", quoteJa:"コーポレートサイトリニューアルをお願いしました。表示速度が劇的に改善しスマホからの問い合わせが2倍に。管理画面も直感的でスタッフだけで日常更新ができるようになりました。デザインも取引先から高評価です。", quoteEn:"Corporate site redesign. Load speed improved dramatically, mobile inquiries doubled. Intuitive admin enables staff to handle daily updates. Partners praise the design.", rating:5, tag:"web" as const, consent:true, pub:true, sort:5 },
  { author:"匿名希望", titleJa:"営業部長", titleEn:"Sales Director", company:"中堅製造業", quoteJa:"DXの進め方が全くわからない状態でしたが、AI導入支援のおかげで小さな業務から自動化を始められました。最初のn8nワークフローで月20時間の残業削減に成功し社内のDX抵抗感も大きく緩和されました。", quoteEn:"We had no idea how to approach DX, but the AI enablement service helped us start small. First n8n workflow cut 20 hours of monthly overtime and reduced internal DX resistance.", rating:4, tag:"ai" as const, consent:true, anon:true, pub:true, sort:6 },
]

export const TEAM_MEMBERS = [
  { nameJa:"代表取締役", nameEn:"CEO", roleJa:"Founder & CEO", roleEn:"Founder & CEO", bioJa:"AI・Web技術を活用した中小企業の成長支援に情熱を注ぐ。複数のSaaSプロダクトをBootstrapで立ち上げPMFからグローバル展開まで一貫リード。", bioEn:"Passionate about empowering SMB growth through AI and web technology. Bootstrap-launched multiple SaaS products from PMF through global expansion.", sort:1 },
  { nameJa:"テクニカルリード", nameEn:"Technical Lead", roleJa:"Senior Full-Stack Engineer", roleEn:"Senior Full-Stack Engineer", bioJa:"Next.js、TypeScript、Supabaseを専門。ヘッドレスCMSアーキテクチャ設計とAIパイプライン構築の経験が豊富。", bioEn:"Full-stack engineer specializing in Next.js, TypeScript, Supabase. Extensive headless CMS architecture and AI pipeline experience.", sort:2 },
  { nameJa:"デザインリード", nameEn:"Design Lead", roleJa:"UX Designer & Frontend Engineer", roleEn:"UX Designer & Frontend Engineer", bioJa:"プロダクトデザインとフロントエンド実装の両方を持ちTailwindCSS/Framer Motion/shadcn/uiを駆使したモダンUI設計が得意。", bioEn:"Bridging product design and frontend. Specializes in modern UI with TailwindCSS, Framer Motion, shadcn/ui.", sort:3 },
]
export async function seedAllContent() {
  const [{ getPayload }, { default: config }] = await Promise.all([
    import("payload"),
    import("@payload-config"),
  ])
  const payload = await getPayload({ config })
  const ctx = { skipAutoTranslate: true }
  const sum: Record<string, { created: number; updated: number; errors: number }> = {}

  async function upsert(collection: string, where: Record<string, unknown>, jaData: Record<string, unknown>, enData?: Record<string, unknown>) {
    const result = { created: 0, updated: 0, errors: 0 }
    try {
      const { docs: ex } = await payload.find({ collection, where, limit: 1 } as Parameters<typeof payload.find>[0])
      let id: string | number
      if (ex.length > 0) {
        const u = await payload.update({ collection, id: ex[0].id, data: jaData, locale: "ja", context: ctx } as unknown as Parameters<typeof payload.update>[0]) as unknown as { id: string | number }
        id = u.id; result.updated++
      } else {
        const c = await payload.create({ collection, data: jaData, locale: "ja", context: ctx } as unknown as Parameters<typeof payload.create>[0]) as unknown as { id: string | number }
        id = c.id; result.created++
      }
      if (enData) {
        await payload.update({ collection, id, data: enData, locale: "en", context: ctx } as unknown as Parameters<typeof payload.update>[0])
      }
    } catch (e) { console.error(`[seed] ${collection}:`, e); result.errors++ }
    return result
  }

  function add(acc: Record<string, { created: number; updated: number; errors: number }>, key: string, r: { created: number; updated: number; errors: number }) {
    const s = acc[key] || { created: 0, updated: 0, errors: 0 }
    s.created += r.created; s.updated += r.updated; s.errors += r.errors
    acc[key] = s
  }

  // Categories
  sum.categories = { created: 0, updated: 0, errors: 0 }
  for (const c of CATEGORIES) {
    const r = await upsert("categories", { slug: { equals: c.slug } }, { name: c.ja.name, slug: c.slug, description: c.ja.desc, color: c.color, sortOrder: c.sort, availableLocales: ["ja","en"] }, { name: c.en.name, description: c.en.desc })
    add(sum, "categories", r)
  }

  // Posts
  sum.posts = { created: 0, updated: 0, errors: 0 }
  for (const p of ALL_POSTS) {
    const r = await upsert("posts", { slug: { equals: p.slug } }, { title: p.ja.title, slug: p.slug, excerpt: p.ja.excerpt, content: textToLexical(p.ja.content), category: p.ja.cat, readTime: p.ja.read, tags: p.tags.map(t => ({ tag: t })), status: "published", publishedAt: new Date(p.date).toISOString(), availableLocales: ["ja","en"] }, { title: p.en.title, excerpt: p.en.excerpt, content: textToLexical(p.en.content), category: p.en.cat, readTime: p.en.read })
    add(sum, "posts", r)
  }

  // Services
  sum.services = { created: 0, updated: 0, errors: 0 }
  for (const s of SERVICES) {
    const r = await upsert("services", { slug: { equals: s.slug } }, { name: s.ja.name, slug: s.slug, tagline: s.ja.tagline, icon: s.icon, features: s.ja.features.map(f => ({ feature: f })), sortOrder: s.sort, availableLocales: ["ja","en"], isActive: true }, { name: s.en.name, tagline: s.en.tagline, features: s.en.features.map(f => ({ feature: f })) })
    add(sum, "services", r)
  }

  // Pricing
  sum.pricing = { created: 0, updated: 0, errors: 0 }
  for (const p of PRICING_PLANS) {
    const r = await upsert("pricing", { serviceId: { equals: p.sid }, planName: { equals: p.planJa } }, { planName: p.planJa, serviceId: p.sid, price: p.price, currency: p.cur, billingCycle: p.bill, description: p.descJa, features: p.featJa.map(f => ({ feature: f, included: true })), isPopular: p.pop, ctaLabel: p.ctaJa, sortOrder: p.sort, availableLocales: ["ja","en"] }, { planName: p.planEn, description: p.descEn, features: p.featEn.map(f => ({ feature: f, included: true })), ctaLabel: p.ctaEn })
    add(sum, "pricing", r)
  }

  // Works
  sum.works = { created: 0, updated: 0, errors: 0 }
  for (const w of WORKS) {
    const r = await upsert("works", { slug: { equals: w.slug } }, { title: w.ja.title, slug: w.slug, industry: w.ja.industry, description: w.ja.desc, challenge: w.ja.challenge, solution: w.ja.solution, metrics: w.ja.metrics, tags: w.tags.map(t => ({ tag: t })), color: w.color, sortOrder: w.sort, availableLocales: ["ja","en"], isPublished: true }, { title: w.en.title, industry: w.en.industry, description: w.en.desc, challenge: w.en.challenge, solution: w.en.solution, metrics: w.en.metrics })
    add(sum, "works", r)
  }

  // FAQs
  sum.faqs = { created: 0, updated: 0, errors: 0 }
  for (const f of FAQS) {
    const r = await upsert("faqs", { question: { equals: f.qJa } }, { question: f.qJa, answer: textToLexical(f.aJa), category: f.catJa, sortOrder: f.sort, availableLocales: ["ja","en"] }, { question: f.qEn, answer: textToLexical(f.aEn), category: f.catEn })
    add(sum, "faqs", r)
  }

  // Testimonials
  sum.testimonials = { created: 0, updated: 0, errors: 0 }
  for (const t of TESTIMONIALS) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const anon = (t as any).anon || false
    const r = await upsert("testimonials", { authorName: { equals: t.author }, company: { equals: t.company } }, { quote: t.quoteJa, authorName: t.author, authorTitle: t.titleJa, company: t.company, rating: t.rating, serviceTag: t.tag, consentGiven: t.consent, isAnonymous: anon, isPublished: t.pub, sortOrder: t.sort, availableLocales: ["ja","en"] }, { quote: t.quoteEn, authorTitle: t.titleEn })
    add(sum, "testimonials", r)
  }

  // Team Members
  sum.team = { created: 0, updated: 0, errors: 0 }
  for (const m of TEAM_MEMBERS) {
    const r = await upsert("team-members", { name: { equals: m.nameJa } }, { name: m.nameJa, role: m.roleJa, bio: m.bioJa, sortOrder: m.sort, availableLocales: ["ja","en"], isActive: true }, { name: m.nameEn, role: m.roleEn, bio: m.bioEn })
    add(sum, "team", r)
  }

  // CMS Homepage
  sum.pages = { created: 0, updated: 0, errors: 0 }
  try {
    const layout = [
      { blockType: "hero", variant: "centered", badge: "PARADIGM", title: "テクノロジーで、ビジネスの未来を創る", subtitle: "AI × Web × グローバル — 中小企業のデジタル競争力を、テクノロジーの力で引き上げます。Webサイト制作からAI導入、海外展開支援まで、すべてをワンストップで。", primaryCtaLabel: "まずは無料相談", primaryCtaHref: "/contact", secondaryCtaLabel: "制作実績を見る", secondaryCtaHref: "/works" },
      { blockType: "section", kicker: "SERVICES", title: "選べる5つのサービス", subtitle: "Web制作からAI導入・海外展開まで、ビジネスの成長ステージに合わせた最適なサービスを提供します。", alignment: "center", background: "default" },
      { blockType: "card-grid", variant: "bento", columns: 3, cards: [{ icon:"Globe", title:"Web制作", description:"Next.js + PayloadCMSによる高性能サイト構築。SEO/GEO/MEO標準対応、12カ国語多言語対応。", href:"/services/web", highlighted:false },{ icon:"MapPin", title:"MEO対策", description:"Googleマップ検索で上位表示。口コミ戦略と投稿運用で地域集客を最大化。", href:"/services/meo", highlighted:false },{ icon:"Search", title:"SEO/GEO対策", description:"検索エンジン＋AI検索の両方から集客。データドリブンなキーワード戦略。", href:"/services/seo", highlighted:true },{ icon:"Bot", title:"AI導入支援", description:"DeepSeek V4 + Dify + n8nで業務自動化。月額数万円から始めるAI/DX。", href:"/services/ai", highlighted:false },{ icon:"Globe", title:"海外展開支援 (JaaS)", description:"日本市場参入をフルスタックでサポート。市場調査からLP構築、決済・CSまで。", href:"/services/jaas", highlighted:false }] },
      { blockType: "cta", title: "まずは無料相談から", subtitle: "御社の課題と目標をお聞かせください。最適なソリューションをご提案します。", primaryCtaLabel: "無料相談を申し込む", primaryCtaHref: "/contact", background: "gradient" },
      { blockType: "stats", kicker: "ACHIEVEMENTS", title: "数字で見るParadigm", stats: [{ value:"12", label:"対応言語", sublabel:"日本語からアラビア語まで" },{ value:"5", label:"サービス", sublabel:"Web/MEO/SEO/AI/海外展開" },{ value:"98%", label:"Lighthouseスコア", sublabel:"パフォーマンス最適化済み" },{ value:"6+", label:"プロジェクト実績", sublabel:"SaaS/D2C/コーポレート" }], background: "surface" },
      { blockType: "process", kicker: "PROCESS", title: "プロジェクトの流れ", subtitle: "初回相談から公開・運用まで、安心のステップバイステップ", steps: [{ title:"ヒアリング", description:"課題・目標・予算をお聞きし最適なご提案をいたします", icon:"MessageCircle" },{ title:"企画・設計", description:"サイト構造、デザイン方針、技術選定を確定します", icon:"Pencil" },{ title:"開発・制作", description:"定期的な進捗共有を行いながら透明性の高い開発を進めます", icon:"Code" },{ title:"検証・公開", description:"品質チェック、SEO監査を経て本番環境に公開します", icon:"CheckCircle" },{ title:"運用・改善", description:"アクセス解析、コンテンツ更新、継続的な改善を行います", icon:"RefreshCw" }] },
      { blockType: "cta", title: "ビジネスの成長を、テクノロジーで加速しませんか？", subtitle: "無料相談では、具体的なお見積りと改善の方向性をご提示します。お気軽にご連絡ください。", primaryCtaLabel: "無料相談を申し込む", primaryCtaHref: "/contact", secondaryCtaLabel: "お問い合わせ", secondaryCtaHref: "/contact", background: "accent" },
    ]
    const data = { title: "Paradigm — テクノロジーでビジネスの未来を創る", slug: "home", description: "ParadigmはAI×Web×グローバルで中小企業のデジタル競争力を引き上げます。Web制作、SEO/MEO対策、AI導入支援、海外展開支援をワンストップで提供。", layout, availableLocales: ["ja","en"], isHomepage: true }
    const { docs: ex } = await payload.find({ collection: "pages", where: { slug: { equals: "home" } }, limit: 1 } as Parameters<typeof payload.find>[0])
    if (ex.length > 0) { await payload.update({ collection: "pages", id: ex[0].id, data, locale: "ja", context: ctx } as unknown as Parameters<typeof payload.update>[0]); sum.pages.updated++ }
    else { await payload.create({ collection: "pages", data, locale: "ja", context: ctx } as unknown as Parameters<typeof payload.create>[0]); sum.pages.created++ }
  } catch (e) { console.error(`[seed] pages:`, e); sum.pages.errors++ }

  return sum
}
