-- Migration 011: Drop legacy settings columns from paradigm.settings
-- Generated by scripts/legacy-cleanup-drop-settings.mjs
-- 冪等 (IF EXISTS) — 安全に実行可能
-- 前提: admin が手動で availableLocales / byLocale array へ移行済であること

DO $$ BEGIN
  ALTER TABLE paradigm.settings DROP COLUMN IF EXISTS analytics_umami_website_id;
  ALTER TABLE paradigm.settings DROP COLUMN IF EXISTS analytics_umami_website_id_en;
  ALTER TABLE paradigm.settings DROP COLUMN IF EXISTS calendar_url_ja;
  ALTER TABLE paradigm.settings DROP COLUMN IF EXISTS calendar_url_en;
END $$;