-- Migration 010: Drop legacy locale columns from 5 collections
-- Generated by scripts/legacy-cleanup-drop-locale.mjs
-- 冪等 (IF EXISTS) — 安全に実行可能
-- 前提: admin が手動で availableLocales へ移行済であること

DO $$ BEGIN
  ALTER TABLE paradigm.pages DROP COLUMN IF EXISTS locale;
  ALTER TABLE paradigm.services DROP COLUMN IF EXISTS locale;
  ALTER TABLE paradigm.works DROP COLUMN IF EXISTS locale;
  ALTER TABLE paradigm.pricing DROP COLUMN IF EXISTS locale;
  ALTER TABLE paradigm.faqs DROP COLUMN IF EXISTS locale;
END $$;