"use client"

import { ArrowRight, ArrowUpRight, Check, MapPin } from "lucide-react"
import type { DemoDesignRecipe, DemoMultiPageData, DemoPremiumMedia } from "@/lib/sales/demo-site-types"
import { demoHeadlineClass } from "@/lib/sales/demo-art-direction"
import { PremiumV3Media, PremiumV3MediaCarousel, PremiumV3PageHero, PremiumV3Reveal, PremiumV3Stagger, PremiumV3StaggerItem } from "./PremiumV3Primitives"

export function PremiumV3HospitalityAbout({ data }: { data: DemoMultiPageData }) {
  const about = data.pages.about
  const premium = data.premium!
  const media = uniqueMedia([...premium.gallery, ...premium.heroMedia])
  const motionStyle = data.designRecipe?.motionVariant
  const chapters = about.chapters ?? data.pages.home.narrativeModules ?? []
  const storyParagraphs = about.story.split(/\n{2,}/u).filter(Boolean)
  return <div className="premium-hospitality-inner overflow-hidden bg-[var(--demo-surface)] text-[var(--demo-ink)]">
    <PremiumV3PageHero title={about.title} subtitle={about.subtitle} eyebrow="THE STORY" media={media[0] ?? premium.heroMedia[0]} recipe={data.designRecipe} variant="cinematic" />
    <section className="px-5 py-24 sm:px-10 sm:py-32 lg:px-16 lg:py-40"><div className="mx-auto grid max-w-[1380px] gap-14 lg:grid-cols-[.46fr_1.54fr] lg:gap-24"><PremiumV3Reveal motionStyle={motionStyle}><p className="premium-hospitality-kicker">ABOUT / 01</p><p className="mt-8 max-w-[16rem] text-sm leading-8 text-[var(--demo-muted)]">料理、空間、接客。目に見えるものの奥にある、店の日々をお伝えします。</p><dl className="mt-12 border-t border-[var(--demo-line)] text-sm"><div className="grid grid-cols-[90px_1fr] gap-4 border-b border-[var(--demo-line)] py-4"><dt className="text-[var(--demo-muted)]">拠点</dt><dd>{about.locationLabel}</dd></div><div className="grid grid-cols-[90px_1fr] gap-4 border-b border-[var(--demo-line)] py-4"><dt className="text-[var(--demo-muted)]">業態</dt><dd>{about.industryLabel}</dd></div></dl></PremiumV3Reveal><PremiumV3Reveal motionStyle={motionStyle} delay={.08}><p className="max-w-4xl border-l-2 border-[var(--demo-accent)] pl-6 text-2xl leading-10 [font-family:var(--demo-font-display)] sm:text-3xl sm:leading-[1.7]">{about.mission}</p><div className="mt-10 space-y-6">{storyParagraphs.map((paragraph) => <p key={paragraph} className="whitespace-pre-line text-base leading-9 text-[var(--demo-muted)] sm:text-lg">{paragraph}</p>)}</div><p className="mt-10 max-w-2xl border-t border-[var(--demo-line)] pt-7 text-sm leading-8 text-[var(--demo-muted)]">{about.teamNote}</p></PremiumV3Reveal></div></section>
    {chapters.length > 0 && <section className="border-y border-[var(--demo-line)] bg-[var(--demo-surface-alt)] px-5 py-24 sm:px-10 sm:py-32 lg:px-16"><div className="mx-auto max-w-[1380px]"><PremiumV3Reveal motionStyle={motionStyle} className="grid gap-8 border-b border-[var(--demo-line)] pb-9 md:grid-cols-[1fr_.65fr] md:items-end"><div><p className="premium-hospitality-kicker">THE DETAILS / 02</p><h2 className={`${demoHeadlineClass("一皿の背景にある、日々。", "section")} mt-6 max-w-2xl font-[var(--demo-heading-weight)] [font-family:var(--demo-font-display)]`}>一皿の背景にある、<br />日々。</h2></div><p className="text-sm leading-8 text-[var(--demo-muted)]">素材の選び方、仕込みの手順、店内を整える時間。お店を形づくる判断軸を章立てでご紹介します。</p></PremiumV3Reveal><div className="divide-y divide-[var(--demo-line)]">{chapters.slice(0, 4).map((chapter, index) => <PremiumV3Reveal key={`${chapter.title}-${index}`} motionStyle={motionStyle} delay={index * .05} className="grid gap-6 py-9 md:grid-cols-[82px_.75fr_1.25fr] md:gap-10"><span className="text-xs text-[var(--demo-muted)]">0{index + 1}</span><div><p className="premium-hospitality-kicker">{chapter.eyebrow}</p><h3 className="mt-4 text-2xl [font-family:var(--demo-font-display)]">{chapter.title}</h3></div><div><p className="whitespace-pre-line text-sm leading-8 text-[var(--demo-muted)]">{chapter.body}</p>{chapter.points.length > 0 && <ul className="mt-5 border-t border-[var(--demo-line)] pt-4">{chapter.points.slice(0, 3).map((point) => <li key={point} className="flex items-start gap-3 py-1.5 text-xs leading-6"><Check className="mt-1 h-3.5 w-3.5 shrink-0 text-[var(--demo-accent)]" />{point}</li>)}</ul>}</div></PremiumV3Reveal>)}</div></div></section>}
    <section className="bg-[var(--demo-ink)] px-5 py-24 text-white sm:px-10 sm:py-32 lg:px-16"><div className="mx-auto grid max-w-[1380px] gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div className="relative min-h-[480px] overflow-hidden sm:min-h-[620px]"><PremiumV3Media media={media[1] ?? media[0] ?? premium.heroMedia[0]} className="absolute inset-0" sizes="(max-width:1024px) 100vw, 58vw" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-black/5" /><p className="absolute bottom-7 left-7 max-w-sm text-sm leading-7 text-white/70">{media[1]?.caption ?? media[1]?.alt}</p></div><PremiumV3Reveal motionStyle={motionStyle}><p className="premium-hospitality-kicker text-white/48">VALUES / 03</p><h2 className={`${demoHeadlineClass("大切にしていること。", "section")} mt-6 font-[var(--demo-heading-weight)] [font-family:var(--demo-font-display)]`}>大切にしている<br />こと。</h2><div className="mt-9 border-t border-white/16">{about.values.slice(0, 4).map((value, index) => <div key={value.title} className="grid grid-cols-[46px_1fr] gap-4 border-b border-white/16 py-5"><span className="text-xs text-white/35">0{index + 1}</span><div><h3 className="text-lg [font-family:var(--demo-font-display)]">{value.title}</h3><p className="mt-2 text-sm leading-7 text-white/58">{value.description}</p></div></div>)}</div></PremiumV3Reveal></div></section>
    <section className="px-5 py-24 sm:px-10 sm:py-32 lg:px-16"><div className="mx-auto max-w-[1380px]"><PremiumV3Reveal motionStyle={motionStyle} className="mb-10 flex flex-col gap-5 border-b border-[var(--demo-line)] pb-9 md:flex-row md:items-end md:justify-between"><div><p className="premium-hospitality-kicker">SCENES / 04</p><h2 className={`${demoHeadlineClass(`${data.companyName}の日々`, "section")} mt-5 font-[var(--demo-heading-weight)] [font-family:var(--demo-font-display)]`}>{data.companyName}の日々。</h2></div><a href={`/${data.slug}/services`} className="premium-hospitality-link inline-flex items-center gap-3 text-sm font-bold">メニューを見る<ArrowRight className="h-4 w-4" /></a></PremiumV3Reveal><PremiumV3MediaCarousel media={media} label={`${data.companyName}の日々の写真`} variant="wide" /></div></section>
  </div>
}

export function PremiumV3HospitalityServices({ data }: { data: DemoMultiPageData }) {
  const services = data.pages.services
  const premium = data.premium!
  const media = uniqueMedia([...premium.gallery, ...premium.heroMedia])
  const motionStyle = data.designRecipe?.motionVariant
  const guidance = services.guidance ?? []
  return <div className="premium-hospitality-inner overflow-hidden bg-[var(--demo-surface)] text-[var(--demo-ink)]">
    <PremiumV3PageHero title={services.title} subtitle={services.subtitle} eyebrow="MENU" media={media[0] ?? premium.heroMedia[0]} recipe={data.designRecipe} variant="editorial-split" />
    <section className="px-5 py-24 sm:px-10 sm:py-32 lg:px-16 lg:py-40"><div className="mx-auto max-w-[1380px]"><PremiumV3Reveal motionStyle={motionStyle} className="grid gap-8 border-b border-[var(--demo-line)] pb-9 md:grid-cols-[.8fr_1.2fr] md:items-end"><div><p className="premium-hospitality-kicker">MENU / 01</p><h2 className={`${demoHeadlineClass(data.presentation?.servicesHeading ?? services.title, "section")} mt-6 max-w-2xl font-[var(--demo-heading-weight)] [font-family:var(--demo-font-display)]`}>{data.presentation?.servicesHeading ?? services.title}</h2></div><p className="max-w-xl text-sm leading-8 text-[var(--demo-muted)]">季節や仕入れによって内容が変わる場合があります。最新の提供状況は公式案内をご確認ください。</p></PremiumV3Reveal><PremiumV3Stagger className="mt-14 grid gap-6 md:grid-cols-2">{services.services.map((service, index) => <PremiumV3StaggerItem key={service.title} className={`premium-hospitality-menu-card group ${index === 0 ? "md:row-span-2" : ""}`}><div className={`relative overflow-hidden ${index === 0 ? "aspect-[4/5] md:h-full" : "aspect-[1.5/1]"}`}><PremiumV3Media media={media[index % Math.max(media.length, 1)] ?? media[0]} className="absolute inset-0" sizes={index === 0 ? "(max-width:768px) 100vw, 50vw" : "(max-width:768px) 100vw, 42vw"} /><div className="absolute inset-0 bg-gradient-to-t from-black/84 via-black/15 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-7 text-white sm:p-9"><p className="text-[10px] font-bold tracking-[.24em] text-white/58">MENU / {String(index + 1).padStart(2, "0")}</p><h3 className="mt-3 text-3xl [font-family:var(--demo-font-display)]">{service.title}</h3><p className="mt-4 max-w-lg text-sm leading-7 text-white/72">{service.description}</p><ul className="mt-5 border-t border-white/22 pt-4">{service.features.slice(0, 3).map((feature) => <li key={feature} className="flex items-start gap-2 py-1 text-xs leading-6 text-white/62"><Check className="mt-1 h-3.5 w-3.5 shrink-0" />{feature}</li>)}</ul></div></div></PremiumV3StaggerItem>)}</PremiumV3Stagger></div></section>
    {guidance.length > 0 && <section className="border-y border-[var(--demo-line)] bg-[var(--demo-surface-alt)] px-5 py-24 sm:px-10 sm:py-32 lg:px-16"><div className="mx-auto max-w-[1380px]"><PremiumV3Reveal motionStyle={motionStyle} className="grid gap-8 border-b border-[var(--demo-line)] pb-9 md:grid-cols-[1fr_.65fr] md:items-end"><div><p className="premium-hospitality-kicker">HOW TO ENJOY / 02</p><h2 className={`${demoHeadlineClass("選ぶ前に、知っておきたいこと。", "section")} mt-6 font-[var(--demo-heading-weight)] [font-family:var(--demo-font-display)]`}>選ぶ前に、<br />知っておきたいこと。</h2></div><p className="text-sm leading-8 text-[var(--demo-muted)]">メニューの違いだけでなく、店内で過ごす時間やご来店前の確認事項を整理しています。</p></PremiumV3Reveal><div className="divide-y divide-[var(--demo-line)]">{guidance.slice(0, 4).map((item, index) => <PremiumV3Reveal key={`${item.title}-${index}`} motionStyle={motionStyle} delay={index * .05} className="grid gap-5 py-8 md:grid-cols-[74px_.7fr_1.3fr] md:gap-8"><span className="text-xs text-[var(--demo-muted)]">0{index + 1}</span><div><p className="premium-hospitality-kicker">{item.eyebrow}</p><h3 className="mt-3 text-2xl [font-family:var(--demo-font-display)]">{item.title}</h3></div><div><p className="text-sm leading-8 text-[var(--demo-muted)]">{item.body}</p><ul className="mt-4 flex flex-wrap gap-x-5 gap-y-2">{item.points.slice(0, 3).map((point) => <li key={point} className="text-xs text-[var(--demo-muted)]">— {point}</li>)}</ul></div></PremiumV3Reveal>)}</div></div></section>}
    <section className="bg-[var(--demo-ink)] px-5 py-24 text-white sm:px-10 sm:py-32 lg:px-16"><div className="mx-auto max-w-[1380px]"><PremiumV3Reveal motionStyle={motionStyle} className="grid gap-8 border-b border-white/16 pb-9 md:grid-cols-[1fr_.65fr] md:items-end"><div><p className="premium-hospitality-kicker text-white/48">THE FLOW / 03</p><h2 className={`${demoHeadlineClass(services.processTitle ?? "店で過ごす時間。", "section")} mt-6 font-[var(--demo-heading-weight)] [font-family:var(--demo-font-display)]`}>{services.processTitle ?? "店で過ごす時間。"}</h2></div><p className="text-sm leading-8 text-white/58">{services.processEyebrow ?? "VISIT"}。ご来店前に、現在確認できる流れをご覧いただけます。</p></PremiumV3Reveal><div className="grid border-b border-white/16 md:grid-cols-2">{services.process.slice(0, 4).map((step, index) => <PremiumV3Reveal key={step.step} motionStyle={motionStyle} delay={index * .05} className="grid min-h-56 grid-cols-[64px_1fr] gap-4 border-b border-white/16 py-8 md:border-r md:px-8"><span className="text-xs text-white/35">0{index + 1}</span><div><h3 className="text-2xl [font-family:var(--demo-font-display)]">{step.title}</h3><p className="mt-4 text-sm leading-8 text-white/58">{step.description}</p></div></PremiumV3Reveal>)}</div></div></section>
    <section className="bg-[var(--demo-accent)] px-5 py-20 text-white sm:px-10 sm:py-24 lg:px-16"><PremiumV3Reveal motionStyle={motionStyle} className="mx-auto grid max-w-[1180px] gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="premium-hospitality-kicker text-white/58">READY WHEN YOU ARE</p><h2 className={`${demoHeadlineClass(services.ctaTitle ?? "次の食事を、ここから。", "section")} mt-5 font-[var(--demo-heading-weight)] [font-family:var(--demo-font-display)]`}>{services.ctaTitle ?? "次の食事を、ここから。"}</h2><p className="mt-5 max-w-2xl text-sm leading-8 text-white/74">{services.ctaSubtitle ?? "現在の営業情報とお問い合わせ方法をご確認ください。"}</p></div><a href={services.ctaHref ?? `/${data.slug}/contact`} className="inline-flex min-h-13 items-center justify-center gap-3 bg-white px-8 text-sm font-bold text-black">{services.ctaText ?? "アクセスを見る"}<MapPin className="h-4 w-4" /><ArrowUpRight className="h-4 w-4" /></a></PremiumV3Reveal></section>
  </div>
}

function uniqueMedia(media: DemoPremiumMedia[]) {
  const seen = new Set<string>()
  return media.filter((item) => {
    if (!item.src || seen.has(item.src)) return false
    seen.add(item.src)
    return true
  })
}
