import type { Metadata } from "next"
import Link from "next/link"
import { notFound } from "next/navigation"
import { PET_MOVIE_DELIVERY_BUSINESS_DAYS, PET_MOVIE_PLANS, PET_MOVIE_TERMS_VERSION } from "@/lib/pet-life-movie/commercial"

type Locale = "ja" | "en" | "es" | "pt"
const supported = (value: string): value is Locale => ["ja", "en", "es", "pt"].includes(value)

const copy = {
  ja: { title: "Pet Life Movie 提供条件", intro: "注文前に確認いただく、買い切り動画制作サービスの条件です。", headings: ["サービスと価格", "制作・納品", "素材とAI利用", "取消し・不具合", "保存と削除", "サポート"], bodies: [`Mini $19、Story $39、Cinema $79の一回払いです。定期課金と送料はありません。プランごとの尺・画角は注文前の料金表に表示します。`, `決済確認後${PET_MOVIE_DELIVERY_BUSINESS_DAYS}営業日以内に、private storageの完成動画を専用ページへ納品します。全作品でドラフト確認と最終品質確認を行います。`, "利用者は写真を使用・提供する権利を持つことを確認します。字幕は入力された事実だけを使い、音声複製や架空の思い出は作りません。本人らしさを保持できない生成処理は使用しません。", `制作開始後のお客様都合による取消しはできません。当社が${PET_MOVIE_DELIVERY_BUSINESS_DAYS}営業日以内に納品できない場合、または完成品に重大な不具合がある場合は、修正・再制作または返金を行います。不具合は納品後7日以内にご連絡ください。`, "無料プロジェクトは作成から30日、有料プロジェクトは決済から90日で削除対象になります。管理用リンクからいつでも写真・動画・関連データを即時削除できます。", "support@paradigmjp.comへご連絡ください。通常2営業日以内に返信します。"], back: "Pet Life Movieへ戻る", effective: "適用日" },
  en: { title: "Pet Life Movie Terms", intro: "Terms for this one-time custom film service, provided before ordering.", headings: ["Service and price", "Production and delivery", "Assets and AI", "Cancellation and defects", "Retention and deletion", "Support"], bodies: [`Mini is $19, Story is $39, and Cinema is $79, each as a one-time purchase. There is no subscription or shipping charge. Duration and aspect ratios are shown before ordering.`, `We deliver private files within ${PET_MOVIE_DELIVERY_BUSINESS_DAYS} business days after payment confirmation. Every film passes draft and final human quality review.`, "You confirm that you have the right to provide every photo. Captions use only supplied facts. We do not clone voices or invent memories, and we do not use generated motion that fails identity-preservation checks.", `Customer-requested cancellation is unavailable after production starts. If we do not deliver within ${PET_MOVIE_DELIVERY_BUSINESS_DAYS} business days or the deliverable has a material defect, we provide correction, re-production, or refund. Report defects within seven days of delivery.`, "Free projects are retained for 30 days and paid projects for 90 days after payment. The management link can permanently delete photos, films, and related data at any time.", "Contact support@paradigmjp.com. We normally respond within two business days."], back: "Back to Pet Life Movie", effective: "Effective" },
  es: { title: "Condiciones de Pet Life Movie", intro: "Condiciones del servicio de vídeo personalizado y pago único.", headings: ["Servicio y precio", "Producción y entrega", "Materiales e IA", "Cancelación y defectos", "Conservación y eliminación", "Soporte"], bodies: [`Mini cuesta $19, Story $39 y Cinema $79, con un único pago. No hay suscripción ni envío. La duración y los formatos se muestran antes de comprar.`, `Entregamos los archivos privados en ${PET_MOVIE_DELIVERY_BUSINESS_DAYS} días laborables tras confirmar el pago. Cada vídeo pasa revisión humana de borrador y final.`, "Confirmas que tienes derecho a proporcionar cada foto. Los textos solo usan hechos aportados. No clonamos voces ni inventamos recuerdos.", `No se admite cancelación una vez iniciada la producción. Si no entregamos en ${PET_MOVIE_DELIVERY_BUSINESS_DAYS} días laborables o existe un defecto importante, corregimos, rehacemos o reembolsamos. Comunica defectos en siete días.`, "Los proyectos gratuitos se conservan 30 días y los pagados 90. El enlace de gestión permite eliminar permanentemente todos los datos.", "Escribe a support@paradigmjp.com. Respondemos normalmente en dos días laborables."], back: "Volver a Pet Life Movie", effective: "Vigente desde" },
  pt: { title: "Termos do Pet Life Movie", intro: "Condições do serviço de filme personalizado com pagamento único.", headings: ["Serviço e preço", "Produção e entrega", "Materiais e IA", "Cancelamento e defeitos", "Retenção e exclusão", "Suporte"], bodies: [`Mini custa $19, Story $39 e Cinema $79, em pagamento único. Não há assinatura ou frete. Duração e formatos são mostrados antes da compra.`, `Entregamos os arquivos privados em até ${PET_MOVIE_DELIVERY_BUSINESS_DAYS} dias úteis após confirmar o pagamento. Todo filme passa por revisão humana de rascunho e final.`, "Você confirma ter direito de fornecer cada foto. As legendas usam apenas fatos informados. Não clonamos vozes nem inventamos memórias.", `Não há cancelamento após o início da produção. Se não entregarmos em ${PET_MOVIE_DELIVERY_BUSINESS_DAYS} dias úteis ou houver defeito relevante, corrigimos, refazemos ou reembolsamos. Informe defeitos em sete dias.`, "Projetos grátis são mantidos por 30 dias e pagos por 90. O link de gestão permite excluir permanentemente todos os dados.", "Escreva para support@paradigmjp.com. Normalmente respondemos em dois dias úteis."], back: "Voltar ao Pet Life Movie", effective: "Vigente desde" },
} as const

const paymentCopy = {
  ja: "支払方法・時期：Stripeで利用可能なクレジット／デビットカードにより、注文確定時に一回払いで決済します。",
  en: "Payment method and timing: one-time charge at order confirmation using a credit or debit card available through Stripe.",
  es: "Método y momento del pago: un único cargo al confirmar el pedido con una tarjeta de crédito o débito disponible en Stripe.",
  pt: "Método e momento do pagamento: cobrança única na confirmação do pedido com cartão de crédito ou débito disponível no Stripe.",
} as const

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params
  if (!supported(locale)) return { title: "Pet Life Movie Terms" }
  return { title: copy[locale].title, robots: { index: true, follow: true } }
}

export default async function PetMovieTermsPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params
  if (!supported(locale)) notFound()
  const t = copy[locale]
  return <main className="min-h-dvh bg-paradigm-paper px-5 pb-24 pt-32 text-paradigm-ink"><article className="mx-auto max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-paradigm-accent">Pet Life Movie · v{PET_MOVIE_TERMS_VERSION}</p><h1 className="mt-4 font-display text-5xl md:text-7xl">{t.title}</h1><p className="mt-6 text-lg leading-8 text-paradigm-ink-soft">{t.intro}</p><p className="mt-3 text-sm text-paradigm-ink-mute">{t.effective}: {PET_MOVIE_TERMS_VERSION}</p><p className="mt-6 rounded-2xl border border-paradigm-line bg-paradigm-paper-card p-5 text-sm leading-6">{paymentCopy[locale]}</p><div className="mt-12 space-y-9">{t.headings.map((heading, index) => <section key={heading}><h2 className="font-display text-2xl">{heading}</h2><p className="mt-3 leading-7 text-paradigm-ink-soft">{t.bodies[index]}</p></section>)}</div><div className="mt-12 flex flex-wrap gap-5 border-t border-paradigm-line pt-7 text-sm underline underline-offset-4"><Link href={`/${locale}/pet-life-movie`}>{t.back}</Link><Link href={`/${locale}/legal`}>Legal</Link><Link href={`/${locale}/privacy`}>Privacy</Link><Link href={`/${locale}/refund`}>Refunds</Link></div><p className="sr-only">{PET_MOVIE_PLANS.map((plan) => `${plan.name} ${plan.priceUsd} USD`).join(", ")}</p></article></main>
}
