/**
 * lib/sales/integration-defs-sources.ts
 * list_source + analysis カテゴリの統合定義
 */
import type { SalesIntegrationDefinition } from "./integration-registry-types"

export const SOURCE_DEFS: SalesIntegrationDefinition[] = [
  {
    slug: "google_places",
    displayName: "Google Places API",
    category: "list_source",
    deployment: "api",
    role: "店舗の位置情報、口コミ、評価、営業時間などを取得し、MEO（地図最適化）課題を診断するAPI。",
    requiredEnv: ["GOOGLE_PLACES_API_KEY"],
    optionalEnv: [],
    balance: "google_places_health",
    docsUrl: "https://developers.google.com/maps/documentation/places/web-service/reference/rest",
    recommended: true,
    notes: "Google Cloud請求/無料枠はCloud Consoleで監視する。取得データの保存範囲は規約に合わせる。",
  },
  {
    slug: "apollo",
    displayName: "Apollo.io",
    category: "list_source",
    deployment: "api",
    role: "グローバルなB2Bデータベースから、企業属性やターゲットの連絡先（メール・役職等）を収集するAPI。",
    requiredEnv: ["APOLLO_API_KEY"],
    optionalEnv: ["APOLLO_EXPORTER_TOKEN"],
    balance: "apollo_health",
    docsUrl: "https://docs.apollo.io/docs/api-overview",
    recommended: true,
    notes: "クレジット/レート制限はApollo Developer Portalで監視。CSV投入はSupabaseを入口にする。",
  },
  {
    slug: "fumadata",
    displayName: "Fumadata",
    category: "list_source",
    deployment: "api",
    role: "日本国内の企業データベースから、ターゲット企業の基本情報を収集するAPI。",
    requiredEnv: ["FUMADATA_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: true,
    notes: "日本市場の業界別リスト補強用。",
  },
  {
    slug: "bizmap",
    displayName: "BIZMap",
    category: "list_source",
    deployment: "api",
    role: "日本国内のSMB（中小企業）リストを補強し、業種や事業内容のデータを充実させるAPI。",
    requiredEnv: ["BIZMAP_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: false,
    notes: "Apollo/Fumadataで不足する国内SMB補完。",
  },
  {
    slug: "gbizinfo",
    displayName: "gBizInfo API",
    category: "list_source",
    deployment: "api",
    role: "経済産業省の公的データベースから、法人の登録情報、財務情報、許認可などの実績データを取得するAPI。",
    requiredEnv: [],
    optionalEnv: ["GBIZ_API_TOKEN"],
    balance: "gbizinfo_health",
    recommended: true,
    notes: "無料の公的情報を優先して企業カルテへ入れる。",
  },
  {
    slug: "houjin_bangou",
    displayName: "国税庁 法人番号API",
    category: "list_source",
    deployment: "api",
    role: "国税庁の公的データから、企業の正式名称や本店所在地、法人番号を取得して正規化するAPI。",
    requiredEnv: ["HOUJIN_BANGOU_API_ID"],
    optionalEnv: [],
    balance: "none",
    recommended: true,
    notes: "正式法人名・所在地の正規化に使う。",
  },
  {
    slug: "spiderfoot",
    displayName: "SpiderFoot",
    category: "list_source",
    deployment: "oss",
    role: "200以上のオープンソースモジュールで攻撃面・DNS・メール・SSLなど多面的なOSINT情報を収集する自動偵察ツール。",
    requiredEnv: [],
    optionalEnv: ["SPIDERFOOT_API_URL"],
    balance: "spiderfoot_health",
    docsUrl: "https://github.com/smicallef/spiderfoot",
    recommended: true,
    notes: "Docker経由で実行。診断レポートのOSINTセクションに統合。",
  },
  {
    slug: "katana",
    displayName: "Katana",
    category: "list_source",
    deployment: "oss",
    role: "対象サイトの全ページ・JS・APIエンドポイントを高速クロールし、隠れた問い合わせフォームや技術スタックを検出するクローラー。",
    requiredEnv: [],
    optionalEnv: [],
    balance: "katana_health",
    docsUrl: "https://github.com/projectdiscovery/katana",
    recommended: true,
    notes: "Docker経由で実行。診断レポートの技術検出・フォーム発見セクションに統合。",
  },
  {
    slug: "maigret",
    displayName: "Maigret",
    category: "list_source",
    deployment: "oss",
    role: "ユーザー名から3000以上のSNS・Webサービス上のアカウント有無を横断検索し、経営者のデジタルプレゼンスを調査するツール。",
    requiredEnv: [],
    optionalEnv: [],
    balance: "maigret_health",
    docsUrl: "https://github.com/soxoj/maigret",
    recommended: false,
    notes: "Docker経由で実行。競合分析・経営者SNSプレゼンス診断に使用。",
  },
  {
    slug: "apify",
    displayName: "Apify",
    category: "list_source",
    deployment: "api",
    role: "各種WebサイトやSNSから特定のデータセットを抽出・スクレイピングする汎用クラウドクローラーAPI。",
    requiredEnv: ["APIFY_API_TOKEN"],
    optionalEnv: [],
    balance: "manual",
    recommended: false,
    notes: "専用actorがある情報源だけに絞る。",
  },
  {
    slug: "outscraper",
    displayName: "Outscraper",
    category: "list_source",
    deployment: "api",
    role: "Googleマップなどの店舗情報やレビュー、SNSリンクを一括でスクレイピングしてリスト化するAPI。",
    requiredEnv: ["OUTSCRAPER_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: false,
    notes: "Places APIの補完候補。利用規約と保存範囲を確認して使う。",
  },
  {
    slug: "public_web_corpora",
    displayName: "Approved company directories / Zone files",
    category: "list_source",
    deployment: "api",
    role: "公的名簿・輸出事業者・業界団体・出展者名簿を主母集団にし、zone/domain feedは二次監査に限定する。",
    requiredEnv: [],
    optionalEnv: ["PASSIVE_DOMAIN_FEED_URLS", "CZDS_ZONE_FILE_URLS", "MASSDNS_BIN"],
    balance: "none",
    recommended: true,
    notes: "Search proxyと有料APIを使わず、取得元・検証根拠・国判定を保存する。",
  },
  {
    slug: "niche_list_sources",
    displayName: "WhoisDS / theHarvester / Events / Platform experts",
    category: "list_source",
    deployment: "api",
    role: "新規取得ドメイン、OSINTツール、展示会出展者、Shopify/Webflow開発パートナーディレクトリなどのニッチなリード情報源API群。",
    requiredEnv: [],
    optionalEnv: [
      "WHOISDS_NRD_URL", "THEHARVESTER_BIN", "THEHARVESTER_WORKER_URL",
      "EVENTSEYE_SEARCH_URL", "TENTIMES_SEARCH_URL",
      "SHOPIFY_EXPERTS_URL", "WEBFLOW_EXPERTS_URL",
    ],
    balance: "manual",
    recommended: true,
    notes: "Secondary lead sources feed Supabase batches only after dedupe and scoring.",
  },
  {
    slug: "morphic",
    displayName: "Morphic",
    category: "list_source",
    deployment: "oss",
    role: "AI搭載の次世代検索エンジン。自然言語クエリでWeb検索+生成AIによる回答を提供し、見込み客リサーチや競合調査に活用する。",
    requiredEnv: [],
    optionalEnv: ["MORPHIC_BASE_URL"],
    balance: "morphic_health",
    docsUrl: "https://github.com/miurla/morphic",
    recommended: false,
    notes: "MorphicのAI補完として使用。生成AI回答により従来の検索よりリッチな競合・市場情報を取得できる。",
  },
  {
    slug: "perplexica",
    displayName: "Perplexica",
    category: "list_source",
    deployment: "oss",
    role: "AI搭載のオープンソース検索エンジン。Perplexity.ai のセルフホスト代替として、プライバシーを保ったままAI検索+情報収集を行うツール。",
    requiredEnv: [],
    optionalEnv: ["PERPLEXICA_BASE_URL"],
    balance: "perplexica_health",
    docsUrl: "https://github.com/ItzCrazyKns/Perplexica",
    recommended: true,
    notes: "見込み客リサーチのAI検索レイヤーとしてMorphicと併用。プライバシー重視の自己ホスト型。",
  },
  {
    slug: "dataforseo",
    displayName: "DataForSEO",
    category: "analysis",
    deployment: "api",
    role: "対象ドメインのSEO評価、被リンク、検索順位、Lighthouseスコアなどの詳細データを取得するAPI。",
    requiredEnv: ["DATAFORSEO_LOGIN", "DATAFORSEO_PASSWORD"],
    optionalEnv: [],
    balance: "dataforseo_user_data",
    docsUrl: "https://docs.dataforseo.com/v3/appendix-user-data/",
    recommended: true,
    notes: "user_data APIで利用状況・支出・アカウント情報を確認できる。費用が乗る分析はsource_runsへ記録する。",
  },
  {
    slug: "similarweb",
    displayName: "Similarweb API",
    category: "analysis",
    deployment: "api",
    role: "Webサイトのアクセス数、訪問ユーザー属性、競合比較などのトラフィック推計データを取得するAPI。",
    requiredEnv: ["SIMILARWEB_API_KEY"],
    optionalEnv: [],
    balance: "similarweb_health",
    docsUrl: "https://developers.similarweb.com/docs",
    recommended: false,
    notes: "海外SMB向けの「日本進出しない機会損失」推定に強いが、費用が重くなりやすいのでDataForSEO/公的データの補助として使う。",
  },
  {
    slug: "jgrants",
    displayName: "jGrants API",
    category: "analysis",
    deployment: "api",
    role: "国の補助金（Jグランツ）データベースから、対象企業に提案可能な補助金・助成金の適合状況を判定するAPI。",
    requiredEnv: ["JGRANTS_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: true,
    notes: "補助金適合の提案材料にする。",
  },
  {
    slug: "wappalyzer_webanalyze",
    displayName: "Wappalyzer / webanalyze",
    category: "analysis",
    deployment: "oss",
    role: "ドメインからその企業が使用しているCMS、サーバー、決済、アナリティクスなどの技術スタックや使用SaaSを割り出すプログラム。",
    requiredEnv: [],
    optionalEnv: ["WAPPALYZER_API_KEY", "WAPPALYZER_CLI_BIN", "WEBANALYZE_BIN"],
    balance: "manual",
    docsUrl: "https://www.wappalyzer.com/technologies/",
    recommended: true,
    notes: "内蔵regexを強化済み。必要ならwebanalyze CLIをworker化して精度を上げる。",
  },
  {
    slug: "pagespeed",
    displayName: "PageSpeed Insights",
    category: "analysis",
    deployment: "api",
    role: "対象Webサイトの表示速度、Core Web Vitals、読み込みパフォーマンスの課題を測定するAPI。",
    requiredEnv: [],
    optionalEnv: ["GOOGLE_PSI_API_KEY"],
    balance: "pagespeed_health",
    recommended: true,
    notes: "APIキーなしでも低頻度なら動くが、大量診断ではキー必須。",
  },
  {
    slug: "urlscan",
    displayName: "urlscan.io",
    category: "analysis",
    deployment: "api",
    role: "Webサイトの読み込みリソース、安全な依存関係、リンク先セキュリティリスクをスキャンするAPI。",
    requiredEnv: ["URLSCAN_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: false,
    notes: "公開スキャンの扱いに注意。顧客候補サイトへ過剰アクセスしない。",
  },
  {
    slug: "publicwww",
    displayName: "PublicWWW",
    category: "analysis",
    deployment: "api",
    role: "WebサイトのHTMLソースコードから特定のスクリプトやトラッキングコードの埋め込みを検索するソースコード検索API。",
    requiredEnv: ["PUBLICWWW_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: false,
    notes: "タグ・埋め込み検出の補完。",
  },
  {
    slug: "ad_libraries",
    displayName: "Meta Ad Library / TikTok Commercial Content API",
    category: "analysis",
    deployment: "api",
    role: "Meta広告ライブラリ等のAPIから、競合の広告掲載本数や更新頻度を取得して動画提案の材料にするAPI。",
    requiredEnv: [],
    optionalEnv: ["META_AD_LIBRARY_ACCESS_TOKEN", "TIKTOK_CLIENT_KEY", "TIKTOK_CLIENT_SECRET"],
    balance: "manual",
    docsUrl: "https://developers.tiktok.com/doc/commercial-content-api-getting-started/",
    recommended: true,
    notes: "広告費や売上を断定せず、公開広告本数・クリエイティブ更新頻度・媒体依存度を根拠に動画納品サブスクの訴求へつなぐ。",
  },
  {
    slug: "security_apis",
    displayName: "SecurityTrails / Shodan / Censys / Observatory / SSL Labs",
    category: "analysis",
    deployment: "api",
    role: "SecurityTrails、Observatoryなどの外部APIから、DNS設定、ポート公開状況、SSL/TLS証明書の安全性を診断するAPI群。",
    requiredEnv: [],
    optionalEnv: ["SECURITYTRAILS_API_KEY", "SHODAN_API_KEY", "CENSYS_API_ID", "MOZILLA_OBSERVATORY_API_URL"],
    balance: "manual",
    recommended: true,
    notes: "無料枠・公的チェックを優先し、危険な能動スキャンは避ける。",
  },
  {
    slug: "mobsf",
    displayName: "Mobile Security Framework MobSF",
    category: "analysis",
    deployment: "oss",
    role: "見込み客がモバイルアプリを公開している場合に、静的・動的解析でアプリのセキュリティ脆弱性を診断するOSS環境。",
    requiredEnv: ["MOBSF_BASE_URL"],
    optionalEnv: ["MOBSF_API_KEY"],
    balance: "none",
    recommended: false,
    notes: "Web制作営業では対象外が多いので必要時だけ。",
  },
  {
    slug: "serp_tavily",
    displayName: "SerpAPI / Tavily",
    category: "analysis",
    deployment: "api",
    role: "検索エンジンの検索結果やTavilyのAI検索機能を用いて、企業の競合状況や市場動向を調査するAPI。",
    requiredEnv: [],
    optionalEnv: ["SERPAPI_API_KEY", "TAVILY_API_KEY"],
    balance: "manual",
    recommended: true,
    notes: "DataForSEOを主、Tavily/SerpAPIを補助にする。",
  },
  {
    slug: "rsshub_wayback",
    displayName: "RSSHub / Wayback Machine",
    category: "analysis",
    deployment: "oss",
    role: "Wayback Machineから企業のWebサイトの過去履歴や更新履歴、RSSHubから最新のプレスリリースや採用情報を取得するAPI群。",
    requiredEnv: [],
    optionalEnv: ["RSSHUB_BASE_URL"],
    balance: "manual",
    recommended: true,
    notes: "Wayback can be checked without secrets; RSSHub becomes ready when a self-hosted or public base URL is configured.",
  },
  {
    slug: "w3c_validator",
    displayName: "W3C HTML Validator",
    category: "analysis",
    deployment: "api",
    role: "HTML標準準拠チェックでマークアップ品質を診断し、アクセシビリティとSEOの基礎を評価します。",
    requiredEnv: [],
    optionalEnv: [],
    balance: "none",
    recommended: false,
    notes: "無料の公開API。レート制限あり（約100req/min）。",
  },
  {
    slug: "phishtank",
    displayName: "PhishTank",
    category: "analysis",
    deployment: "api",
    role: "ドメインがフィッシングデータベースに登録されていないか確認し、ブランド安全性を評価します。",
    requiredEnv: [],
    optionalEnv: [],
    balance: "none",
    recommended: false,
    notes: "無料の公開API。",
  },
  {
    slug: "green_web",
    displayName: "Green Web Foundation",
    category: "analysis",
    deployment: "api",
    role: "対象サイトがグリーンホスティングを使用しているか確認し、環境配慮のシグナルとして評価します。",
    requiredEnv: [],
    optionalEnv: [],
    balance: "none",
    recommended: false,
    notes: "無料の公開API。",
  },
  {
    slug: "smb_signals",
    displayName: "SMB Digital Signals",
    category: "analysis",
    deployment: "api",
    role: "中小企業のデジタルプレゼンス（SNS・Googleビジネス・リンク等）を収集し、営業優先度を判定します。",
    requiredEnv: [],
    optionalEnv: [],
    balance: "none",
    recommended: true,
    notes: "WappalyzerとDNSデータから自動計算。外部API不要。",
  },
  {
    slug: "market_data",
    displayName: "e-Stat Market Statistics",
    category: "analysis",
    deployment: "api",
    role: "業界別の市場規模・成長率などの統計データをe-Stat APIから取得し、提案の定量根拠とします。",
    requiredEnv: [],
    optionalEnv: [],
    balance: "none",
    recommended: true,
    notes: "無料の政府統計API。業界別データがハードコードフォールバックあり。",
  },
  {
    slug: "flowsint",
    displayName: "Flowsint",
    category: "list_source",
    deployment: "oss",
    role: "内部OSINT統合ツール。企業ドメインからDNS・WHOIS・SSL・ソーシャル等のデータを横断的に収集します。",
    requiredEnv: [],
    optionalEnv: ["FLOWSINT_API_URL", "FLOWSINT_API_TOKEN"],
    balance: "none",
    recommended: false,
    notes: "セルフホストのFlowsintインスタンスに接続。SpiderFootの補完として使用。",
  },
]
