/**
 * lib/sales/integration-definitions.ts — 統合レジストリの定義配列
 *
 * integration-registry.ts から分離 (C-1 対応)。
 * REGISTRY 定義を専用ファイルに集約。
 */

import { DIFY_RUNTIME_KEY_ENV_NAMES, DIFY_RUNTIME_URL_ENV_NAMES } from "./dify-cloud"
import type { SalesIntegrationDefinition } from "./integration-registry-types"

export const INTEGRATION_REGISTRY: SalesIntegrationDefinition[] = [
  {
    slug: "supabase_ssot",
    displayName: "Supabase SSOT",
    category: "crm_ops",
    deployment: "oss",
    role: "リード、診断レポート、ジョブ履歴、商談、契約書、監査ログを管理する中心データベース（SSOT）。",
    requiredEnv: [],
    requiredAnyEnv: ["SALES_SUPABASE_SERVICE_ROLE_KEY", "SUPABASE_SERVICE_ROLE_KEY"],
    optionalEnv: ["SALES_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_URL", "SUPABASE_PAT"],
    balance: "none",
    docsUrl: "https://github.com/supabase/supabase",
    recommended: true,
    notes: "営業データの正本です。service_role未設定時はSales OSをdegraded表示にし、偽成功で処理を進めません。",
  },
  {
    slug: "supabase_studio",
    displayName: "Supabase Studio",
    category: "crm_ops",
    deployment: "oss",
    role: "データベースのテーブル作成・データ確認をGUIで行う管理画面。",
    requiredEnv: ["NEXT_PUBLIC_SUPABASE_STUDIO_URL"],
    optionalEnv: [],
    balance: "supabase_studio_health",
    recommended: true,
    notes: "Allows direct row-level exploration and editing.",
  },
  {
    slug: "dify_cloud",
    displayName: "Dify Cloud",
    category: "orchestration",
    deployment: "cloud",
    role: "DeepSeek V4を連携し、企業診断、提案文作成、テンプレート選定、人間確認フローを行う中核ワークフロー。",
    requiredEnv: [],
    requiredAnyEnv: DIFY_RUNTIME_KEY_ENV_NAMES,
    optionalEnv: [...DIFY_RUNTIME_URL_ENV_NAMES],
    balance: "dify_health",
    docsUrl: "https://docs.dify.ai/api-reference/workflows/run-workflow",
    recommended: true,
    notes: "DifyはCloud版 api.dify.ai のみを正とする。用途別キーを認識し、APIキーの実値はUI・ログ・n8nペイロードへ出さない。",
  },
  {
    slug: "deepseek",
    displayName: "DeepSeek API",
    category: "orchestration",
    deployment: "api",
    role: "Difyワークフローが利用できない場合のフォールバック用LLMおよび構造化データ生成エンジン。",
    requiredEnv: ["DEEPSEEK_API_KEY"],
    optionalEnv: ["DEEPSEEK_BASE_URL"],
    balance: "manual",
    recommended: true,
    notes: "Dify Cloud内の推論モデルを優先し、直APIは補助・検証用に限定する。",
  },
  {
    slug: "n8n",
    displayName: "n8n OSS (legacy)",
    category: "orchestration",
    deployment: "oss",
    role: "（移行元レガシー）以前使用していたWebhook連携とアプローチ承認フローの実行エンジン。",
    requiredEnv: ["N8N_WEBHOOK_SECRET"],
    optionalEnv: ["N8N_BASE_URL", "N8N_SALES_ENRICHMENT_WEBHOOK_URL", "N8N_PLAYWRIGHT_FORM_WEBHOOK"],
    balance: "none",
    recommended: false,
    notes: "Trigger.devに移行済みの旧ワークフローシステムです。新規ジョブの実行には使用されません。",
  },
  {
    slug: "twenty_crm",
    displayName: "Twenty CRM",
    category: "crm_ops",
    deployment: "oss",
    role: "企業情報、商談ステージ、活動履歴、営業担当者を管理するCRM画面。",
    requiredEnv: ["TWENTY_BASE_URL"],
    optionalEnv: ["TWENTY_API_KEY", "TWENTY_DATABASE_URL"],
    balance: "manual",
    docsUrl: "https://github.com/twentyhq/twenty",
    recommended: true,
    notes: "Supabase SSOTの会社情報をCRM画面へ投影します。APIキーが無い場合は画面リンクのみ、メタデータ同期は無効です。",
  },
  {
    slug: "trigger_dev",
    displayName: "Trigger.dev",
    category: "orchestration",
    deployment: "cloud",
    role: "時間のかかるデータ収集ジョブ、動画・レポート生成、再試行制御を行うバックグラウンドジョブ実行エンジン。",
    requiredEnv: ["TRIGGER_SECRET_KEY"],
    optionalEnv: [
      "TRIGGER_API_URL",
      "TRIGGER_DASHBOARD_URL",
      "TRIGGER_SALES_OS_PIPELINE_TASK_ID",
      "TRIGGER_POST_OUTREACH_TASK_ID",
      "TRIGGER_CHATWOOT_REPLY_TASK_ID",
      "TRIGGER_LIVEKIT_DISCOVERY_TASK_ID",
    ],
    balance: "trigger_dev_health",
    recommended: true,
    notes: "営業OSの長時間ジョブ、再試行制御、webhook転送の主要なオーケストレーターです。",
  },
  {
    slug: "browserless",
    displayName: "Browserless",
    category: "outreach",
    deployment: "api",
    role: "SPAフォーム探索、送信前チェック、Webサイトの高解像度スクリーンショットを撮影するリモートブラウザ実行環境。",
    requiredEnv: ["BROWSERLESS_URL", "BROWSERLESS_TOKEN"],
    optionalEnv: [],
    balance: "browserless_pressure",
    docsUrl: "https://docs.browserless.io/enterprise/utility-functions/pressure",
    recommended: true,
    notes: "送信前にpressureを確認できる場合は、running/queuedを見て過負荷時に停止する。高解像度スクショ機能も提供。",
  },
  {
    slug: "stagehand",
    displayName: "Stagehand",
    category: "outreach",
    deployment: "oss",
    role: "PlaywrightとLLMを組み合わせ、多様な問い合わせフォームの入力欄を自律的に解釈して自動入力・送信するAIエージェント。",
    requiredEnv: ["STAGEHAND_URL", "STAGEHAND_API_KEY"],
    optionalEnv: [],
    balance: "stagehand_health",
    docsUrl: "https://github.com/browserbase/stagehand",
    recommended: true,
    notes: "Playwrightの裏でLLMを動かし、バラバラなフォーム構造を人間のように自律解釈して送信します。",
  },
  {
    slug: "crawlee",
    displayName: "Crawlee",
    category: "outreach",
    deployment: "oss",
    role: "Webサイトのリンク構造をクロールし、問い合わせページなどの宛先URLを特定する構造化クローラー。",
    requiredEnv: ["CRAWLEE_WORKER_URL"],
    optionalEnv: [],
    balance: "crawlee_health",
    docsUrl: "https://crawlee.dev/",
    recommended: true,
    notes: "Next.js本体では軽量fetch、重いクロールはworkerに逃がす。",
  },
  {
    slug: "searxng",
    displayName: "SearxNG",
    category: "list_source",
    deployment: "oss",
    role: "検索エンジン（Google/Bing等）を統合し、見込み客候補ドメインをキーワード検索で一括収集するセルフホスト検索API。",
    requiredEnv: ["SEARXNG_BASE_URL"],
    optionalEnv: ["SEARXNG_LANGUAGE", "SEARXNG_DEFAULT_ENGINES"],
    balance: "searxng_health",
    docsUrl: "https://github.com/searxng/searxng",
    recommended: true,
    notes: "JSON形式をsettings.ymlで有効化してから使います。検索結果はDBに保存し、重複排除とスコアリング後にリード化します。",
  },
  {
    slug: "crawl4ai",
    displayName: "Crawl4AI",
    category: "outreach",
    deployment: "oss",
    role: "Webページからレイアウトを保ったままテキストや問い合わせフォーム候補を抽出するAI向けクローラー。",
    requiredEnv: ["CRAWL4AI_BASE_URL"],
    optionalEnv: ["CRAWL4AI_API_KEY", "CRAWL4AI_FORM_DISCOVERY_PATH", "CRAWL4AI_HEALTH_PATH"],
    balance: "crawl4ai_health",
    recommended: true,
    notes: "HTML本文とフォーム候補の抽出を担当。送信は別ガードを通す。",
  },
  {
    slug: "playwright_stealth",
    displayName: "Playwright Stealth Worker",
    category: "outreach",
    deployment: "oss",
    role: "人間がチェックを通した後に、ステルスブラウザを使用して問い合わせフォームへの自動送信を実行するワーカー。",
    requiredEnv: ["OUTREACH_WORKER_URL"],
    optionalEnv: ["PLAYWRIGHT_STEALTH_ENABLED"],
    balance: "playwright_stealth_health",
    recommended: true,
    notes: "CAPTCHA/Cloudflare Challenge検出時は自動送信せず、人間キューへ切り替える。",
  },
  {
    slug: "camoufox",
    displayName: "Camoufox",
    category: "outreach",
    deployment: "oss",
    role: "ブラウザフィンガープリントを偽装し、手動レビューやQA時のアクセス制限を検証するための検証用ブラウザ環境。",
    requiredEnv: ["CAMOUFOX_WS_URL"],
    optionalEnv: [],
    balance: "none",
    recommended: false,
    notes: "回避目的ではなく、人間確認付きの再現・検証に限定する。",
  },
  {
    slug: "dataforseo",
    displayName: "DataForSEO",
    category: "analysis",
    deployment: "api",
    role: "対象ドメインのSEO評価、被リンク、検索順位、Lighthouseスコアなどの詳細データを取得するAPI。",
    requiredEnv: ["DATAFORSEO_LOGIN", "DATAFORSEO_PASSWORD"],
    optionalEnv: [],
    balance: "dataforseo_user_data",
    docsUrl: "https://docs.dataforseo.com/v3/appendix-user-data/",
    recommended: true,
    notes: "user_data APIで利用状況・支出・アカウント情報を確認できる。費用が乗る分析はsource_runsへ記録する。",
  },
  {
    slug: "similarweb",
    displayName: "Similarweb API",
    category: "analysis",
    deployment: "api",
    role: "Webサイトのアクセス数、訪問ユーザー属性、競合比較などのトラフィック推計データを取得するAPI。",
    requiredEnv: ["SIMILARWEB_API_KEY"],
    optionalEnv: [],
    balance: "similarweb_health",
    docsUrl: "https://developers.similarweb.com/docs",
    recommended: false,
    notes: "海外SMB向けの「日本進出しない機会損失」推定に強いが、費用が重くなりやすいのでDataForSEO/公的データの補助として使う。",
  },
  {
    slug: "google_places",
    displayName: "Google Places API",
    category: "list_source",
    deployment: "api",
    role: "店舗の位置情報、口コミ、評価、営業時間などを取得し、MEO（地図最適化）課題を診断するAPI。",
    requiredEnv: ["GOOGLE_PLACES_API_KEY"],
    optionalEnv: [],
    balance: "google_places_health",
    docsUrl: "https://developers.google.com/maps/documentation/places/web-service/reference/rest",
    recommended: true,
    notes: "Google Cloud請求/無料枠はCloud Consoleで監視する。取得データの保存範囲は規約に合わせる。",
  },
  {
    slug: "apollo",
    displayName: "Apollo.io",
    category: "list_source",
    deployment: "api",
    role: "グローバルなB2Bデータベースから、企業属性やターゲットの連絡先（メール・役職等）を収集するAPI。",
    requiredEnv: ["APOLLO_API_KEY"],
    optionalEnv: ["APOLLO_EXPORTER_TOKEN"],
    balance: "apollo_health",
    docsUrl: "https://docs.apollo.io/docs/api-overview",
    recommended: true,
    notes: "クレジット/レート制限はApollo Developer Portalで監視。CSV投入はSupabaseを入口にする。",
  },
  {
    slug: "fumadata",
    displayName: "Fumadata",
    category: "list_source",
    deployment: "api",
    role: "日本国内の企業データベースから、ターゲット企業の基本情報を収集するAPI。",
    requiredEnv: ["FUMADATA_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: true,
    notes: "日本市場の業界別リスト補強用。",
  },
  {
    slug: "bizmap",
    displayName: "BIZMap",
    category: "list_source",
    deployment: "api",
    role: "日本国内のSMB（中小企業）リストを補強し、業種や事業内容のデータを充実させるAPI。",
    requiredEnv: ["BIZMAP_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: false,
    notes: "Apollo/Fumadataで不足する国内SMB補完。",
  },
  {
    slug: "gbizinfo",
    displayName: "gBizInfo API",
    category: "list_source",
    deployment: "api",
    role: "経済産業省の公的データベースから、法人の登録情報、財務情報、許認可などの実績データを取得するAPI。",
    requiredEnv: [],
    optionalEnv: ["GBIZINFO_API_KEY"],
    balance: "gbizinfo_health",
    recommended: true,
    notes: "無料の公的情報を優先して企業カルテへ入れる。",
  },
  {
    slug: "houjin_bangou",
    displayName: "国税庁 法人番号API",
    category: "list_source",
    deployment: "api",
    role: "国税庁の公的データから、企業の正式名称や本店所在地、法人番号を取得して正規化するAPI。",
    requiredEnv: ["HOUJIN_BANGOU_API_ID"],
    optionalEnv: [],
    balance: "none",
    recommended: true,
    notes: "正式法人名・所在地の正規化に使う。",
  },
  {
    slug: "spiderfoot",
    displayName: "SpiderFoot",
    category: "list_source",
    deployment: "oss",
    role: "200以上のオープンソースモジュールで攻撃面・DNS・メール・SSLなど多面的なOSINT情報を収集する自動偵察ツール。",
    requiredEnv: [],
    optionalEnv: ["SPIDERFOOT_API_URL"],
    balance: "spiderfoot_health",
    docsUrl: "https://github.com/smicallef/spiderfoot",
    recommended: true,
    notes: "Docker経由で実行。診断レポートのOSINTセクションに統合。",
  },
  {
    slug: "katana",
    displayName: "Katana",
    category: "list_source",
    deployment: "oss",
    role: "対象サイトの全ページ・JS・APIエンドポイントを高速クロールし、隠れた問い合わせフォームや技術スタックを検出するクローラー。",
    requiredEnv: [],
    optionalEnv: [],
    balance: "katana_health",
    docsUrl: "https://github.com/projectdiscovery/katana",
    recommended: true,
    notes: "Docker経由で実行。診断レポートの技術検出・フォーム発見セクションに統合。",
  },
  {
    slug: "maigret",
    displayName: "Maigret",
    category: "list_source",
    deployment: "oss",
    role: "ユーザー名から3000以上のSNS・Webサービス上のアカウント有無を横断検索し、経営者のデジタルプレゼンスを調査するツール。",
    requiredEnv: [],
    optionalEnv: [],
    balance: "maigret_health",
    docsUrl: "https://github.com/soxoj/maigret",
    recommended: false,
    notes: "Docker経由で実行。競合分析・経営者SNSプレゼンス診断に使用。",
  },
  {
    slug: "flaresolverr",
    displayName: "FlareSolverr",
    category: "proxy",
    deployment: "oss",
    role: "CloudflareやDDoS-GUARDなどのWAFブロックをバイパスし、ブロックされたサイトへのHTTPリクエストを中継するプロキシ。",
    requiredEnv: [],
    optionalEnv: ["FLARESOLVERR_API_URL"],
    balance: "flaresolverr_health",
    docsUrl: "https://github.com/FlareSolverr/FlareSolverr",
    recommended: true,
    notes: "診断レポートのWAF検出バイパスに使用。CAPTCHA回避は行わず、Cloudflare Challengeの突破に限定。",
  },
  {
    slug: "jgrants",
    displayName: "jGrants API",
    category: "analysis",
    deployment: "api",
    role: "国の補助金（Jグランツ）データベースから、対象企業に提案可能な補助金・助成金の適合状況を判定するAPI。",
    requiredEnv: ["JGRANTS_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: true,
    notes: "補助金適合の提案材料にする。",
  },
  {
    slug: "apify",
    displayName: "Apify",
    category: "list_source",
    deployment: "api",
    role: "各種WebサイトやSNSから特定のデータセットを抽出・スクレイピングする汎用クラウドクローラーAPI。",
    requiredEnv: ["APIFY_API_TOKEN"],
    optionalEnv: [],
    balance: "manual",
    recommended: false,
    notes: "専用actorがある情報源だけに絞る。",
  },
  {
    slug: "outscraper",
    displayName: "Outscraper",
    category: "list_source",
    deployment: "api",
    role: "Googleマップなどの店舗情報やレビュー、SNSリンクを一括でスクレイピングしてリスト化するAPI。",
    requiredEnv: ["OUTSCRAPER_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: false,
    notes: "Places APIの補完候補。利用規約と保存範囲を確認して使う。",
  },
  {
    slug: "wappalyzer_webanalyze",
    displayName: "Wappalyzer / webanalyze",
    category: "analysis",
    deployment: "oss",
    role: "ドメインからその企業が使用しているCMS、サーバー、決済、アナリティクスなどの技術スタックや使用SaaSを割り出すプログラム。",
    requiredEnv: [],
    optionalEnv: ["WAPPALYZER_API_KEY", "WAPPALYZER_CLI_BIN", "WEBANALYZE_BIN"],
    balance: "manual",
    docsUrl: "https://www.wappalyzer.com/technologies/",
    recommended: true,
    notes: "内蔵regexを強化済み。必要ならwebanalyze CLIをworker化して精度を上げる。",
  },
  {
    slug: "pagespeed",
    displayName: "PageSpeed Insights",
    category: "analysis",
    deployment: "api",
    role: "対象Webサイトの表示速度、Core Web Vitals、読み込みパフォーマンスの課題を測定するAPI。",
    requiredEnv: [],
    optionalEnv: ["GOOGLE_PSI_API_KEY"],
    balance: "pagespeed_health",
    recommended: true,
    notes: "APIキーなしでも低頻度なら動くが、大量診断ではキー必須。",
  },
  {
    slug: "urlscan",
    displayName: "urlscan.io",
    category: "analysis",
    deployment: "api",
    role: "Webサイトの読み込みリソース、安全な依存関係、リンク先セキュリティリスクをスキャンするAPI。",
    requiredEnv: ["URLSCAN_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: false,
    notes: "公開スキャンの扱いに注意。顧客候補サイトへ過剰アクセスしない。",
  },
  {
    slug: "publicwww",
    displayName: "PublicWWW",
    category: "analysis",
    deployment: "api",
    role: "WebサイトのHTMLソースコードから特定のスクリプトやトラッキングコードの埋め込みを検索するソースコード検索API。",
    requiredEnv: ["PUBLICWWW_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: false,
    notes: "タグ・埋め込み検出の補完。",
  },
  {
    slug: "ad_libraries",
    displayName: "Meta Ad Library / TikTok Commercial Content API",
    category: "analysis",
    deployment: "api",
    role: "Meta広告ライブラリ等のAPIから、競合の広告掲載本数や更新頻度を取得して動画提案の材料にするAPI。",
    requiredEnv: [],
    optionalEnv: ["META_AD_LIBRARY_ACCESS_TOKEN", "TIKTOK_CLIENT_KEY", "TIKTOK_CLIENT_SECRET"],
    balance: "manual",
    docsUrl: "https://developers.tiktok.com/doc/commercial-content-api-getting-started",
    recommended: true,
    notes: "広告費や売上を断定せず、公開広告本数・クリエイティブ更新頻度・媒体依存度を根拠に動画納品サブスクの訴求へつなぐ。",
  },
  {
    slug: "security_apis",
    displayName: "SecurityTrails / Shodan / Censys / Observatory / SSL Labs",
    category: "analysis",
    deployment: "api",
    role: "SecurityTrails、Observatoryなどの外部APIから、DNS設定、ポート公開状況、SSL/TLS証明書の安全性を診断するAPI群。",
    requiredEnv: [],
    optionalEnv: ["SECURITYTRAILS_API_KEY", "SHODAN_API_KEY", "CENSYS_API_ID", "MOZILLA_OBSERVATORY_API_URL"],
    balance: "manual",
    recommended: true,
    notes: "無料枠・公的チェックを優先し、危険な能動スキャンは避ける。",
  },
  {
    slug: "mobsf",
    displayName: "Mobile Security Framework MobSF",
    category: "analysis",
    deployment: "oss",
    role: "見込み客がモバイルアプリを公開している場合に、静的・動的解析でアプリのセキュリティ脆弱性を診断するOSS環境。",
    requiredEnv: ["MOBSF_BASE_URL"],
    optionalEnv: ["MOBSF_API_KEY"],
    balance: "none",
    recommended: false,
    notes: "Web制作営業では対象外が多いので必要時だけ。",
  },
  {
    slug: "slidev_gotenberg",
    displayName: "Slidev / Gotenberg",
    category: "asset_generation",
    deployment: "oss",
    role: "HTML/Markdownからスライド形式の営業提案資料やPDFレポートを生成するGotenberg/Slidev連携エンジン。",
    requiredEnv: ["GOTENBERG_URL"],
    optionalEnv: ["SLIDEV_RENDER_URL"],
    balance: "slidev_gotenberg_health",
    recommended: true,
    notes: "Difyが構成案を生成し、Slidev/GotenbergでPDF化する。",
  },
  {
    slug: "directus_assets",
    displayName: "Directus",
    category: "asset_generation",
    deployment: "oss",
    role: "営業活動で使用する画像、PDF、スライド素材、および診断結果のメッセージパーツを管理するヘッドレスCMS。",
    requiredEnv: ["DIRECTUS_BASE_URL", "DIRECTUS_TOKEN"],
    optionalEnv: ["NEXT_PUBLIC_DIRECTUS_URL", "DIRECTUS_SALES_ASSETS_COLLECTION"],
    balance: "directus_health",
    docsUrl: "https://github.com/directus/directus",
    recommended: true,
    notes: "未接続時はRevenue OS内の資料スタジオにフォールバックします。外部Directusが404でも営業導線は止めません。",
  },
  {
    slug: "nextjs_reports",
    displayName: "Next.js report renderer",
    category: "asset_generation",
    deployment: "oss",
    role: "顧客ごとにパーソナライズされた診断レポートや動画視聴ページを動的にWeb描画するフロントエンドサーバー。",
    requiredEnv: ["NEXT_PUBLIC_SITE_URL"],
    optionalEnv: ["PARADIGMJP_BASE_URL"],
    balance: "none",
    docsUrl: "https://github.com/vercel/next.js",
    recommended: true,
    notes: "診断レポートはNext.jsの/[locale]/report/[slug]で描画します。顧客URLを生成するためNEXT_PUBLIC_SITE_URLは必須です。",
  },
  {
    slug: "serp_tavily",
    displayName: "SerpAPI / Tavily",
    category: "analysis",
    deployment: "api",
    role: "検索エンジンの検索結果やTavilyのAI検索機能を用いて、企業の競合状況や市場動向を調査するAPI。",
    requiredEnv: [],
    optionalEnv: ["SERPAPI_API_KEY", "TAVILY_API_KEY"],
    balance: "manual",
    recommended: true,
    notes: "DataForSEOを主、Tavily/SerpAPIを補助にする。",
  },
  {
    slug: "video_stack",
    displayName: "OpenMontage / ComfyUI / HyperFrames / Remotion",
    category: "video",
    deployment: "oss",
    role: "提案用パーソナライズ動画および納品用自動動画を生成する動画レンダリングエンジン群。",
    requiredEnv: [],
    optionalEnv: [
      "OPENMONTAGE_API_URL", "OPENMONTAGE_BASE_URL", "NEXT_PUBLIC_OPENMONTAGE_STUDIO_URL",
      "COMFYUI_API_URL", "REMOTION_RENDER_URL",
      "HYPERFRAMES_API_URL", "HYPERFRAMES_RENDERER_URL", "HYPERFRAMES_API_KEY",
    ],
    balance: "manual",
    recommended: true,
    notes: "Overview only. Production readiness is judged by the dedicated OpenMontage, HyperFrames, ComfyUI, and R2 runtime gates below.",
  },
  {
    slug: "openmontage_runtime",
    displayName: "OpenMontage",
    category: "video",
    deployment: "oss",
    role: "自動動画生成ジョブのスケジューリング、リソース管理、および動画スタジオURLを提供するオーケストレーター。",
    requiredEnv: ["OPENMONTAGE_API_URL", "OPENMONTAGE_API_KEY", "NEXT_PUBLIC_OPENMONTAGE_STUDIO_URL"],
    optionalEnv: ["OPENMONTAGE_BASE_URL", "OPENMONTAGE_STUDIO_HOST"],
    balance: "openmontage_health",
    docsUrl: "/docs/knowledge/revenue-os-production-service-setup.md",
    recommended: true,
    notes: "URLだけではreadyにしません。API URL、API key、Studio URL、health endpointの疎通を要求します。公開公式OSSとしては未確認のため、社内互換APIとして扱います。",
  },
  {
    slug: "hyperframes_renderer",
    displayName: "HyperFrames",
    category: "video",
    deployment: "oss",
    role: "HTMLの動きを動画（MP4等）に高速レンダリングしてパーソナライズ動画を作成するエンジン。",
    requiredEnv: ["HYPERFRAMES_API_KEY"],
    requiredAnyEnv: ["HYPERFRAMES_RENDERER_URL", "HYPERFRAMES_API_URL"],
    optionalEnv: [],
    balance: "hyperframes_health",
    docsUrl: "https://github.com/heygen-com/hyperframes",
    recommended: true,
    notes: "HyperFramesはURLだけではreadyにしません。renderer/API URLのいずれか、HYPERFRAMES_API_KEY、health endpoint疎通を要求します。",
  },
  {
    slug: "comfyui_api",
    displayName: "ComfyUI API",
    category: "video",
    deployment: "oss",
    role: "生成AIモデルをワークフロー化し、動画・スライド用の画像、アバター、BロールなどのアセットをGPU生成するAPI環境。",
    requiredEnv: ["COMFYUI_API_KEY"],
    requiredAnyEnv: ["COMFYUI_API_URL", "COMFYUI_BASE_URL"],
    optionalEnv: ["VAST_API_KEY", "RUNPOD_API_KEY"],
    balance: "comfyui_health",
    docsUrl: "https://github.com/comfyanonymous/ComfyUI",
    recommended: true,
    notes: "Public ComfyUI endpoints must not be unauthenticated. Revenue OS requires COMFYUI_API_KEY and /system_stats reachability before queueing jobs.",
  },
  {
    slug: "vast_api",
    displayName: "Vast.ai API",
    category: "video",
    deployment: "api",
    role: "ComfyUI等のAI動画生成ジョブが高負荷になった際に、クラウド上にオンデマンドでGPUインスタンスを立ち上げるAPI。",
    requiredEnv: ["VAST_API_KEY"],
    optionalEnv: [],
    balance: "vast_health",
    recommended: true,
    notes: "Allocates remote GPU power when on-premise hardware is saturated.",
  },
  {
    slug: "ffmpeg",
    displayName: "FFmpeg",
    category: "video",
    deployment: "local",
    role: "動画ファイルの切り出し、結合、音声合成、エンコード、圧縮処理を行うローカルの動画処理ツール。",
    requiredEnv: ["FFMPEG_BIN"],
    optionalEnv: [],
    balance: "ffmpeg_health",
    recommended: true,
    notes: "Required for base level video trimming and compression.",
  },
  {
    slug: "ffcreator",
    displayName: "FFCreator",
    category: "video",
    deployment: "oss",
    role: "Node.js上で高速にアニメーションや動画合成を行うための軽量動画生成ワーカープログラム。",
    requiredEnv: ["FFCREATOR_WORKER_URL"],
    optionalEnv: [],
    balance: "ffcreator_health",
    recommended: true,
    notes: "Alternative Node-based worker for video generation.",
  },
  {
    slug: "video_media_sources",
    displayName: "Pexels / ElevenLabs / Faster Whisper",
    category: "video",
    deployment: "api",
    role: "Pexelsのフリー動画素材、ElevenLabsのAIナレーション、Faster Whisperの音声文字起こしなど、動画素材と音声を供給するAPI群。",
    requiredEnv: [],
    optionalEnv: ["PEXELS_API_KEY", "ELEVENLABS_API_KEY", "FASTER_WHISPER_URL"],
    balance: "manual",
    docsUrl: "https://www.pexels.com/api/documentation/",
    recommended: true,
    notes: "OpenMontage/HyperFrames/Remotionの素材供給と音声・字幕生成に使う。著作権リスクを避けるため、商用利用可能な素材だけを許可する。",
  },
  {
    slug: "r2_delivery",
    displayName: "Cloudflare R2",
    category: "video",
    deployment: "api",
    role: "生成された動画、PDFレポート、デモサイトのコードアセットなどを高速かつ低コストで配信・保存するCloudflare R2ストレージAPI。",
    requiredEnv: [
      "CLOUDFLARE_R2_ACCOUNT_ID",
      "CLOUDFLARE_R2_ACCESS_KEY_ID",
      "CLOUDFLARE_R2_SECRET_ACCESS_KEY",
    ],
    requiredAnyEnv: ["CLOUDFLARE_R2_BUCKET", "R2_BUCKET"],
    optionalEnv: ["CLOUDFLARE_R2_PUBLIC_BASE_URL", "R2_PUBLIC_BASE_URL"],
    balance: "r2_health",
    recommended: true,
    notes: "bucket名だけではreadyにしません。account/access/secret、bucket、public base URL、HeadBucket疎通を要求します。",
  },
  {
    slug: "keystatic_demo_cms",
    displayName: "Keystatic",
    category: "demo_site",
    deployment: "oss",
    role: "Astroで構築したデモサイト内のコンテンツや設定を、非エンジニアがGit経由で編集できる管理UI（Keystatic）。",
    requiredEnv: ["KEYSTATIC_BASE_URL"],
    optionalEnv: [
      "NEXT_PUBLIC_KEYSTATIC_URL", "KEYSTATIC_SYNC_WEBHOOK_URL",
      "KEYSTATIC_SYNC_WEBHOOK_SECRET", "ASTRO_DEMO_WORKER_URL", "ASTRO_DEMO_WORKER_TOKEN",
    ],
    balance: "keystatic_health",
    docsUrl: "https://github.com/Thinkmill/keystatic",
    recommended: true,
    notes: "未接続時はRevenue OS内のデモサイトテンプレート管理を使います。Git反映は別途Keystatic/Astro側のデプロイが必要です。",
  },
  {
    slug: "astro_demo",
    displayName: "Astro",
    category: "demo_site",
    deployment: "oss",
    role: "提案先の企業に「改善後のWebサイト」のプレビューを高速提供するための、Astro製デモサイト生成・配信テンプレート。",
    requiredEnv: [],
    optionalEnv: ["ASTRO_DEMO_FACTORY_URL"],
    balance: "astro_health",
    recommended: true,
    notes: "テンプレートは言語・業界・訴求別に分け、Difyが選択する。",
  },
  {
    slug: "hermes_slack",
    displayName: "Hermes Agent / Slack",
    category: "orchestration",
    deployment: "oss",
    role: "自動送信前にオペレーターの承認を求める通知や、エラー・問い合わせ時のSlack通知をルーティングする連携モジュール。",
    requiredEnv: [],
    optionalEnv: ["HERMES_AGENT_WEBHOOK_URL", "SLACK_WEBHOOK_URL", "SLACK_BOT_TOKEN"],
    balance: "manual",
    recommended: true,
    notes: "Keeps autonomous jobs behind approval gates and records the human escalation surface.",
  },
  {
    slug: "notion_mcp",
    displayName: "Notion MCP",
    category: "orchestration",
    deployment: "api",
    role: "顧客用の共有スペース、議事録、および社内の引継ぎナレッジを同期するためのNotion連携API。",
    requiredEnv: [],
    optionalEnv: ["NOTION_API_KEY", "NOTION_MCP_TOKEN"],
    balance: "manual",
    recommended: false,
    notes: "Supabase remains the Sales OS SSOT; Notion is only a customer-facing or knowledge-capture surface.",
  },
  {
    slug: "supabase_mcp_nocodb",
    displayName: "Supabase MCP / NocoDB",
    category: "crm_ops",
    deployment: "oss",
    role: "Supabaseのデータベースを、スプレッドシートのような操作画面で一括編集できるようにするNocoDBの連携設定。",
    requiredEnv: [],
    optionalEnv: ["SUPABASE_ACCESS_TOKEN", "NOCODB_BASE_URL"],
    balance: "manual",
    recommended: true,
    notes: "NocoDB is an operating face over the Supabase SSOT, not a second source of truth.",
  },
  {
    slug: "chrome_mcp",
    displayName: "Chrome MCP",
    category: "orchestration",
    deployment: "local",
    role: "開発者やオペレーター側で、診断レポートやデモサイトの表示崩れ、フォーム動作のテストをローカルブラウザで行う検証用API。",
    requiredEnv: [],
    optionalEnv: ["CHROME_MCP_URL"],
    balance: "manual",
    recommended: false,
    notes: "Used for verification and QA; production automation should remain on Browserless/Stagehand workers.",
  },
  {
    slug: "rsshub_wayback",
    displayName: "RSSHub / Wayback Machine",
    category: "analysis",
    deployment: "oss",
    role: "Wayback Machineから企業のWebサイトの過去履歴や更新履歴、RSSHubから最新のプレスリリースや採用情報を取得するAPI群。",
    requiredEnv: [],
    optionalEnv: ["RSSHUB_BASE_URL"],
    balance: "manual",
    recommended: true,
    notes: "Wayback can be checked without secrets; RSSHub becomes ready when a self-hosted or public base URL is configured.",
  },
  {
    slug: "public_web_corpora",
    displayName: "Common Crawl / Tranco / HTTP Archive",
    category: "list_source",
    deployment: "api",
    role: "Common CrawlやTrancoなどの公開ビッグデータを用いて、企業のWebランキングやトラフィック規模を判定するAPI。",
    requiredEnv: [],
    optionalEnv: ["HTTPARCHIVE_BIGQUERY_PROJECT_ID"],
    balance: "none",
    recommended: true,
    notes: "Public datasets support sourcing and benchmarking without paid API dependency.",
  },
  {
    slug: "niche_list_sources",
    displayName: "WhoisDS / theHarvester / Events / Platform experts",
    category: "list_source",
    deployment: "api",
    role: "新規取得ドメイン、OSINTツール、展示会出展者、Shopify/Webflow開発パートナーディレクトリなどのニッチなリード情報源API群。",
    requiredEnv: [],
    optionalEnv: [
      "WHOISDS_NRD_URL", "THEHARVESTER_BIN", "THEHARVESTER_WORKER_URL",
      "EVENTSEYE_SEARCH_URL", "TENTIMES_SEARCH_URL",
      "SHOPIFY_EXPERTS_URL", "WEBFLOW_EXPERTS_URL",
    ],
    balance: "manual",
    recommended: true,
    notes: "Secondary lead sources feed Supabase batches only after dedupe and scoring.",
  },
  {
    slug: "proposal_renderer_stack",
    displayName: "Slidev / Gotenberg / Marp / Recharts",
    category: "asset_generation",
    deployment: "oss",
    role: "Slidev、Gotenberg、Marpなどの、スライド形式資料作成、グラフ描画、PDF変換を行う営業資料レンダリングツール群。",
    requiredEnv: [],
    optionalEnv: ["GOTENBERG_URL", "SLIDEV_RENDER_URL", "MARP_RENDER_URL", "RECHARTS_ENABLED"],
    balance: "manual",
    recommended: true,
    notes: "Gotenberg is the PDF conversion lane; Slidev, Marp, and Recharts are generation/rendering surfaces.",
  },
  {
    slug: "demo_builder_stack",
    displayName: "Astro / v0 / shadcn UI",
    category: "demo_site",
    deployment: "oss",
    role: "Astro、v0 by Vercel、shadcn UIなどの、提案用デモサイトおよびコンポーネントを高速構築するデザインシステムとフレームワーク群。",
    requiredEnv: [],
    optionalEnv: ["ASTRO_DEMO_WORKER_URL", "ASTRO_DEMO_FACTORY_URL", "V0_API_KEY", "V0_WORKER_URL", "SHADCN_BLOCKS_REGISTRY_URL"],
    balance: "manual",
    recommended: true,
    notes: "shadcn UI is a code/design dependency and does not require a runtime secret.",
  },
  {
    slug: "scrapoxy",
    displayName: "Scrapoxy",
    category: "proxy",
    deployment: "oss",
    role: "自動データ収集やブラウザ実行時のIPアドレス制限を回避するための、プロキシ分散管理OSS。",
    requiredEnv: [],
    optionalEnv: ["SCRAPOXY_API_URL", "SCRAPOXY_PROXY_URL", "SCRAPOXY_API_KEY"],
    balance: "manual",
    docsUrl: "https://github.com/fabienvauchelles/scrapoxy",
    recommended: false,
    notes: "mubeng remains the primary listed proxy rotator; Scrapoxy is tracked as an optional proxy-manager surface.",
  },
  {
    slug: "email_marketing_stack",
    displayName: "Listmonk / Mautic",
    category: "outreach",
    deployment: "oss",
    role: "ListmonkやMauticなどの、診断レポート配信後のステップメール、メルマガ、およびフォローアップメール配信エンジン。",
    requiredEnv: [],
    optionalEnv: ["LISTMONK_BASE_URL", "LISTMONK_API_KEY", "MAUTIC_BASE_URL", "MAUTIC_API_KEY"],
    balance: "manual",
    recommended: true,
    notes: "Separate campaign/newsletter automation from direct sales replies and CRM activity.",
  },
  {
    slug: "twenty_cms_alias",
    displayName: "TwentyCMS / Twenty CRM",
    category: "crm_ops",
    deployment: "oss",
    role: "CRM（Twenty）に関連する追加の設定や、別名連携を行うためのエイリアス管理。",
    requiredEnv: [],
    optionalEnv: ["TWENTY_BASE_URL", "TWENTY_CMS_BASE_URL"],
    balance: "manual",
    recommended: false,
    notes: "The production CRM source is Twenty OSS; TwentyCMS is tracked as an alias until a distinct CMS service is provisioned.",
  },
  {
    slug: "email_phone_stack",
    displayName: "Zoho / Smartlead / Resend / Listmonk / Twilio / HeyReach",
    category: "outreach",
    deployment: "api",
    role: "Zoho Mail、Smartlead、Twilioなどを経由し、フォーム送信が適さない場合のメールアプローチやSMS/電話、LinkedInなどの連絡経路群。",
    requiredEnv: [],
    optionalEnv: [
      "ZOHO_MAIL_CLIENT_ID", "SMARTLEAD_API_KEY", "RESEND_API_KEY", "LISTMONK_BASE_URL",
      "TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "IVRY_API_KEY", "HEYREACH_API_KEY", "DOCSEND_API_KEY",
    ],
    balance: "manual",
    recommended: true,
    notes: "フォーム自動送信が危険な場合の代替。ドメインウォームアップと上限監視が必須。",
  },
  {
    slug: "calcom",
    displayName: "Cal.com",
    category: "crm_ops",
    deployment: "oss",
    role: "診断レポートの閲覧後に、相手がコンサルティング商談の予約（Cal.com）を直ちに行えるカレンダー調整機能。",
    requiredEnv: ["CALCOM_BASE_URL"],
    optionalEnv: ["CALCOM_API_KEY", "CALCOM_WEBHOOK_URL"],
    balance: "calcom_health",
    recommended: true,
    notes: "成約時はDocuseal signed webhookから顧客ハンドオフを起動する。",
  },
  {
    slug: "chatwoot",
    displayName: "Chatwoot",
    category: "crm_ops",
    deployment: "oss",
    role: "アプローチ送信後の相手からの返信（メール、SNS、チャットなど）を1つのタイムラインで管理し、AI返信下書きを作成する共通インボックス。",
    requiredEnv: ["CHATWOOT_BASE_URL", "CHATWOOT_API_KEY", "CHATWOOT_ACCOUNT_ID"],
    optionalEnv: ["CHATWOOT_WEBHOOK_URL", "TRIGGER_CHATWOOT_REPLY_TASK_ID", "TRIGGER_POST_OUTREACH_TASK_ID"],
    balance: "chatwoot_health",
    docsUrl: "https://github.com/chatwoot/chatwoot",
    recommended: true,
    notes: "Webhookは/api/sales/chatwoot/webhookで受け、返信を活動ログとフォローアップキューに戻します。Trigger.dev設定時はAI返信導線へ転送します。",
  },
  {
    slug: "livekit",
    displayName: "LiveKit",
    category: "crm_ops",
    deployment: "oss",
    role: "商談やヒアリング時の音声・ビデオ通話を処理し、リアルタイムでのAIアシスタント動作や文字起こし・要約を行うシステム。",
    requiredEnv: ["LIVEKIT_URL", "LIVEKIT_API_KEY", "LIVEKIT_API_SECRET"],
    optionalEnv: ["LIVEKIT_WEBHOOK_URL", "TRIGGER_LIVEKIT_DISCOVERY_TASK_ID", "TRIGGER_POST_OUTREACH_TASK_ID"],
    balance: "livekit_health",
    docsUrl: "https://github.com/livekit/livekit",
    recommended: true,
    notes: "Webhookは/api/sales/livekit/webhookで受け、初期ヒアリングの記録を活動ログと商談準備キューに戻します。Trigger.dev設定時はAI返信導線へ転送します。",
  },
  {
    slug: "docuseal",
    displayName: "Docuseal",
    category: "crm_ops",
    deployment: "oss",
    role: "商談後に、契約書の作成・電子署名をオンラインで完結させ、自動で顧客ハンドオフへ進める電子契約署名システム。",
    requiredEnv: [],
    optionalEnv: ["DOCUSEAL_BASE_URL", "DOCUSEAL_API_KEY", "DOCUSEAL_WEBHOOK_URL"],
    balance: "none",
    recommended: true,
    notes: "署名Webhookは/api/sales/docuseal/webhookで受け、sales_contractsと顧客ハンドオフへ反映します。",
  },
  {
    slug: "proxy_pool",
    displayName: "DataImpulse / IPRoyal Proxy",
    category: "proxy",
    deployment: "api",
    role: "クローラーやブラウザが接続ブロックされるのを防ぐため、IPアドレスを適切にローテーションさせるプロキシ接続プールAPI。",
    requiredEnv: [],
    optionalEnv: ["DATAIMPULSE_PROXY_URL", "DATAIMPULSE_API_KEY", "IPROYAL_PROXY_URL", "IPROYAL_API_KEY"],
    balance: "manual",
    recommended: true,
    notes: "残量は各プロバイダ管理画面/APIで確認。CAPTCHAやCloudflare Challengeは回避せず人間確認に切り替える。",
  },
  {
    slug: "mubeng",
    displayName: "mubeng",
    category: "proxy",
    deployment: "oss",
    role: "セルフホストで動作し、SearxNGやCrawl4AI等のすべての外向き通信に対してプロキシの稼働チェックとローテーションを行うプロキシサーバー。",
    requiredEnv: ["MUBENG_PROXY_URL"],
    optionalEnv: ["MUBENG_PROXY_USERNAME", "MUBENG_PROXY_PASSWORD"],
    balance: "mubeng_health",
    docsUrl: "https://github.com/mubeng/mubeng",
    recommended: true,
    notes: "mubengをローカルまたはセルフホストの回転プロキシとして起動し、SearxNG/Crawl4AI/Browserless系の外向き通信を同じ防衛線へ通します。CAPTCHA回避ではなく、負荷分散とIP保護のために使います。",
  },
  {
    slug: "morphic",
    displayName: "Morphic",
    category: "list_source",
    deployment: "oss",
    role: "AI搭載の次世代検索エンジン。自然言語クエリでWeb検索+生成AIによる回答を提供し、見込み客リサーチや競合調査に活用する。",
    requiredEnv: [],
    optionalEnv: ["MORPHIC_BASE_URL"],
    balance: "morphic_health",
    docsUrl: "https://github.com/miurla/morphic",
    recommended: false,
    notes: "SearXNGのAI補完として使用。生成AI回答により従来の検索よりリッチな競合・市場情報を取得できる。",
  },
  {
    slug: "perplexica",
    displayName: "Perplexica",
    category: "list_source",
    deployment: "oss",
    role: "AI搭載のオープンソース検索エンジン。Perplexity.ai のセルフホスト代替として、プライバシーを保ったままAI検索+情報収集を行うツール。",
    requiredEnv: [],
    optionalEnv: ["PERPLEXICA_BASE_URL"],
    balance: "perplexica_health",
    docsUrl: "https://github.com/ItzCrazyKns/Perplexica",
    recommended: true,
    notes: "見込み客リサーチのAI検索レイヤーとしてSearXNG+Morphicと併用。プライバシー重視の自己ホスト型。",
  },
  {
    slug: "skyvern",
    displayName: "Skyvern",
    category: "outreach",
    deployment: "oss",
    role: "ブラウザ自動化フレームワーク。AIエージェントがWebサイトを操作し、フォーム入力・データ抽出・ワークフロー自動化を実行する。",
    requiredEnv: [],
    optionalEnv: ["SKYVERN_BASE_URL", "SKYVERN_API_KEY"],
    balance: "skyvern_health",
    docsUrl: "https://github.com/Skyvern-AI/skyvern",
    recommended: false,
    notes: "Stagehand/Browserlessと併用し、複雑なマルチステップWeb操作をAIエージェントが自律実行。CAPTCHA検出時は人間確認キューへ。",
  },
]
