/**
 * lib/sales/integration-definitions.ts — 統合レジストリの定義配列
 *
 * integration-registry.ts から分離 (C-1 対応)。
 * REGISTRY 定義を専用ファイルに集約。
 */

import { DIFY_RUNTIME_KEY_ENV_NAMES, DIFY_RUNTIME_URL_ENV_NAMES } from "./dify-cloud"
import type { SalesIntegrationDefinition } from "./integration-registry-types"

export const INTEGRATION_REGISTRY: SalesIntegrationDefinition[] = [
  {
    slug: "supabase_ssot",
    displayName: "Supabase SSOT",
    category: "crm_ops",
    deployment: "oss",
    role: "Single source of truth for leads, reports, jobs, meetings, contracts, and audit logs.",
    requiredEnv: [],
    requiredAnyEnv: ["SALES_SUPABASE_SERVICE_ROLE_KEY", "SUPABASE_SERVICE_ROLE_KEY"],
    optionalEnv: ["SALES_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_URL", "SUPABASE_PAT"],
    balance: "none",
    docsUrl: "https://github.com/supabase/supabase",
    recommended: true,
    notes: "営業データの正本です。service_role未設定時はSales OSをdegraded表示にし、偽成功で処理を進めません。",
  },
  {
    slug: "supabase_studio",
    displayName: "Supabase Studio",
    category: "crm_ops",
    deployment: "oss",
    role: "Database management GUI for Supabase SSOT.",
    requiredEnv: ["NEXT_PUBLIC_SUPABASE_STUDIO_URL"],
    optionalEnv: [],
    balance: "supabase_studio_health",
    recommended: true,
    notes: "Allows direct row-level exploration and editing.",
  },
  {
    slug: "dify_cloud",
    displayName: "Dify Cloud",
    category: "orchestration",
    deployment: "cloud",
    role: "DeepSeek V4 workflow for diagnosis, message generation, template selection, and human-review routing.",
    requiredEnv: [],
    requiredAnyEnv: DIFY_RUNTIME_KEY_ENV_NAMES,
    optionalEnv: [...DIFY_RUNTIME_URL_ENV_NAMES],
    balance: "dify_health",
    docsUrl: "https://docs.dify.ai/api-reference/workflows/run-workflow",
    recommended: true,
    notes: "DifyはCloud版 api.dify.ai のみを正とする。用途別キーを認識し、APIキーの実値はUI・ログ・n8nペイロードへ出さない。",
  },
  {
    slug: "deepseek",
    displayName: "DeepSeek API",
    category: "orchestration",
    deployment: "api",
    role: "LLM fallback and JSON generation when Dify workflow is unavailable.",
    requiredEnv: ["DEEPSEEK_API_KEY"],
    optionalEnv: ["DEEPSEEK_BASE_URL"],
    balance: "manual",
    recommended: true,
    notes: "Dify Cloud内の推論モデルを優先し、直APIは補助・検証用に限定する。",
  },
  {
    slug: "n8n",
    displayName: "n8n OSS",
    category: "orchestration",
    deployment: "oss",
    role: "Webhook orchestration for enrichment, outreach dry-run, approvals, and notifications.",
    requiredEnv: ["N8N_WEBHOOK_SECRET"],
    optionalEnv: ["N8N_BASE_URL", "N8N_SALES_ENRICHMENT_WEBHOOK_URL", "N8N_PLAYWRIGHT_FORM_WEBHOOK"],
    balance: "n8n_health",
    recommended: true,
    notes: "大量実行はn8n側の同時実行数とSales OS側のbatch limitで抑制する。",
  },
  {
    slug: "twenty_crm",
    displayName: "Twenty CRM",
    category: "crm_ops",
    deployment: "oss",
    role: "CRM surface for companies, deal stages, activities, and sales ownership.",
    requiredEnv: ["TWENTY_BASE_URL"],
    optionalEnv: ["TWENTY_API_KEY", "TWENTY_DATABASE_URL"],
    balance: "manual",
    docsUrl: "https://github.com/twentyhq/twenty",
    recommended: true,
    notes: "Supabase SSOTの会社情報をCRM画面へ投影します。APIキーが無い場合は画面リンクのみ、メタデータ同期は無効です。",
  },
  {
    slug: "trigger_dev",
    displayName: "Trigger.dev",
    category: "orchestration",
    deployment: "cloud",
    role: "Durable background jobs for long-running enrichment and asset generation.",
    requiredEnv: ["TRIGGER_DEV_API_KEY"],
    optionalEnv: ["TRIGGER_DEV_SALES_ENRICHMENT_WEBHOOK_URL"],
    balance: "manual",
    recommended: false,
    notes: "n8nで足りない長時間ジョブや再試行制御に使う候補。",
  },
  {
    slug: "browserless",
    displayName: "Browserless",
    category: "outreach",
    deployment: "api",
    role: "Remote browser runtime for SPA form discovery, preflight checks, and target website screenshots.",
    requiredEnv: ["BROWSERLESS_URL", "BROWSERLESS_TOKEN"],
    optionalEnv: [],
    balance: "browserless_pressure",
    docsUrl: "https://docs.browserless.io/enterprise/utility-functions/pressure",
    recommended: true,
    notes: "送信前にpressureを確認できる場合は、running/queuedを見て過負荷時に停止する。高解像度スクショ機能も提供。",
  },
  {
    slug: "stagehand",
    displayName: "Stagehand",
    category: "outreach",
    deployment: "oss",
    role: "AI-driven web agent for autonomous and robust contact form submission using LLMs.",
    requiredEnv: ["STAGEHAND_URL", "STAGEHAND_API_KEY"],
    optionalEnv: [],
    balance: "stagehand_health",
    docsUrl: "https://github.com/browserbase/stagehand",
    recommended: true,
    notes: "Playwrightの裏でLLMを動かし、バラバラなフォーム構造を人間のように自律解釈して送信します。",
  },
  {
    slug: "crawlee",
    displayName: "Crawlee",
    category: "outreach",
    deployment: "oss",
    role: "Structured crawling and contact path discovery.",
    requiredEnv: ["CRAWLEE_WORKER_URL"],
    optionalEnv: [],
    balance: "crawlee_health",
    docsUrl: "https://crawlee.dev/",
    recommended: true,
    notes: "Next.js本体では軽量fetch、重いクロールはworkerに逃がす。",
  },
  {
    slug: "searxng",
    displayName: "SearxNG",
    category: "list_source",
    deployment: "oss",
    role: "Self-hosted SERP water source for search-result lead discovery and monthly lead batches.",
    requiredEnv: ["SEARXNG_BASE_URL"],
    optionalEnv: ["SEARXNG_LANGUAGE", "SEARXNG_DEFAULT_ENGINES"],
    balance: "none",
    docsUrl: "https://github.com/searxng/searxng",
    recommended: true,
    notes: "JSON形式をsettings.ymlで有効化してから使います。検索結果はDBに保存し、重複排除とスコアリング後にリード化します。",
  },
  {
    slug: "crawl4ai",
    displayName: "Crawl4AI",
    category: "outreach",
    deployment: "oss",
    role: "AI-ready crawling and content extraction for company karte evidence.",
    requiredEnv: ["CRAWL4AI_BASE_URL"],
    optionalEnv: ["CRAWL4AI_API_KEY", "CRAWL4AI_FORM_DISCOVERY_PATH", "CRAWL4AI_HEALTH_PATH"],
    balance: "crawl4ai_health",
    recommended: true,
    notes: "HTML本文とフォーム候補の抽出を担当。送信は別ガードを通す。",
  },
  {
    slug: "playwright_stealth",
    displayName: "Playwright Stealth Worker",
    category: "outreach",
    deployment: "oss",
    role: "Approved form automation worker after CAPTCHA/anti-bot gates pass.",
    requiredEnv: ["OUTREACH_WORKER_URL"],
    optionalEnv: ["PLAYWRIGHT_STEALTH_ENABLED"],
    balance: "playwright_stealth_health",
    recommended: true,
    notes: "CAPTCHA/Cloudflare Challenge検出時は自動送信せず、人間キューへ切り替える。",
  },
  {
    slug: "camoufox",
    displayName: "Camoufox",
    category: "outreach",
    deployment: "oss",
    role: "Fingerprint-hardened browser option for manual review and QA, not blind bypass.",
    requiredEnv: ["CAMOUFOX_WS_URL"],
    optionalEnv: [],
    balance: "none",
    recommended: false,
    notes: "回避目的ではなく、人間確認付きの再現・検証に限定する。",
  },
  {
    slug: "dataforseo",
    displayName: "DataForSEO",
    category: "analysis",
    deployment: "api",
    role: "SEO, SERP, OnPage, Lighthouse, keyword and business-data enrichment.",
    requiredEnv: ["DATAFORSEO_LOGIN", "DATAFORSEO_PASSWORD"],
    optionalEnv: [],
    balance: "dataforseo_user_data",
    docsUrl: "https://docs.dataforseo.com/v3/appendix-user-data/",
    recommended: true,
    notes: "user_data APIで利用状況・支出・アカウント情報を確認できる。費用が乗る分析はsource_runsへ記録する。",
  },
  {
    slug: "similarweb",
    displayName: "Similarweb API",
    category: "analysis",
    deployment: "api",
    role: "Traffic, engagement, geography and competitor-market evidence for opportunity-loss estimates.",
    requiredEnv: ["SIMILARWEB_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    docsUrl: "https://developers.similarweb.com/docs",
    recommended: false,
    notes: "海外SMB向けの「日本進出しない機会損失」推定に強いが、費用が重くなりやすいのでDataForSEO/公的データの補助として使う。",
  },
  {
    slug: "google_places",
    displayName: "Google Places API",
    category: "list_source",
    deployment: "api",
    role: "Local presence, address, rating, categories, and MEO signals.",
    requiredEnv: ["GOOGLE_PLACES_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    docsUrl: "https://developers.google.com/maps/documentation/places/web-service/reference/rest",
    recommended: true,
    notes: "Google Cloud請求/無料枠はCloud Consoleで監視する。取得データの保存範囲は規約に合わせる。",
  },
  {
    slug: "apollo",
    displayName: "Apollo.io",
    category: "list_source",
    deployment: "api",
    role: "B2B account/contact enrichment and exported lead lists.",
    requiredEnv: ["APOLLO_API_KEY"],
    optionalEnv: ["APOLLO_EXPORTER_TOKEN"],
    balance: "manual",
    docsUrl: "https://docs.apollo.io/docs/api-overview",
    recommended: true,
    notes: "クレジット/レート制限はApollo Developer Portalで監視。CSV投入はSupabaseを入口にする。",
  },
  {
    slug: "fumadata",
    displayName: "Fumadata",
    category: "list_source",
    deployment: "api",
    role: "Japan SMB lead collection.",
    requiredEnv: ["FUMADATA_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: true,
    notes: "日本市場の業界別リスト補強用。",
  },
  {
    slug: "bizmap",
    displayName: "BIZMap",
    category: "list_source",
    deployment: "api",
    role: "Japan company list enrichment.",
    requiredEnv: ["BIZMAP_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: false,
    notes: "Apollo/Fumadataで不足する国内SMB補完。",
  },
  {
    slug: "gbizinfo",
    displayName: "gBizInfo API",
    category: "list_source",
    deployment: "api",
    role: "Official Japanese company facts and corporate registry evidence.",
    requiredEnv: [],
    optionalEnv: ["GBIZINFO_API_KEY"],
    balance: "none",
    recommended: true,
    notes: "無料の公的情報を優先して企業カルテへ入れる。",
  },
  {
    slug: "houjin_bangou",
    displayName: "国税庁 法人番号API",
    category: "list_source",
    deployment: "api",
    role: "Corporate number and legal entity verification.",
    requiredEnv: ["HOUJIN_BANGOU_API_ID"],
    optionalEnv: [],
    balance: "none",
    recommended: true,
    notes: "正式法人名・所在地の正規化に使う。",
  },
  {
    slug: "jgrants",
    displayName: "jGrants API",
    category: "analysis",
    deployment: "api",
    role: "Subsidy and grant-fit evidence for DX/Web proposals.",
    requiredEnv: ["JGRANTS_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: true,
    notes: "補助金適合の提案材料にする。",
  },
  {
    slug: "apify",
    displayName: "Apify",
    category: "list_source",
    deployment: "api",
    role: "Actor-based scraping and dataset enrichment.",
    requiredEnv: ["APIFY_API_TOKEN"],
    optionalEnv: [],
    balance: "manual",
    recommended: false,
    notes: "専用actorがある情報源だけに絞る。",
  },
  {
    slug: "outscraper",
    displayName: "Outscraper",
    category: "list_source",
    deployment: "api",
    role: "Google Maps/local business enrichment alternative.",
    requiredEnv: ["OUTSCRAPER_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: false,
    notes: "Places APIの補完候補。利用規約と保存範囲を確認して使う。",
  },
  {
    slug: "wappalyzer_webanalyze",
    displayName: "Wappalyzer / webanalyze",
    category: "analysis",
    deployment: "oss",
    role: "Technology fingerprinting from HTML, scripts, headers, cookies and public markers.",
    requiredEnv: [],
    optionalEnv: ["WAPPALYZER_API_KEY", "WAPPALYZER_CLI_BIN", "WEBANALYZE_BIN"],
    balance: "manual",
    docsUrl: "https://www.wappalyzer.com/technologies/",
    recommended: true,
    notes: "内蔵regexを強化済み。必要ならwebanalyze CLIをworker化して精度を上げる。",
  },
  {
    slug: "pagespeed",
    displayName: "PageSpeed Insights",
    category: "analysis",
    deployment: "api",
    role: "Performance and Core Web Vitals evidence.",
    requiredEnv: [],
    optionalEnv: ["GOOGLE_PSI_API_KEY"],
    balance: "manual",
    recommended: true,
    notes: "APIキーなしでも低頻度なら動くが、大量診断ではキー必須。",
  },
  {
    slug: "urlscan",
    displayName: "urlscan.io",
    category: "analysis",
    deployment: "api",
    role: "Security/resource evidence and suspicious dependency checks.",
    requiredEnv: ["URLSCAN_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: false,
    notes: "公開スキャンの扱いに注意。顧客候補サイトへ過剰アクセスしない。",
  },
  {
    slug: "publicwww",
    displayName: "PublicWWW",
    category: "analysis",
    deployment: "api",
    role: "Script, tag and footprint search.",
    requiredEnv: ["PUBLICWWW_API_KEY"],
    optionalEnv: [],
    balance: "manual",
    recommended: false,
    notes: "タグ・埋め込み検出の補完。",
  },
  {
    slug: "ad_libraries",
    displayName: "Meta Ad Library / TikTok Commercial Content API",
    category: "analysis",
    deployment: "api",
    role: "Competitor creative volume, active ads and fatigue signals for video-subscription proposals.",
    requiredEnv: [],
    optionalEnv: ["META_AD_LIBRARY_ACCESS_TOKEN", "TIKTOK_CLIENT_KEY", "TIKTOK_CLIENT_SECRET"],
    balance: "manual",
    docsUrl: "https://developers.tiktok.com/doc/commercial-content-api-getting-started",
    recommended: true,
    notes: "広告費や売上を断定せず、公開広告本数・クリエイティブ更新頻度・媒体依存度を根拠に動画納品サブスクの訴求へつなぐ。",
  },
  {
    slug: "security_apis",
    displayName: "SecurityTrails / Shodan / Censys / Observatory / SSL Labs",
    category: "analysis",
    deployment: "api",
    role: "DNS, exposure, TLS and security posture evidence.",
    requiredEnv: [],
    optionalEnv: ["SECURITYTRAILS_API_KEY", "SHODAN_API_KEY", "CENSYS_API_ID", "MOZILLA_OBSERVATORY_API_URL"],
    balance: "manual",
    recommended: true,
    notes: "無料枠・公的チェックを優先し、危険な能動スキャンは避ける。",
  },
  {
    slug: "mobsf",
    displayName: "Mobile Security Framework MobSF",
    category: "analysis",
    deployment: "oss",
    role: "Mobile-app security checks when the prospect has apps.",
    requiredEnv: ["MOBSF_BASE_URL"],
    optionalEnv: ["MOBSF_API_KEY"],
    balance: "none",
    recommended: false,
    notes: "Web制作営業では対象外が多いので必要時だけ。",
  },
  {
    slug: "slidev_gotenberg",
    displayName: "Slidev / Gotenberg",
    category: "asset_generation",
    deployment: "oss",
    role: "Proposal deck and PDF generation.",
    requiredEnv: ["GOTENBERG_URL"],
    optionalEnv: ["SLIDEV_RENDER_URL"],
    balance: "slidev_gotenberg_health",
    recommended: true,
    notes: "Difyが構成案を生成し、Slidev/GotenbergでPDF化する。",
  },
  {
    slug: "directus_assets",
    displayName: "Directus",
    category: "asset_generation",
    deployment: "oss",
    role: "Asset, proposal, and slide content management studio when a dedicated Directus instance is deployed.",
    requiredEnv: ["DIRECTUS_BASE_URL", "DIRECTUS_TOKEN"],
    optionalEnv: ["NEXT_PUBLIC_DIRECTUS_URL", "DIRECTUS_SALES_ASSETS_COLLECTION"],
    balance: "directus_health",
    docsUrl: "https://github.com/directus/directus",
    recommended: true,
    notes: "未接続時はRevenue OS内の資料スタジオにフォールバックします。外部Directusが404でも営業導線は止めません。",
  },
  {
    slug: "nextjs_reports",
    displayName: "Next.js report renderer",
    category: "asset_generation",
    deployment: "oss",
    role: "Dynamic SSR rendering for customer diagnostic reports by locale and slug.",
    requiredEnv: ["NEXT_PUBLIC_SITE_URL"],
    optionalEnv: ["PARADIGMJP_BASE_URL"],
    balance: "none",
    docsUrl: "https://github.com/vercel/next.js",
    recommended: true,
    notes: "診断レポートはNext.jsの/[locale]/report/[slug]で描画します。顧客URLを生成するためNEXT_PUBLIC_SITE_URLは必須です。",
  },
  {
    slug: "serp_tavily",
    displayName: "SerpAPI / Tavily",
    category: "analysis",
    deployment: "api",
    role: "Search result, competitor and market context evidence.",
    requiredEnv: [],
    optionalEnv: ["SERPAPI_API_KEY", "TAVILY_API_KEY"],
    balance: "manual",
    recommended: true,
    notes: "DataForSEOを主、Tavily/SerpAPIを補助にする。",
  },
  {
    slug: "video_stack",
    displayName: "OpenMontage / ComfyUI / HyperFrames / Remotion",
    category: "video",
    deployment: "oss",
    role: "Sales video and delivery-subscription video generation.",
    requiredEnv: [],
    optionalEnv: [
      "OPENMONTAGE_API_URL", "OPENMONTAGE_BASE_URL", "NEXT_PUBLIC_OPENMONTAGE_STUDIO_URL",
      "COMFYUI_API_URL", "REMOTION_RENDER_URL",
      "HYPERFRAMES_API_URL", "HYPERFRAMES_RENDERER_URL", "HYPERFRAMES_API_KEY",
    ],
    balance: "manual",
    recommended: true,
    notes: "Overview only. Production readiness is judged by the dedicated OpenMontage, HyperFrames, ComfyUI, and R2 runtime gates below.",
  },
  {
    slug: "openmontage_runtime",
    displayName: "OpenMontage",
    category: "video",
    deployment: "oss",
    role: "Authenticated orchestration API and studio URL for video-production jobs.",
    requiredEnv: ["OPENMONTAGE_API_URL", "OPENMONTAGE_API_KEY", "NEXT_PUBLIC_OPENMONTAGE_STUDIO_URL"],
    optionalEnv: ["OPENMONTAGE_BASE_URL", "OPENMONTAGE_STUDIO_HOST"],
    balance: "openmontage_health",
    docsUrl: "/docs/knowledge/revenue-os-production-service-setup.md",
    recommended: true,
    notes: "URLだけではreadyにしません。API URL、API key、Studio URL、health endpointの疎通を要求します。公開公式OSSとしては未確認のため、社内互換APIとして扱います。",
  },
  {
    slug: "hyperframes_renderer",
    displayName: "HyperFrames",
    category: "video",
    deployment: "oss",
    role: "Authenticated HTML-to-video renderer for sales video assets and delivery-subscription outputs.",
    requiredEnv: ["HYPERFRAMES_API_KEY"],
    requiredAnyEnv: ["HYPERFRAMES_RENDERER_URL", "HYPERFRAMES_API_URL"],
    optionalEnv: [],
    balance: "hyperframes_health",
    docsUrl: "https://github.com/heygen-com/hyperframes",
    recommended: true,
    notes: "HyperFramesはURLだけではreadyにしません。renderer/API URLのいずれか、HYPERFRAMES_API_KEY、health endpoint疎通を要求します。",
  },
  {
    slug: "comfyui_api",
    displayName: "ComfyUI API",
    category: "video",
    deployment: "oss",
    role: "Authenticated GPU asset-generation API for backgrounds, avatars, thumbnails, b-roll, and video source assets.",
    requiredEnv: ["COMFYUI_API_KEY"],
    requiredAnyEnv: ["COMFYUI_API_URL", "COMFYUI_BASE_URL"],
    optionalEnv: ["VAST_API_KEY", "RUNPOD_API_KEY"],
    balance: "comfyui_health",
    docsUrl: "https://github.com/comfyanonymous/ComfyUI",
    recommended: true,
    notes: "Public ComfyUI endpoints must not be unauthenticated. Revenue OS requires COMFYUI_API_KEY and /system_stats reachability before queueing jobs.",
  },
  {
    slug: "vast_api",
    displayName: "Vast.ai API",
    category: "video",
    deployment: "api",
    role: "On-demand GPU instances for video and asset generation.",
    requiredEnv: ["VAST_API_KEY"],
    optionalEnv: [],
    balance: "vast_health",
    recommended: true,
    notes: "Allocates remote GPU power when on-premise hardware is saturated.",
  },
  {
    slug: "ffmpeg",
    displayName: "FFmpeg",
    category: "video",
    deployment: "local",
    role: "Local or binary video manipulation tool.",
    requiredEnv: ["FFMPEG_BIN"],
    optionalEnv: [],
    balance: "ffmpeg_health",
    recommended: true,
    notes: "Required for base level video trimming and compression.",
  },
  {
    slug: "ffcreator",
    displayName: "FFCreator",
    category: "video",
    deployment: "oss",
    role: "Video pipeline and animation worker.",
    requiredEnv: ["FFCREATOR_WORKER_URL"],
    optionalEnv: [],
    balance: "ffcreator_health",
    recommended: true,
    notes: "Alternative Node-based worker for video generation.",
  },
  {
    slug: "video_media_sources",
    displayName: "Pexels / ElevenLabs / Faster Whisper",
    category: "video",
    deployment: "api",
    role: "Commercial-safe stock footage, narration and transcript/caption support for video proposals.",
    requiredEnv: [],
    optionalEnv: ["PEXELS_API_KEY", "ELEVENLABS_API_KEY", "FASTER_WHISPER_URL"],
    balance: "manual",
    docsUrl: "https://www.pexels.com/api/documentation/",
    recommended: true,
    notes: "OpenMontage/HyperFrames/Remotionの素材供給と音声・字幕生成に使う。著作権リスクを避けるため、商用利用可能な素材だけを許可する。",
  },
  {
    slug: "r2_delivery",
    displayName: "Cloudflare R2",
    category: "video",
    deployment: "api",
    role: "Fast delivery for generated reports, videos, PDFs and demo assets.",
    requiredEnv: [
      "CLOUDFLARE_R2_ACCOUNT_ID",
      "CLOUDFLARE_R2_ACCESS_KEY_ID",
      "CLOUDFLARE_R2_SECRET_ACCESS_KEY",
    ],
    requiredAnyEnv: ["CLOUDFLARE_R2_BUCKET", "R2_BUCKET"],
    optionalEnv: ["CLOUDFLARE_R2_PUBLIC_BASE_URL", "R2_PUBLIC_BASE_URL"],
    balance: "r2_health",
    recommended: true,
    notes: "bucket名だけではreadyにしません。account/access/secret、bucket、public base URL、HeadBucket疎通を要求します。",
  },
  {
    slug: "keystatic_demo_cms",
    displayName: "Keystatic",
    category: "demo_site",
    deployment: "oss",
    role: "Git-backed CMS for Astro demo-site edits by non-engineering operators.",
    requiredEnv: ["KEYSTATIC_BASE_URL"],
    optionalEnv: [
      "NEXT_PUBLIC_KEYSTATIC_URL", "KEYSTATIC_SYNC_WEBHOOK_URL",
      "KEYSTATIC_SYNC_WEBHOOK_SECRET", "ASTRO_DEMO_WORKER_URL", "ASTRO_DEMO_WORKER_TOKEN",
    ],
    balance: "keystatic_health",
    docsUrl: "https://github.com/Thinkmill/keystatic",
    recommended: true,
    notes: "未接続時はRevenue OS内のデモサイトテンプレート管理を使います。Git反映は別途Keystatic/Astro側のデプロイが必要です。",
  },
  {
    slug: "astro_demo",
    displayName: "Astro",
    category: "demo_site",
    deployment: "oss",
    role: "Fast reusable replacement demo sites for Web production proposals.",
    requiredEnv: [],
    optionalEnv: ["ASTRO_DEMO_FACTORY_URL"],
    balance: "astro_health",
    recommended: true,
    notes: "テンプレートは言語・業界・訴求別に分け、Difyが選択する。",
  },
  {
    slug: "hermes_slack",
    displayName: "Hermes Agent / Slack",
    category: "orchestration",
    deployment: "oss",
    role: "Agent approval lane, Slack notifications, and human-in-the-loop escalation.",
    requiredEnv: [],
    optionalEnv: ["HERMES_AGENT_WEBHOOK_URL", "SLACK_WEBHOOK_URL", "SLACK_BOT_TOKEN"],
    balance: "manual",
    recommended: true,
    notes: "Keeps autonomous jobs behind approval gates and records the human escalation surface.",
  },
  {
    slug: "notion_mcp",
    displayName: "Notion MCP",
    category: "orchestration",
    deployment: "api",
    role: "Customer workspace, handoff notes, and legacy knowledge capture bridge.",
    requiredEnv: [],
    optionalEnv: ["NOTION_API_KEY", "NOTION_MCP_TOKEN"],
    balance: "manual",
    recommended: false,
    notes: "Supabase remains the Sales OS SSOT; Notion is only a customer-facing or knowledge-capture surface.",
  },
  {
    slug: "supabase_mcp_nocodb",
    displayName: "Supabase MCP / NocoDB",
    category: "crm_ops",
    deployment: "oss",
    role: "Supabase operations and spreadsheet-style bulk list editing through NocoDB.",
    requiredEnv: [],
    optionalEnv: ["SUPABASE_ACCESS_TOKEN", "NOCODB_BASE_URL"],
    balance: "manual",
    recommended: true,
    notes: "NocoDB is an operating face over the Supabase SSOT, not a second source of truth.",
  },
  {
    slug: "chrome_mcp",
    displayName: "Chrome MCP",
    category: "orchestration",
    deployment: "local",
    role: "Operator-side browser inspection and visual QA for reports, demos, and forms.",
    requiredEnv: [],
    optionalEnv: ["CHROME_MCP_URL"],
    balance: "manual",
    recommended: false,
    notes: "Used for verification and QA; production automation should remain on Browserless/Stagehand workers.",
  },
  {
    slug: "rsshub_wayback",
    displayName: "RSSHub / Wayback Machine",
    category: "analysis",
    deployment: "oss",
    role: "News/feed monitoring and historical website evidence for timing and change detection.",
    requiredEnv: [],
    optionalEnv: ["RSSHUB_BASE_URL"],
    balance: "manual",
    recommended: true,
    notes: "Wayback can be checked without secrets; RSSHub becomes ready when a self-hosted or public base URL is configured.",
  },
  {
    slug: "public_web_corpora",
    displayName: "Common Crawl / Tranco / HTTP Archive",
    category: "list_source",
    deployment: "api",
    role: "Public-web corpus, ranking, and technology trend evidence for lead discovery and prioritization.",
    requiredEnv: [],
    optionalEnv: ["HTTPARCHIVE_BIGQUERY_PROJECT_ID"],
    balance: "none",
    recommended: true,
    notes: "Public datasets support sourcing and benchmarking without paid API dependency.",
  },
  {
    slug: "niche_list_sources",
    displayName: "WhoisDS / theHarvester / Events / Platform experts",
    category: "list_source",
    deployment: "api",
    role: "Fresh domains, OSINT contacts, event exhibitors, and platform expert directories.",
    requiredEnv: [],
    optionalEnv: [
      "WHOISDS_NRD_URL", "THEHARVESTER_BIN", "THEHARVESTER_WORKER_URL",
      "EVENTSEYE_SEARCH_URL", "TENTIMES_SEARCH_URL",
      "SHOPIFY_EXPERTS_URL", "WEBFLOW_EXPERTS_URL",
    ],
    balance: "manual",
    recommended: true,
    notes: "Secondary lead sources feed Supabase batches only after dedupe and scoring.",
  },
  {
    slug: "proposal_renderer_stack",
    displayName: "Slidev / Gotenberg / Marp / Recharts",
    category: "asset_generation",
    deployment: "oss",
    role: "Proposal decks, PDF conversion, chart rendering, and reusable sales-material templates.",
    requiredEnv: [],
    optionalEnv: ["GOTENBERG_URL", "SLIDEV_RENDER_URL", "MARP_RENDER_URL", "RECHARTS_ENABLED"],
    balance: "manual",
    recommended: true,
    notes: "Gotenberg is the PDF conversion lane; Slidev, Marp, and Recharts are generation/rendering surfaces.",
  },
  {
    slug: "demo_builder_stack",
    displayName: "Astro / v0 / shadcn UI",
    category: "demo_site",
    deployment: "oss",
    role: "Fast demo-site construction and component generation for proposal previews.",
    requiredEnv: [],
    optionalEnv: ["ASTRO_DEMO_WORKER_URL", "ASTRO_DEMO_FACTORY_URL", "V0_API_KEY", "V0_WORKER_URL", "SHADCN_BLOCKS_REGISTRY_URL"],
    balance: "manual",
    recommended: true,
    notes: "shadcn UI is a code/design dependency and does not require a runtime secret.",
  },
  {
    slug: "scrapoxy",
    displayName: "Scrapoxy",
    category: "proxy",
    deployment: "oss",
    role: "Optional proxy-manager alternative for crawler/browser outbound routing.",
    requiredEnv: [],
    optionalEnv: ["SCRAPOXY_API_URL", "SCRAPOXY_PROXY_URL", "SCRAPOXY_API_KEY"],
    balance: "manual",
    docsUrl: "https://github.com/fabienvauchelles/scrapoxy",
    recommended: false,
    notes: "mubeng remains the primary listed proxy rotator; Scrapoxy is tracked as an optional proxy-manager surface.",
  },
  {
    slug: "email_marketing_stack",
    displayName: "Listmonk / Mautic",
    category: "outreach",
    deployment: "oss",
    role: "Newsletter, nurture campaign, and non-1:1 email fallback routing.",
    requiredEnv: [],
    optionalEnv: ["LISTMONK_BASE_URL", "LISTMONK_API_KEY", "MAUTIC_BASE_URL", "MAUTIC_API_KEY"],
    balance: "manual",
    recommended: true,
    notes: "Separate campaign/newsletter automation from direct sales replies and CRM activity.",
  },
  {
    slug: "twenty_cms_alias",
    displayName: "TwentyCMS / Twenty CRM",
    category: "crm_ops",
    deployment: "oss",
    role: "Alias tracking for Twenty-based CRM/CMS operating surfaces.",
    requiredEnv: [],
    optionalEnv: ["TWENTY_BASE_URL", "TWENTY_CMS_BASE_URL"],
    balance: "manual",
    recommended: false,
    notes: "The production CRM source is Twenty OSS; TwentyCMS is tracked as an alias until a distinct CMS service is provisioned.",
  },
  {
    slug: "email_phone_stack",
    displayName: "Zoho / Smartlead / Resend / Listmonk / Twilio / HeyReach",
    category: "outreach",
    deployment: "api",
    role: "Email, newsletter, SMS/phone and LinkedIn fallback channels.",
    requiredEnv: [],
    optionalEnv: [
      "ZOHO_MAIL_CLIENT_ID", "SMARTLEAD_API_KEY", "RESEND_API_KEY", "LISTMONK_BASE_URL",
      "TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "IVRY_API_KEY", "HEYREACH_API_KEY", "DOCSEND_API_KEY",
    ],
    balance: "manual",
    recommended: true,
    notes: "フォーム自動送信が危険な場合の代替。ドメインウォームアップと上限監視が必須。",
  },
  {
    slug: "calcom",
    displayName: "Cal.com",
    category: "crm_ops",
    deployment: "oss",
    role: "Meeting booking and post-diagnosis consultation scheduling.",
    requiredEnv: ["CALCOM_BASE_URL"],
    optionalEnv: ["CALCOM_API_KEY", "CALCOM_WEBHOOK_URL"],
    balance: "none",
    recommended: true,
    notes: "成約時はDocuseal signed webhookから顧客ハンドオフを起動する。",
  },
  {
    slug: "chatwoot",
    displayName: "Chatwoot",
    category: "crm_ops",
    deployment: "oss",
    role: "Unified inbox for email replies, chat, and social DMs after outreach lands.",
    requiredEnv: ["CHATWOOT_BASE_URL", "CHATWOOT_API_KEY", "CHATWOOT_ACCOUNT_ID"],
    optionalEnv: ["CHATWOOT_WEBHOOK_URL", "N8N_POST_OUTREACH_WEBHOOK_URL"],
    balance: "chatwoot_health",
    docsUrl: "https://github.com/chatwoot/chatwoot",
    recommended: true,
    notes: "Webhookは/api/sales/chatwoot/webhookで受け、返信を活動ログとフォローアップキューに戻します。n8n設定時はAI返信導線へ転送します。",
  },
  {
    slug: "livekit",
    displayName: "LiveKit",
    category: "crm_ops",
    deployment: "oss",
    role: "Realtime voice/video lane for AI discovery calls and meeting transcripts.",
    requiredEnv: ["LIVEKIT_URL", "LIVEKIT_API_KEY", "LIVEKIT_API_SECRET"],
    optionalEnv: ["LIVEKIT_WEBHOOK_URL", "N8N_LIVEKIT_DISCOVERY_WEBHOOK_URL"],
    balance: "livekit_health",
    docsUrl: "https://github.com/livekit/livekit",
    recommended: true,
    notes: "Webhookは/api/sales/livekit/webhookで受け、初期ヒアリングの記録を活動ログと商談準備キューに戻します。",
  },
  {
    slug: "docuseal",
    displayName: "Docuseal",
    category: "crm_ops",
    deployment: "oss",
    role: "Contract signature and customer handoff after proposal acceptance.",
    requiredEnv: [],
    optionalEnv: ["DOCUSEAL_BASE_URL", "DOCUSEAL_API_KEY", "DOCUSEAL_WEBHOOK_URL"],
    balance: "none",
    recommended: true,
    notes: "署名Webhookは/api/sales/docuseal/webhookで受け、sales_contractsと顧客ハンドオフへ反映します。",
  },
  {
    slug: "proxy_pool",
    displayName: "DataImpulse / IPRoyal Proxy",
    category: "proxy",
    deployment: "api",
    role: "Proxy pool for compliant crawling, not for CAPTCHA bypass.",
    requiredEnv: [],
    optionalEnv: ["DATAIMPULSE_PROXY_URL", "DATAIMPULSE_API_KEY", "IPROYAL_PROXY_URL", "IPROYAL_API_KEY"],
    balance: "manual",
    recommended: true,
    notes: "残量は各プロバイダ管理画面/APIで確認。CAPTCHAやCloudflare Challengeは回避せず人間確認に切り替える。",
  },
  {
    slug: "mubeng",
    displayName: "mubeng",
    category: "proxy",
    deployment: "oss",
    role: "Fast proxy checker and IP rotator for routing outbound crawler/browser traffic through a controlled proxy pool.",
    requiredEnv: ["MUBENG_PROXY_URL"],
    optionalEnv: ["MUBENG_PROXY_USERNAME", "MUBENG_PROXY_PASSWORD"],
    balance: "mubeng_health",
    docsUrl: "https://github.com/mubeng/mubeng",
    recommended: true,
    notes: "mubengをローカルまたはセルフホストの回転プロキシとして起動し、SearxNG/Crawl4AI/Browserless系の外向き通信を同じ防衛線へ通します。CAPTCHA回避ではなく、負荷分散とIP保護のために使います。",
  },
]
