/**
 * lib/sales/integration-defs-assets.ts
 * asset_generation + video + demo_site + outreach + proxy カテゴリの統合定義
 */
import type { SalesIntegrationDefinition } from "./integration-registry-types"

export const ASSET_DEFS: SalesIntegrationDefinition[] = [
  {
    slug: "slidev_gotenberg",
    displayName: "Slidev / Gotenberg",
    category: "asset_generation",
    deployment: "oss",
    role: "HTML/Markdownからスライド形式の営業提案資料やPDFレポートを生成するGotenberg/Slidev連携エンジン。",
    requiredEnv: ["GOTENBERG_URL"],
    optionalEnv: ["SLIDEV_RENDER_URL"],
    balance: "slidev_gotenberg_health",
    recommended: true,
    notes: "Difyが構成案を生成し、Slidev/GotenbergでPDF化する。",
  },
  {
    slug: "directus_assets",
    displayName: "Directus",
    category: "asset_generation",
    deployment: "oss",
    role: "営業活動で使用する画像、PDF、スライド素材、および診断結果のメッセージパーツを管理するヘッドレスCMS。",
    requiredEnv: ["DIRECTUS_BASE_URL", "DIRECTUS_TOKEN"],
    optionalEnv: ["NEXT_PUBLIC_DIRECTUS_URL", "DIRECTUS_SALES_ASSETS_COLLECTION"],
    balance: "directus_health",
    docsUrl: "https://github.com/directus/directus",
    recommended: true,
    notes: "未接続時はRevenue OS内の資料スタジオにフォールバックします。外部Directusが404でも営業導線は止めません。",
  },
  {
    slug: "nextjs_reports",
    displayName: "Next.js report renderer",
    category: "asset_generation",
    deployment: "oss",
    role: "顧客ごとにパーソナライズされた診断レポートや動画視聴ページを動的にWeb描画するフロントエンドサーバー。",
    requiredEnv: ["NEXT_PUBLIC_SITE_URL"],
    optionalEnv: ["PARADIGMJP_BASE_URL"],
    balance: "none",
    docsUrl: "https://github.com/vercel/next.js",
    recommended: true,
    notes: "診断レポートはNext.jsの/[locale]/report/[slug]で描画します。顧客URLを生成するためNEXT_PUBLIC_SITE_URLは必須です。",
  },
  {
    slug: "proposal_renderer_stack",
    displayName: "Slidev / Gotenberg / Marp / Recharts",
    category: "asset_generation",
    deployment: "oss",
    role: "Slidev、Gotenberg、Marpなどの、スライド形式資料作成、グラフ描画、PDF変換を行う営業資料レンダリングツール群。",
    requiredEnv: [],
    optionalEnv: ["GOTENBERG_URL", "SLIDEV_RENDER_URL", "MARP_RENDER_URL", "RECHARTS_ENABLED"],
    balance: "manual",
    recommended: true,
    notes: "Gotenberg is the PDF conversion lane; Slidev, Marp, and Recharts are generation/rendering surfaces.",
  },
  {
    slug: "video_stack",
    displayName: "OpenMontage / ComfyUI / HyperFrames / Remotion",
    category: "video",
    deployment: "oss",
    role: "提案用パーソナライズ動画および納品用自動動画を生成する動画レンダリングエンジン群。",
    requiredEnv: [],
    optionalEnv: [
      "OPENMONTAGE_API_URL", "OPENMONTAGE_BASE_URL", "NEXT_PUBLIC_OPENMONTAGE_STUDIO_URL",
      "COMFYUI_API_URL", "REMOTION_RENDER_URL",
      "HYPERFRAMES_API_URL", "HYPERFRAMES_RENDERER_URL", "HYPERFRAMES_API_KEY",
    ],
    balance: "manual",
    recommended: true,
    notes: "Overview only. Production readiness is judged by the dedicated OpenMontage, HyperFrames, ComfyUI, and R2 runtime gates below.",
  },
  {
    slug: "openmontage_runtime",
    displayName: "OpenMontage",
    category: "video",
    deployment: "oss",
    role: "自動動画生成ジョブのスケジューリング、リソース管理、および動画スタジオURLを提供するオーケストレーター。",
    requiredEnv: ["OPENMONTAGE_API_URL", "OPENMONTAGE_API_KEY", "NEXT_PUBLIC_OPENMONTAGE_STUDIO_URL"],
    optionalEnv: ["OPENMONTAGE_BASE_URL", "OPENMONTAGE_STUDIO_HOST"],
    balance: "openmontage_health",
    docsUrl: "/docs/knowledge/revenue-os-production-service-setup.md",
    recommended: true,
    notes: "URLだけではreadyにしません。API URL、API key、Studio URL、health endpointの疎通を要求します。公開公式OSSとしては未確認のため、社内互換APIとして扱います。",
  },
  {
    slug: "hyperframes_renderer",
    displayName: "HyperFrames",
    category: "video",
    deployment: "oss",
    role: "HTMLの動きを動画（MP4等）に高速レンダリングしてパーソナライズ動画を作成するエンジン。",
    requiredEnv: ["HYPERFRAMES_API_KEY"],
    requiredAnyEnv: ["HYPERFRAMES_RENDERER_URL", "HYPERFRAMES_API_URL"],
    optionalEnv: [],
    balance: "hyperframes_health",
    docsUrl: "https://github.com/heygen-com/hyperframes",
    recommended: true,
    notes: "HyperFramesはURLだけではreadyにしません。renderer/API URLのいずれか、HYPERFRAMES_API_KEY、health endpoint疎通を要求します。",
  },
  {
    slug: "comfyui_api",
    displayName: "ComfyUI API",
    category: "video",
    deployment: "oss",
    role: "生成AIモデルをワークフロー化し、動画・スライド用の画像、アバター、BロールなどのアセットをGPU生成するAPI環境。",
    requiredEnv: ["COMFYUI_API_KEY"],
    requiredAnyEnv: ["COMFYUI_API_URL", "COMFYUI_BASE_URL"],
    optionalEnv: ["VAST_API_KEY", "RUNPOD_API_KEY"],
    balance: "comfyui_health",
    docsUrl: "https://github.com/comfyanonymous/ComfyUI",
    recommended: true,
    notes: "Public ComfyUI endpoints must not be unauthenticated. Revenue OS requires COMFYUI_API_KEY and /system_stats reachability before queueing jobs.",
  },
  {
    slug: "vast_api",
    displayName: "Vast.ai API",
    category: "video",
    deployment: "api",
    role: "ComfyUI等のAI動画生成ジョブが高負荷になった際に、クラウド上にオンデマンドでGPUインスタンスを立ち上げるAPI。",
    requiredEnv: ["VAST_API_KEY"],
    optionalEnv: [],
    balance: "vast_health",
    recommended: true,
    notes: "Allocates remote GPU power when on-premise hardware is saturated.",
  },
  {
    slug: "ffmpeg",
    displayName: "FFmpeg",
    category: "video",
    deployment: "local",
    role: "動画ファイルの切り出し、結合、音声合成、エンコード、圧縮処理を行うローカルの動画処理ツール。",
    requiredEnv: ["FFMPEG_BIN"],
    optionalEnv: [],
    balance: "ffmpeg_health",
    recommended: true,
    notes: "Required for base level video trimming and compression.",
  },
  {
    slug: "ffcreator",
    displayName: "FFCreator",
    category: "video",
    deployment: "oss",
    role: "Node.js上で高速にアニメーションや動画合成を行うための軽量動画生成ワーカープログラム。",
    requiredEnv: ["FFCREATOR_WORKER_URL"],
    optionalEnv: [],
    balance: "ffcreator_health",
    recommended: true,
    notes: "Alternative Node-based worker for video generation.",
  },
  {
    slug: "video_media_sources",
    displayName: "Pexels / ElevenLabs / Faster Whisper",
    category: "video",
    deployment: "api",
    role: "Pexelsのフリー動画素材、ElevenLabsのAIナレーション、Faster Whisperの音声文字起こしなど、動画素材と音声を供給するAPI群。",
    requiredEnv: [],
    optionalEnv: ["PEXELS_API_KEY", "ELEVENLABS_API_KEY", "FASTER_WHISPER_URL"],
    balance: "manual",
    docsUrl: "https://www.pexels.com/api/documentation/",
    recommended: true,
    notes: "OpenMontage/HyperFrames/Remotionの素材供給と音声・字幕生成に使う。著作権リスクを避けるため、商用利用可能な素材だけを許可する。",
  },
  {
    slug: "r2_delivery",
    displayName: "Cloudflare R2",
    category: "video",
    deployment: "api",
    role: "生成された動画、PDFレポート、デモサイトのコードアセットなどを高速かつ低コストで配信・保存するCloudflare R2ストレージAPI。",
    requiredEnv: [
      "CLOUDFLARE_R2_ACCOUNT_ID",
      "CLOUDFLARE_R2_ACCESS_KEY_ID",
      "CLOUDFLARE_R2_SECRET_ACCESS_KEY",
    ],
    requiredAnyEnv: ["CLOUDFLARE_R2_BUCKET", "R2_BUCKET"],
    optionalEnv: ["CLOUDFLARE_R2_PUBLIC_BASE_URL", "R2_PUBLIC_BASE_URL"],
    balance: "r2_health",
    recommended: true,
    notes: "bucket名だけではreadyにしません。account/access/secret、bucket、public base URL、HeadBucket疎通を要求します。",
  },
  {
    slug: "keystatic_demo_cms",
    displayName: "Keystatic",
    category: "demo_site",
    deployment: "oss",
    role: "Astroで構築したデモサイト内のコンテンツや設定を、非エンジニアがGit経由で編集できる管理UI（Keystatic）。",
    requiredEnv: ["KEYSTATIC_BASE_URL"],
    optionalEnv: [
      "NEXT_PUBLIC_KEYSTATIC_URL", "KEYSTATIC_SYNC_WEBHOOK_URL",
      "KEYSTATIC_SYNC_WEBHOOK_SECRET", "ASTRO_DEMO_WORKER_URL", "ASTRO_DEMO_WORKER_TOKEN",
    ],
    balance: "keystatic_health",
    docsUrl: "https://github.com/Thinkmill/keystatic",
    recommended: true,
    notes: "未接続時はRevenue OS内のデモサイトテンプレート管理を使います。Git反映は別途Keystatic/Astro側のデプロイが必要です。",
  },
  {
    slug: "astro_demo",
    displayName: "Astro",
    category: "demo_site",
    deployment: "oss",
    role: "提案先の企業に「改善後のWebサイト」のプレビューを高速提供するための、Astro製デモサイト生成・配信テンプレート。",
    requiredEnv: [],
    optionalEnv: ["ASTRO_DEMO_FACTORY_URL"],
    balance: "astro_health",
    recommended: true,
    notes: "テンプレートは言語・業界・訴求別に分け、Difyが選択する。",
  },
  {
    slug: "demo_builder_stack",
    displayName: "Astro / v0 / shadcn UI",
    category: "demo_site",
    deployment: "oss",
    role: "Astro、v0 by Vercel、shadcn UIなどの、提案用デモサイトおよびコンポーネントを高速構築するデザインシステムとフレームワーク群。",
    requiredEnv: [],
    optionalEnv: ["ASTRO_DEMO_WORKER_URL", "ASTRO_DEMO_FACTORY_URL", "V0_API_KEY", "V0_WORKER_URL", "SHADCN_BLOCKS_REGISTRY_URL"],
    balance: "manual",
    recommended: true,
    notes: "shadcn UI is a code/design dependency and does not require a runtime secret.",
  },
  {
    slug: "browserless",
    displayName: "Browserless",
    category: "outreach",
    deployment: "api",
    role: "SPAフォーム探索、送信前チェック、Webサイトの高解像度スクリーンショットを撮影するリモートブラウザ実行環境。",
    requiredEnv: ["BROWSERLESS_URL", "BROWSERLESS_TOKEN"],
    optionalEnv: [],
    balance: "browserless_pressure",
    docsUrl: "https://docs.browserless.io/enterprise/utility-functions/pressure",
    recommended: true,
    notes: "送信前にpressureを確認できる場合は、running/queuedを見て過負荷時に停止する。高解像度スクショ機能も提供。",
  },
  {
    slug: "stagehand",
    displayName: "Stagehand",
    category: "outreach",
    deployment: "oss",
    role: "PlaywrightとLLMを組み合わせ、多様な問い合わせフォームの入力欄を自律的に解釈して自動入力・送信するAIエージェント。",
    requiredEnv: ["STAGEHAND_URL", "STAGEHAND_API_KEY"],
    optionalEnv: [],
    balance: "stagehand_health",
    docsUrl: "https://github.com/browserbase/stagehand",
    recommended: true,
    notes: "Playwrightの裏でLLMを動かし、バラバラなフォーム構造を人間のように自律解釈して送信します。",
  },
  {
    slug: "crawlee",
    displayName: "Crawlee",
    category: "outreach",
    deployment: "oss",
    role: "Webサイトのリンク構造をクロールし、問い合わせページなどの宛先URLを特定する構造化クローラー。",
    requiredEnv: ["CRAWLEE_WORKER_URL"],
    optionalEnv: [],
    balance: "crawlee_health",
    docsUrl: "https://crawlee.dev/",
    recommended: true,
    notes: "Next.js本体では軽量fetch、重いクロールはworkerに逃がす。",
  },
  {
    slug: "crawl4ai",
    displayName: "Crawl4AI",
    category: "outreach",
    deployment: "oss",
    role: "Webページからレイアウトを保ったままテキストや問い合わせフォーム候補を抽出するAI向けクローラー。",
    requiredEnv: ["CRAWL4AI_BASE_URL"],
    optionalEnv: ["CRAWL4AI_API_KEY", "CRAWL4AI_FORM_DISCOVERY_PATH", "CRAWL4AI_HEALTH_PATH"],
    balance: "crawl4ai_health",
    recommended: true,
    notes: "HTML本文とフォーム候補の抽出を担当。送信は別ガードを通す。",
  },
  {
    slug: "playwright_stealth",
    displayName: "Playwright Stealth Worker",
    category: "outreach",
    deployment: "oss",
    role: "人間がチェックを通した後に、ステルスブラウザを使用して問い合わせフォームへの自動送信を実行するワーカー。",
    requiredEnv: ["OUTREACH_WORKER_URL"],
    optionalEnv: ["PLAYWRIGHT_STEALTH_ENABLED"],
    balance: "playwright_stealth_health",
    recommended: true,
    notes: "CAPTCHA/Cloudflare Challenge検出時は自動送信せず、人間キューへ切り替える。",
  },
  {
    slug: "camoufox",
    displayName: "Camoufox",
    category: "outreach",
    deployment: "oss",
    role: "ブラウザフィンガープリントを偽装し、手動レビューやQA時のアクセス制限を検証するための検証用ブラウザ環境。",
    requiredEnv: ["CAMOUFOX_WS_URL"],
    optionalEnv: [],
    balance: "none",
    recommended: false,
    notes: "回避目的ではなく、人間確認付きの再現・検証に限定する。",
  },
  {
    slug: "email_marketing_stack",
    displayName: "Listmonk / Mautic",
    category: "outreach",
    deployment: "oss",
    role: "ListmonkやMauticなどの、診断レポート配信後のステップメール、メルマガ、およびフォローアップメール配信エンジン。",
    requiredEnv: [],
    optionalEnv: ["LISTMONK_BASE_URL", "LISTMONK_API_KEY", "MAUTIC_BASE_URL", "MAUTIC_API_KEY"],
    balance: "manual",
    recommended: true,
    notes: "Separate campaign/newsletter automation from direct sales replies and CRM activity.",
  },
  {
    slug: "email_phone_stack",
    displayName: "Zoho / Smartlead / Resend / Listmonk / Twilio / HeyReach",
    category: "outreach",
    deployment: "api",
    role: "Zoho Mail、Smartlead、Twilioなどを経由し、フォーム送信が適さない場合のメールアプローチやSMS/電話、LinkedInなどの連絡経路群。",
    requiredEnv: [],
    optionalEnv: [
      "ZOHO_MAIL_CLIENT_ID", "SMARTLEAD_API_KEY", "RESEND_API_KEY", "LISTMONK_BASE_URL",
      "TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "IVRY_API_KEY", "HEYREACH_API_KEY", "DOCSEND_API_KEY",
    ],
    balance: "manual",
    recommended: true,
    notes: "フォーム自動送信が危険な場合の代替。ドメインウォームアップと上限監視が必須。",
  },
  {
    slug: "steel",
    displayName: "Steel.dev",
    category: "outreach",
    deployment: "oss",
    role: "ヘッドレスブラウザ自動化。ステルスモードでページスクレイピング、スクリーンショット、データ抽出を行う。",
    requiredEnv: [],
    optionalEnv: ["STEEL_BASE_URL", "STEEL_API_KEY"],
    balance: "steel_health",
    docsUrl: "https://github.com/steel-dev/steel-browser",
    recommended: true,
    notes: "Stagehandの補完。軽量なスクレイピング・スクリーンショット取得に最適。",
  },
  {
    slug: "skyvern",
    displayName: "Skyvern (legacy)",
    category: "outreach",
    deployment: "oss",
    role: "旧ブラウザ自動化。Stagehand + Steel.devに置換済み。",
    requiredEnv: [],
    optionalEnv: ["SKYVERN_BASE_URL", "SKYVERN_API_KEY"],
    balance: "skyvern_health",
    docsUrl: "https://github.com/Skyvern-AI/skyvern",
    recommended: false,
    notes: "Stagehandに移行済み。後方互換のために定義のみ残す。",
  },
  {
    slug: "flaresolverr",
    displayName: "FlareSolverr",
    category: "proxy",
    deployment: "oss",
    role: "CloudflareやDDoS-GUARDなどのWAFブロックをバイパスし、ブロックされたサイトへのHTTPリクエストを中継するプロキシ。",
    requiredEnv: [],
    optionalEnv: ["FLARESOLVERR_API_URL"],
    balance: "flaresolverr_health",
    docsUrl: "https://github.com/FlareSolverr/FlareSolverr",
    recommended: true,
    notes: "診断レポートのWAF検出バイパスに使用。CAPTCHA回避は行わず、Cloudflare Challengeの突破に限定。",
  },
  {
    slug: "scrapoxy",
    displayName: "Scrapoxy",
    category: "proxy",
    deployment: "oss",
    role: "自動データ収集やブラウザ実行時のIPアドレス制限を回避するための、プロキシ分散管理OSS。",
    requiredEnv: [],
    optionalEnv: ["SCRAPOXY_API_URL", "SCRAPOXY_PROXY_URL", "SCRAPOXY_API_KEY"],
    balance: "manual",
    docsUrl: "https://github.com/fabienvauchelles/scrapoxy",
    recommended: false,
    notes: "mubeng remains the primary listed proxy rotator; Scrapoxy is tracked as an optional proxy-manager surface.",
  },
  {
    slug: "proxy_pool",
    displayName: "DataImpulse / IPRoyal Proxy",
    category: "proxy",
    deployment: "api",
    role: "クローラーやブラウザが接続ブロックされるのを防ぐため、IPアドレスを適切にローテーションさせるプロキシ接続プールAPI。",
    requiredEnv: [],
    optionalEnv: ["DATAIMPULSE_PROXY_URL", "DATAIMPULSE_API_KEY", "IPROYAL_PROXY_URL", "IPROYAL_API_KEY"],
    balance: "manual",
    recommended: true,
    notes: "残量は各プロバイダ管理画面/APIで確認。CAPTCHAやCloudflare Challengeは回避せず人間確認に切り替える。",
  },
  {
    slug: "mubeng",
    displayName: "mubeng",
    category: "proxy",
    deployment: "oss",
    role: "セルフホストで動作し、SearxNGやCrawl4AI等のすべての外向き通信に対してプロキシの稼働チェックとローテーションを行うプロキシサーバー。",
    requiredEnv: ["MUBENG_PROXY_URL"],
    optionalEnv: ["MUBENG_PROXY_USERNAME", "MUBENG_PROXY_PASSWORD"],
    balance: "mubeng_health",
    docsUrl: "https://github.com/mubeng/mubeng",
    recommended: true,
    notes: "mubengをローカルまたはセルフホストの回転プロキシとして起動し、SearxNG/Crawl4AI/Browserless系の外向き通信を同じ防衛線へ通します。CAPTCHA回避ではなく、負荷分散とIP保護のために使います。",
  },
]
