/**
 * lib/sales/integration-defs-orchestration.ts
 * orchestration + crm_ops カテゴリの統合定義
 */
import { DIFY_RUNTIME_KEY_ENV_NAMES, DIFY_RUNTIME_URL_ENV_NAMES } from "./dify-cloud"
import type { SalesIntegrationDefinition } from "./integration-registry-types"

export const ORCHESTRATION_DEFS: SalesIntegrationDefinition[] = [
  {
    slug: "dify_cloud",
    displayName: "Dify Cloud",
    category: "orchestration",
    deployment: "cloud",
    role: "DeepSeek V4を連携し、企業診断、提案文作成、テンプレート選定、人間確認フローを行う中核ワークフロー。",
    requiredEnv: [],
    requiredAnyEnv: DIFY_RUNTIME_KEY_ENV_NAMES,
    optionalEnv: [...DIFY_RUNTIME_URL_ENV_NAMES],
    balance: "dify_health",
    docsUrl: "https://docs.dify.ai/api-reference/workflows/run-workflow",
    recommended: true,
    notes: "DifyはCloud版 api.dify.ai のみを正とする。用途別キーを認識し、APIキーの実値はUI・ログへ出さない。",
  },
  {
    slug: "deepseek",
    displayName: "DeepSeek API",
    category: "orchestration",
    deployment: "api",
    role: "Difyワークフローが利用できない場合のフォールバック用LLMおよび構造化データ生成エンジン。",
    requiredEnv: ["DEEPSEEK_API_KEY"],
    optionalEnv: ["DEEPSEEK_BASE_URL"],
    balance: "manual",
    recommended: true,
    notes: "Dify Cloud内の推論モデルを優先し、直APIは補助・検証用に限定する。",
  },
  {
    slug: "trigger_dev",
    displayName: "Trigger.dev",
    category: "orchestration",
    deployment: "cloud",
    role: "時間のかかるデータ収集ジョブ、動画・レポート生成、再試行制御を行うバックグラウンドジョブ実行エンジン。",
    requiredEnv: ["TRIGGER_SECRET_KEY"],
    optionalEnv: [
      "TRIGGER_API_URL",
      "TRIGGER_DASHBOARD_URL",
      "TRIGGER_SALES_OS_PIPELINE_TASK_ID",
      "TRIGGER_POST_OUTREACH_TASK_ID",
      "TRIGGER_CHATWOOT_REPLY_TASK_ID",
      "TRIGGER_LIVEKIT_DISCOVERY_TASK_ID",
    ],
    balance: "trigger_dev_health",
    recommended: true,
    notes: "営業OSの長時間ジョブ、再試行制御、webhook転送の主要なオーケストレーターです。",
  },
  {
    slug: "hermes_slack",
    displayName: "Hermes Agent / Slack",
    category: "orchestration",
    deployment: "oss",
    role: "自動送信前にオペレーターの承認を求める通知や、エラー・問い合わせ時のSlack通知をルーティングする連携モジュール。",
    requiredEnv: [],
    optionalEnv: ["HERMES_AGENT_WEBHOOK_URL", "SLACK_WEBHOOK_URL", "SLACK_BOT_TOKEN"],
    balance: "manual",
    recommended: true,
    notes: "Keeps autonomous jobs behind approval gates and records the human escalation surface.",
  },
  {
    slug: "notion_mcp",
    displayName: "Notion MCP",
    category: "orchestration",
    deployment: "api",
    role: "顧客用の共有スペース、議事録、および社内の引継ぎナレッジを同期するためのNotion連携API。",
    requiredEnv: [],
    optionalEnv: ["NOTION_API_KEY", "NOTION_MCP_TOKEN"],
    balance: "manual",
    recommended: false,
    notes: "Supabase remains the Sales OS SSOT; Notion is only a customer-facing or knowledge-capture surface.",
  },
  {
    slug: "chrome_mcp",
    displayName: "Chrome MCP",
    category: "orchestration",
    deployment: "local",
    role: "開発者やオペレーター側で、診断レポートやデモサイトの表示崩れ、フォーム動作のテストをローカルブラウザで行う検証用API。",
    requiredEnv: [],
    optionalEnv: ["CHROME_MCP_URL"],
    balance: "manual",
    recommended: false,
    notes: "Used for verification and QA; production automation should remain on Steel-Browser/Stagehand workers.",
  },
  {
    slug: "supabase_ssot",
    displayName: "Supabase SSOT",
    category: "crm_ops",
    deployment: "oss",
    role: "リード、診断レポート、ジョブ履歴、商談、契約書、監査ログを管理する中心データベース（SSOT）。",
    requiredEnv: [],
    requiredAnyEnv: ["SALES_SUPABASE_SERVICE_ROLE_KEY", "SUPABASE_SERVICE_ROLE_KEY"],
    optionalEnv: ["SALES_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_URL", "SUPABASE_PAT"],
    balance: "none",
    docsUrl: "https://github.com/supabase/supabase",
    recommended: true,
    notes: "営業データの正本です。service_role未設定時はSales OSをdegraded表示にし、偽成功で処理を進めません。",
  },
  {
    slug: "supabase_studio",
    displayName: "Supabase Studio",
    category: "crm_ops",
    deployment: "oss",
    role: "データベースのテーブル作成・データ確認をGUIで行う管理画面。",
    requiredEnv: ["NEXT_PUBLIC_SUPABASE_STUDIO_URL"],
    optionalEnv: [],
    balance: "supabase_studio_health",
    recommended: true,
    notes: "Allows direct row-level exploration and editing.",
  },
  {
    slug: "twenty_crm",
    displayName: "Twenty CRM",
    category: "crm_ops",
    deployment: "oss",
    role: "企業情報、商談ステージ、活動履歴、営業担当者を管理するCRM画面。",
    requiredEnv: ["TWENTY_BASE_URL"],
    optionalEnv: ["TWENTY_API_KEY", "TWENTY_DATABASE_URL"],
    balance: "manual",
    docsUrl: "https://github.com/twentyhq/twenty",
    recommended: true,
    notes: "Supabase SSOTの会社情報をCRM画面へ投影します。APIキーが無い場合は画面リンクのみ、メタデータ同期は無効です。",
  },
  {
    slug: "twenty_cms_alias",
    displayName: "TwentyCMS / Twenty CRM",
    category: "crm_ops",
    deployment: "oss",
    role: "CRM（Twenty）に関連する追加の設定や、別名連携を行うためのエイリアス管理。",
    requiredEnv: [],
    optionalEnv: ["TWENTY_BASE_URL", "TWENTY_CMS_BASE_URL"],
    balance: "manual",
    recommended: false,
    notes: "The production CRM source is Twenty OSS; TwentyCMS is tracked as an alias until a distinct CMS service is provisioned.",
  },
  {
    slug: "calcom",
    displayName: "Cal.com",
    category: "crm_ops",
    deployment: "oss",
    role: "診断レポートの閲覧後に、相手がコンサルティング商談の予約（Cal.com）を直ちに行えるカレンダー調整機能。",
    requiredEnv: ["CALCOM_BASE_URL"],
    optionalEnv: ["CALCOM_API_KEY", "CALCOM_WEBHOOK_URL"],
    balance: "calcom_health",
    recommended: true,
    notes: "成約時はDocuseal signed webhookから顧客ハンドオフを起動する。",
  },
  {
    slug: "chatwoot",
    displayName: "Chatwoot",
    category: "crm_ops",
    deployment: "oss",
    role: "アプローチ送信後の相手からの返信（メール、SNS、チャットなど）を1つのタイムラインで管理し、AI返信下書きを作成する共通インボックス。",
    requiredEnv: ["CHATWOOT_BASE_URL", "CHATWOOT_API_KEY", "CHATWOOT_ACCOUNT_ID"],
    optionalEnv: ["CHATWOOT_WEBHOOK_URL", "TRIGGER_CHATWOOT_REPLY_TASK_ID", "TRIGGER_POST_OUTREACH_TASK_ID"],
    balance: "chatwoot_health",
    docsUrl: "https://github.com/chatwoot/chatwoot",
    recommended: true,
    notes: "Webhookは/api/sales/chatwoot/webhookで受け、返信を活動ログとフォローアップキューに戻します。Trigger.dev設定時はAI返信導線へ転送します。",
  },
  {
    slug: "livekit",
    displayName: "LiveKit",
    category: "crm_ops",
    deployment: "oss",
    role: "商談やヒアリング時の音声・ビデオ通話を処理し、リアルタイムでのAIアシスタント動作や文字起こし・要約を行うシステム。",
    requiredEnv: ["LIVEKIT_URL", "LIVEKIT_API_KEY", "LIVEKIT_API_SECRET"],
    optionalEnv: ["LIVEKIT_WEBHOOK_URL", "TRIGGER_LIVEKIT_DISCOVERY_TASK_ID", "TRIGGER_POST_OUTREACH_TASK_ID"],
    balance: "livekit_health",
    docsUrl: "https://github.com/livekit/livekit",
    recommended: true,
    notes: "Webhookは/api/sales/livekit/webhookで受け、初期ヒアリングの記録を活動ログと商談準備キューに戻します。Trigger.dev設定時はAI返信導線へ転送します。",
  },
  {
    slug: "docuseal",
    displayName: "Docuseal",
    category: "crm_ops",
    deployment: "oss",
    role: "商談後に、契約書の作成・電子署名をオンラインで完結させ、自動で顧客ハンドオフへ進める電子契約署名システム。",
    requiredEnv: [],
    optionalEnv: ["DOCUSEAL_BASE_URL", "DOCUSEAL_API_KEY", "DOCUSEAL_WEBHOOK_URL"],
    balance: "none",
    recommended: true,
    notes: "署名Webhookは/api/sales/docuseal/webhookで受け、sales_contractsと顧客ハンドオフへ反映します。",
  },
  {
    slug: "supabase_mcp_nocodb",
    displayName: "Supabase MCP / NocoDB",
    category: "crm_ops",
    deployment: "oss",
    role: "Supabaseのデータベースを、スプレッドシートのような操作画面で一括編集できるようにするNocoDBの連携設定。",
    requiredEnv: [],
    optionalEnv: ["SUPABASE_ACCESS_TOKEN", "NOCODB_BASE_URL"],
    balance: "manual",
    recommended: true,
    notes: "NocoDB is an operating face over the Supabase SSOT, not a second source of truth.",
  },
]
