import { z } from "zod"

const caseRef = z.object({ caseId: z.string().uuid() })
const evidenceRef = z.string().uuid().nullable().optional()
const actorNote = z.string().trim().min(2).max(2000)

export const workspaceActionSchema = z.discriminatedUnion("action", [
  caseRef.extend({
    action: z.literal("request_outbound"),
    channel: z.string().trim().min(2).max(80),
    recipient: z.string().trim().min(2).max(2000),
    message: z.string().min(1).max(100_000),
    note: actorNote,
    expiresAt: z.string().datetime(),
  }),
  z.object({
    action: z.literal("approve_outbound"),
    approvalId: z.string().uuid(),
    overrideReason: z.string().trim().max(2000).optional(),
  }),
  z.object({
    action: z.literal("record_suppression"),
    companyId: z.string().uuid().nullable().optional(),
    contactKey: z.string().trim().min(3).max(2000).nullable().optional(),
    channel: z.string().trim().min(2).max(80).default("all"),
    scope: z.enum(["global", "company", "contact"]),
    reasonCode: z.string().trim().min(2).max(100),
    reason: actorNote,
    expiresAt: z.string().datetime().nullable().optional(),
    evidenceId: evidenceRef,
  }).superRefine((value, context) => {
    if (!value.companyId && !value.contactKey) context.addIssue({ code: "custom", message: "A company or contact target is required" })
    if (value.scope === "company" && !value.companyId) context.addIssue({ code: "custom", path: ["companyId"], message: "Company scope requires companyId" })
    if (value.scope === "contact" && !value.contactKey) context.addIssue({ code: "custom", path: ["contactKey"], message: "Contact scope requires contactKey" })
  }),
  z.object({
    action: z.literal("assign_role"),
    principalKey: z.string().trim().min(2).max(300),
    principalEmail: z.string().email().nullable().optional(),
    operatorRole: z.enum(["admin", "commercial_lead", "researcher", "finance", "legal", "delivery", "japan_operator", "viewer", "automation"]),
    active: z.boolean(),
    reason: actorNote,
  }),
  z.object({
    action: z.literal("link_source"),
    sourceConfigId: z.string().uuid(),
    offerCode: z.string().trim().min(2).max(120).default("standard_operator_v1"),
    cadenceHours: z.number().int().min(1).max(8760),
    filters: z.record(z.string(), z.unknown()).default({}),
  }),
  caseRef.extend({
    action: z.literal("create_contract_draft"),
    contractKind: z.enum(["validation_sow", "launch_sow", "operator_agreement"]),
    contractName: z.string().trim().min(2).max(500),
    templateId: z.number().int().positive(),
    submitterName: z.string().trim().min(2).max(300),
    submitterEmail: z.string().email(),
    submitterRole: z.string().trim().min(2).max(120),
    amountMinor: z.number().int().nonnegative(),
    currency: z.enum(["JPY", "USD", "EUR", "GBP", "CNY", "KRW", "SGD"]),
    expiresAt: z.string().datetime().nullable().optional(),
    values: z.record(z.string(), z.unknown()).default({}),
  }),
  caseRef.extend({
    action: z.literal("link_contract"),
    contractKind: z.enum(["validation_sow", "launch_sow", "operator_agreement"]),
    salesContractId: z.string().uuid(),
    docusealSubmissionId: z.string().trim().max(300).nullable().optional(),
    status: z.enum(["draft", "sent", "viewed", "signed", "declined", "expired", "voided"]),
    signedAt: z.string().datetime().nullable().optional(),
    detail: z.record(z.string(), z.unknown()).default({}),
  }),
  caseRef.extend({
    action: z.literal("record_invoice"),
    invoiceKind: z.enum(["validation", "launch", "retainer", "revenue_share", "expense", "adjustment"]),
    provider: z.string().trim().min(2).max(80).default("stripe"),
    externalInvoiceId: z.string().trim().max(300).nullable().optional(),
    externalPaymentId: z.string().trim().max(300).nullable().optional(),
    amountMinor: z.number().int().nonnegative(),
    currency: z.string().length(3),
    status: z.enum(["draft", "open", "paid", "void", "uncollectible", "refunded", "partially_refunded"]),
    issuedAt: z.string().datetime().nullable().optional(),
    dueAt: z.string().datetime().nullable().optional(),
    paidAt: z.string().datetime().nullable().optional(),
    evidenceId: evidenceRef,
    validationCreditSourceId: z.string().uuid().nullable().optional(),
  }),
  caseRef.extend({
    action: z.literal("upsert_sku"),
    sku: z.string().trim().min(1).max(200),
    productName: z.string().trim().min(2).max(500),
    category: z.string().trim().min(2).max(200),
    hsCode: z.string().trim().max(40).nullable().optional(),
    importerOfRecord: z.string().trim().max(300).nullable().optional(),
    sellerOfRecord: z.string().trim().max(300).nullable().optional(),
    labelingStatus: z.enum(["pending", "blocked", "ready", "not_applicable"]),
    complianceStatus: z.enum(["pending", "blocked", "ready", "not_applicable"]),
    customsStatus: z.enum(["pending", "blocked", "ready", "not_applicable"]),
    blockerCodes: z.array(z.string().trim().min(1).max(100)).max(50).default([]),
    evidenceId: evidenceRef,
    detail: z.record(z.string(), z.unknown()).default({}),
  }),
  caseRef.extend({
    action: z.literal("record_deliverable"),
    phase: z.enum(["validation", "launch", "operations", "offboarding"]),
    deliverableType: z.string().trim().min(2).max(120),
    title: z.string().trim().min(2).max(500),
    description: actorNote,
    owner: z.string().trim().min(2).max(120),
    dueAt: z.string().datetime().nullable().optional(),
    status: z.enum(["planned", "in_progress", "submitted", "accepted", "rejected", "cancelled"]),
    acceptanceCriteria: z.array(z.string().trim().min(2).max(500)).min(1).max(50),
    acceptedAt: z.string().datetime().nullable().optional(),
    evidenceId: evidenceRef,
    changeRequestOfId: z.string().uuid().nullable().optional(),
  }),
  caseRef.extend({
    action: z.literal("record_finance_period"),
    periodStart: z.string().date(), periodEnd: z.string().date(), settlementCurrency: z.string().length(3),
    fxRate: z.number().positive(), grossMinor: z.number().int(), refundMinor: z.number().int(), taxMinor: z.number().int(),
    channelFeeMinor: z.number().int(), paymentFeeMinor: z.number().int(), fulfillmentMinor: z.number().int(),
    freightDutyMinor: z.number().int(), marketingMinor: z.number().int(), otherDeductionMinor: z.number().int(),
    netRevenueMinor: z.number().int(), revenueShareMinor: z.number().int(), retainerMinor: z.number().int(),
    payableMinor: z.number().int(), status: z.enum(["open", "review", "approved", "invoiced", "paid", "locked"]),
    evidenceId: evidenceRef,
  }),
  z.object({
    action: z.literal("record_finance_line"), periodId: z.string().uuid(),
    externalOrderId: z.string().trim().max(300).nullable().optional(), channel: z.string().trim().min(2).max(120),
    transactionAt: z.string().datetime(), sourceCurrency: z.string().length(3), grossMinor: z.number().int(),
    refundMinor: z.number().int(), taxMinor: z.number().int(), channelFeeMinor: z.number().int(),
    paymentFeeMinor: z.number().int(), fulfillmentMinor: z.number().int(), freightDutyMinor: z.number().int(),
    marketingMinor: z.number().int(), otherDeductionMinor: z.number().int(), netRevenueMinor: z.number().int(),
    evidenceId: evidenceRef, detail: z.record(z.string(), z.unknown()).default({}),
  }),
  caseRef.extend({
    action: z.literal("record_operation"),
    recordType: z.enum(["order", "inventory", "return", "refund", "fulfillment", "customer_support", "marketing", "change_request", "data_export", "credential_handoff"]),
    externalRef: z.string().trim().max(300).nullable().optional(), skuId: z.string().uuid().nullable().optional(),
    status: z.string().trim().min(2).max(120), quantity: z.number().nullable().optional(), amountMinor: z.number().int().nullable().optional(),
    currency: z.string().length(3).nullable().optional(), occurredAt: z.string().datetime(), dueAt: z.string().datetime().nullable().optional(),
    owner: z.string().trim().max(120).nullable().optional(), evidenceId: evidenceRef,
    detail: z.record(z.string(), z.unknown()).default({}),
  }),
  caseRef.extend({
    action: z.literal("record_incident"), incidentType: z.enum(["quality", "safety", "recall", "regulatory", "privacy", "fraud", "delivery", "service", "other"]),
    severity: z.enum(["low", "medium", "high", "critical"]), title: z.string().trim().min(2).max(500),
    description: actorNote, occurredAt: z.string().datetime(), owner: z.string().trim().min(2).max(120), evidenceId: z.string().uuid(),
  }),
  caseRef.extend({
    action: z.literal("record_kpi"), periodStart: z.string().date(), periodEnd: z.string().date(),
    metrics: z.record(z.string(), z.number()), targets: z.record(z.string(), z.number()),
    status: z.enum(["draft", "submitted", "accepted", "cure_period", "failed", "superseded"]),
    exclusivityDecision: z.enum(["continue", "modify", "terminate", "not_applicable"]).nullable().optional(),
    cureDueAt: z.string().datetime().nullable().optional(), evidenceId: evidenceRef,
  }),
  caseRef.extend({
    action: z.literal("record_offboarding"), status: z.enum(["planned", "in_progress", "review", "completed", "cancelled"]),
    reason: actorNote, effectiveAt: z.string().datetime().nullable().optional(), checklist: z.record(z.string(), z.boolean()),
    evidenceId: evidenceRef,
  }),
])

export type WorkspaceAction = z.infer<typeof workspaceActionSchema>
