import fs from "node:fs"
import path from "node:path"
import { describe, expect, it } from "vitest"

const root = process.cwd()
const read = (file: string) => fs.readFileSync(path.join(root, file), "utf8")

describe("manual Japan Entry release wiring", () => {
  it("applies and verifies the dedicated table before deploy", () => {
    const deploy = read("scripts/sales-os-no-login-deploy.mjs")
    const verifier = read("scripts/verify-db-tables.mjs")
    const doctor = read("scripts/release-doctor.mjs")
    const twenty = read("scripts/twenty-sales-select-options.sql")
    const service = read("src/lib/sales/manual-japan-entry-service.ts")
    const workflowHelpers = read("src/lib/sales/manual-japan-entry-workflow-helpers.ts")
    const report = read("src/lib/sales/manual-japan-entry-report.ts")
    const formVerification = read("src/lib/sales/sources/external-form-verification.ts")
    const experimentMigration = read("supabase/migrations/20260716090000_manual_form_copy_experiment.sql")
    const anglesMigration = read("supabase/migrations/20260716180000_manual_form_copy_angles.sql")
    const sourceLedgerMigration = read("supabase/migrations/20260716181500_manual_japan_entry_source_ledger.sql")

    expect(deploy).toContain("applyManualJapanEntryWorkMigration")
    expect(deploy).toContain("20260715031327_manual_japan_entry_work.sql")
    expect(verifier).toContain('"manual_japan_entry_work"')
    expect(verifier).toContain('"manual_japan_entry_source_catalog"')
    expect(verifier).toContain('"manual_japan_entry_work_sources"')
    expect(deploy).toContain("applyManualFormCopyExperimentMigration")
    expect(deploy).toContain("20260716090000_manual_form_copy_experiment.sql")
    expect(deploy).toContain("applyManualFormCopyAnglesMigration")
    expect(deploy).toContain("20260716180000_manual_form_copy_angles.sql")
    expect(deploy).toContain("applyManualJapanEntrySourceLedgerMigration")
    expect(deploy).toContain("20260716181500_manual_japan_entry_source_ledger.sql")
    expect(doctor).toContain("manual Japan Entry workbench has grounded four-cell and evidence-gated angle copy, industry and market lenses, company-evidence-only commercial signals, a separate source master")
    expect(doctor).toContain("no_automatic_country_adjustment")
    expect(doctor).toContain("manual copy experiment columns/angle playbooks/outcome constraint/RLS/zero-send guard")
    expect(experimentMigration).toContain("message_variant_requested")
    expect(experimentMigration).toContain("manually_sent_at")
    expect(experimentMigration).toContain("Never set by an automated delivery path")
    expect(anglesMigration).toContain("message_angle_requested")
    expect(anglesMigration).toContain("outreach_playbook")
    expect(anglesMigration).toContain("Unsupported competitor, opportunity, or mockup requests fall back to problem")
    expect(sourceLedgerMigration).toContain("manual_japan_entry_source_catalog")
    expect(sourceLedgerMigration).toContain("manual_japan_entry_work_sources")
    expect(sourceLedgerMigration).toContain("qualification_ledger")
    expect(sourceLedgerMigration).toContain("no collector, scheduler, or send path")
    expect(twenty).toContain("'manual_work'")
    expect(service).toContain('purpose: "initial_interest"')
    expect(service).not.toContain('purpose: "commercial_offer"')
    expect(workflowHelpers).toContain("productContext: input.evidence.productContext")
    expect(report).toContain("buildJapanEntryPersonalizationFacts")
    expect(report).toContain("matchContentTemplate")
    expect(report).toContain('evidence_contract: "public-pages-only"')
    expect(formVerification).toContain('inspection.status === "form"')
  })
})
