import fs from "node:fs"
import path from "node:path"
import { describe, expect, it } from "vitest"

const root = process.cwd()
const read = (file: string) => fs.readFileSync(path.join(root, file), "utf8")

describe("manual Japan Entry release wiring", () => {
  it("applies and verifies the dedicated table before deploy", () => {
    const deploy = read("scripts/sales-os-no-login-deploy.mjs")
    const verifier = read("scripts/verify-db-tables.mjs")
    const doctor = read("scripts/release-doctor.mjs")
    const twenty = read("scripts/twenty-sales-select-options.sql")
    const service = read("src/lib/sales/manual-japan-entry-service.ts")
    const profile = read("src/lib/sales/manual-japan-entry-profile.ts")
    const manualTwenty = read("src/lib/sales/manual-japan-entry-twenty.ts")
    const copySmoke = read("scripts/smoke-japan-entry-form-copy.mts")
    const copyEnvelope = read("src/lib/sales/manual-japan-entry-copy-envelope.ts")
    const historyItem = read("src/components/work/ManualWorkHistoryItem.tsx")
    const workPage = read("src/app/work/page.tsx")
    const deepSeek = read("src/lib/deepseek.ts")
    const workflowHelpers = read("src/lib/sales/manual-japan-entry-workflow-helpers.ts")
    const report = read("src/lib/sales/manual-japan-entry-report.ts")
    const reportTypes = read("src/lib/sales/manual-japan-entry-report-types.ts")
    const reportResolver = read("src/lib/sales/manual-japan-entry-report-resolver.ts")
    const reportPage = read("src/app/[locale]/work-report/[token]/page.tsx")
    const reportRenderer = read("src/components/work-report/ManualJapanEntryReport.tsx")
    const conditionalSiteChrome = read("src/components/aesop/ConditionalSiteChrome.tsx")
    const standaloneRoutes = read("src/components/aesop/standalone-routes.ts")
    const formVerification = read("src/lib/sales/sources/external-form-verification.ts")
    const experimentMigration = read("supabase/migrations/20260716090000_manual_form_copy_experiment.sql")
    const anglesMigration = read("supabase/migrations/20260716180000_manual_form_copy_angles.sql")
    const sourceLedgerMigration = read("supabase/migrations/20260716181500_manual_japan_entry_source_ledger.sql")
    const reportV2Migration = read("supabase/migrations/20260719032800_manual_japan_entry_report_v2.sql")
    const formDiagnosticsMigration = read("supabase/migrations/20260719211533_manual_work_verified_form_and_copy_diagnostics.sql")

    expect(deploy).toContain("applyManualJapanEntryWorkMigration")
    expect(deploy).toContain("20260715031327_manual_japan_entry_work.sql")
    expect(verifier).toContain('"manual_japan_entry_work"')
    expect(verifier).toContain('"manual_japan_entry_source_catalog"')
    expect(verifier).toContain('"manual_japan_entry_work_sources"')
    expect(deploy).toContain("applyManualFormCopyExperimentMigration")
    expect(deploy).toContain("20260716090000_manual_form_copy_experiment.sql")
    expect(deploy).toContain("applyManualFormCopyAnglesMigration")
    expect(deploy).toContain("20260716180000_manual_form_copy_angles.sql")
    expect(deploy).toContain("applyManualJapanEntrySourceLedgerMigration")
    expect(deploy).toContain("20260716181500_manual_japan_entry_source_ledger.sql")
    expect(deploy).toContain("applyManualJapanEntryReportV2Migration")
    expect(deploy).toContain("20260719032800_manual_japan_entry_report_v2.sql")
    expect(deploy).toContain("applyManualWorkVerifiedFormAndCopyDiagnosticsMigration")
    expect(deploy).toContain("20260719211533_manual_work_verified_form_and_copy_diagnostics.sql")
    expect(doctor).toContain("manual Japan Entry workbench has a customer-facing V3 report, legacy isolation, login return routing, grounded copy")
    expect(doctor).toContain("no_automatic_country_adjustment")
    expect(doctor).toContain("manual copy experiment/report V2/angle playbooks/outcome constraint/RLS/zero-send guard")
    expect(experimentMigration).toContain("message_variant_requested")
    expect(experimentMigration).toContain("manually_sent_at")
    expect(experimentMigration).toContain("Never set by an automated delivery path")
    expect(anglesMigration).toContain("message_angle_requested")
    expect(anglesMigration).toContain("outreach_playbook")
    expect(anglesMigration).toContain("Unsupported competitor, opportunity, or mockup requests fall back to problem")
    expect(sourceLedgerMigration).toContain("manual_japan_entry_source_catalog")
    expect(sourceLedgerMigration).toContain("manual_japan_entry_work_sources")
    expect(sourceLedgerMigration).toContain("qualification_ledger")
    expect(sourceLedgerMigration).toContain("no collector, scheduler, or send path")
    expect(reportV2Migration).toContain("manual_japan_entry_v2")
    expect(reportV2Migration).toContain("legacyTemplateUsed")
    expect(reportV2Migration).toContain("automaticSendAllowed")
    expect(formDiagnosticsMigration).toContain("generation_error")
    expect(formDiagnosticsMigration).toContain("form_discovery #>> '{inspection,status}' = 'form'")
    expect(twenty).toContain("'manual_work'")
    expect(service).toContain('purpose: "initial_interest"')
    expect(service).not.toContain('purpose: "commercial_offer"')
    expect(service).toContain('!hasRecordedOutcome && (item.status === "failed" || item.status === "needs_review")')
    expect(service).toContain("generation_error")
    expect(manualTwenty).toContain("twentyNumberMatches")
    expect(manualTwenty).toContain("twentyLinkMatches")
    expect(service).toContain('twenty_sync_status === "failed"')
    expect(service).toContain("ownedCompanyId: work.twenty_company_id")
    expect(profile).toContain("normalizeManualCompanyProfile")
    expect(profile).toContain("after one repair")
    expect(manualTwenty).toContain("ManualTwentySyncError")
    expect(manualTwenty).toContain("Twenty保存確認")
    expect(copySmoke).toContain('purpose: "initial_interest"')
    expect(copySmoke).toContain("noUrlOrDomain")
    expect(copySmoke).toContain("noCommercialTerms")
    expect(copySmoke).toContain("copyReadySignature")
    expect(copySmoke).toContain("approvedSenderEmailOnce")
    expect(copyEnvelope).toContain('name: "Tomohiro H"')
    expect(copyEnvelope).toContain('company: "Paradigm LLC"')
    expect(copyEnvelope).toContain('email: "contact@paradigmjp.com"')
    expect(historyItem).toContain("再解析")
    expect(historyItem).toContain("ManualFormDiscoveryStatus")
    expect(workPage).toContain('redirect("/admin/login?redirect=%2Fwork")')
    expect(deepSeek).toContain("DeepSeek APIの残高不足で解析を停止しました")
    expect(workflowHelpers).toContain("productContext: input.evidence.productContext")
    expect(report).toContain("buildJapanEntryPersonalizationFacts")
    expect(report).toContain("MANUAL_JAPAN_ENTRY_REPORT_SCHEMA")
    expect(report).not.toContain("matchContentTemplate")
    expect(report).not.toContain("DiagnosticReportData")
    expect(reportTypes).toContain('"manual_japan_entry_customer_v3"')
    expect(reportTypes).toContain('"customer_japan_entry_opportunity_report"')
    expect(reportResolver).toContain("resolveManualJapanEntryReportData")
    expect(reportPage).toContain("ManualJapanEntryReport")
    expect(reportPage).toContain("resolveManualJapanEntryReportData")
    expect(reportPage).not.toContain("DiagnosticReport")
    expect(reportPage).not.toContain("ensureSafeDiagnosticReport")
    expect(reportRenderer).toContain("Japan Entry Opportunity Report")
    expect(reportRenderer).toContain("Executive perspective")
    expect(reportRenderer).not.toContain("Private evidence brief")
    expect(reportRenderer).not.toContain("Never sent automatically")
    expect(conditionalSiteChrome).toContain("isStandaloneRoute")
    expect(standaloneRoutes).toContain("work-report")
    expect(formVerification).toContain('inspection.status === "form"')
  })
})
