import fs from "node:fs"
import path from "node:path"
import { describe, expect, it } from "vitest"

const root = process.cwd()
const read = (file: string) => fs.readFileSync(path.join(root, file), "utf8")

describe("manual Japan Entry release wiring", () => {
  it("applies and verifies the dedicated table before deploy", () => {
    const deploy = read("scripts/sales-os-no-login-deploy.mjs")
    const verifier = read("scripts/verify-db-tables.mjs")
    const doctor = read("scripts/release-doctor.mjs")
    const twenty = read("scripts/twenty-sales-select-options.sql")
    const service = read("src/lib/sales/manual-japan-entry-service.ts")
    const profile = read("src/lib/sales/manual-japan-entry-profile.ts")
    const fitPolicy = read("src/lib/sales/manual-japan-entry-fit-policy.ts")
    const autoRecovery = read("src/lib/sales/manual-work-auto-recovery.ts")
    const recoveryPolicy = read("src/lib/sales/manual-work-recovery-policy.ts")
    const manualTwenty = read("src/lib/sales/manual-japan-entry-twenty.ts")
    const copySmoke = read("scripts/smoke-japan-entry-form-copy.mts")
    const copyEnvelope = read("src/lib/sales/manual-japan-entry-copy-envelope.ts")
    const messageReview = read("src/lib/sales/japan-entry-personalized-message-review.ts")
    const historyItem = read("src/components/work/ManualWorkHistoryItem.tsx")
    const messageIntelligence = read("src/components/work/ManualMessageIntelligence.tsx")
    const operatorNotice = read("src/lib/sales/manual-work-operator-notice.ts")
    const workPage = read("src/app/work/page.tsx")
    const workLayout = read("src/app/work/layout.tsx")
    const workConsole = read("src/components/work/ManualJapanEntryWorkConsole.tsx")
    const deepSeek = read("src/lib/deepseek.ts")
    const workflowHelpers = read("src/lib/sales/manual-japan-entry-workflow-helpers.ts")
    const report = read("src/lib/sales/manual-japan-entry-report.ts")
    const reportTypes = read("src/lib/sales/manual-japan-entry-report-types.ts")
    const reportResolver = read("src/lib/sales/manual-japan-entry-report-resolver.ts")
    const reportPage = read("src/app/[locale]/work-report/[token]/page.tsx")
    const reportRenderer = read("src/components/work-report/ManualJapanEntryReport.tsx")
    const reportVisuals = read("src/components/work-report/ManualReportVisuals.tsx")
    const strategyChapter = read("src/components/work-report/ManualStrategyChapter.tsx")
    const batchSchedule = read("src/lib/sales/manual-japan-entry-batch-schedule.ts")
    const batchDrain = read("src/lib/sales/manual-japan-entry-batch-drain.ts")
    const batchPreflight = read("src/lib/sales/manual-japan-entry-batch-preflight.ts")
    const batchEvents = read("src/app/api/work/batches/[batchId]/events/route.ts")
    const workStore = read("src/lib/sales/manual-japan-entry-store.ts")
    const conditionalSiteChrome = read("src/components/aesop/ConditionalSiteChrome.tsx")
    const standaloneRoutes = read("src/components/aesop/standalone-routes.ts")
    const formVerification = read("src/lib/sales/sources/external-form-verification.ts")
    const experimentMigration = read("supabase/migrations/20260716090000_manual_form_copy_experiment.sql")
    const anglesMigration = read("supabase/migrations/20260716180000_manual_form_copy_angles.sql")
    const sourceLedgerMigration = read("supabase/migrations/20260716181500_manual_japan_entry_source_ledger.sql")
    const reportV2Migration = read("supabase/migrations/20260719032800_manual_japan_entry_report_v2.sql")
    const formDiagnosticsMigration = read("supabase/migrations/20260719211533_manual_work_verified_form_and_copy_diagnostics.sql")
    const batchMigration = read("supabase/migrations/20260720233215_manual_work_durable_batches.sql")
    const batchRealtimeMigration = read("supabase/migrations/20260721123500_manual_work_batch_realtime.sql")
    const ownershipMigration = read("supabase/migrations/20260721193000_manual_work_report_ownership_and_scale.sql")
    const terminalFailuresMigration = read("supabase/migrations/20260722044000_manual_work_terminal_source_failures.sql")
    const durableRetryMigration = read("supabase/migrations/20260722123000_manual_work_durable_retry_queue.sql")
    const legacyReportPage = read("src/app/[locale]/report/[slug]/page.tsx")
    const artifactAuthority = read("src/lib/sales/manual-work-artifact-authority.ts")

    expect(deploy).toContain("applyManualJapanEntryWorkMigration")
    expect(deploy).toContain("20260715031327_manual_japan_entry_work.sql")
    expect(verifier).toContain('"manual_japan_entry_work"')
    expect(verifier).toContain('"manual_japan_entry_source_catalog"')
    expect(verifier).toContain('"manual_japan_entry_work_sources"')
    expect(deploy).toContain("applyManualFormCopyExperimentMigration")
    expect(deploy).toContain("20260716090000_manual_form_copy_experiment.sql")
    expect(deploy).toContain("applyManualFormCopyAnglesMigration")
    expect(deploy).toContain("20260716180000_manual_form_copy_angles.sql")
    expect(deploy).toContain("applyManualJapanEntrySourceLedgerMigration")
    expect(deploy).toContain("20260716181500_manual_japan_entry_source_ledger.sql")
    expect(deploy).toContain("applyManualJapanEntryReportV2Migration")
    expect(deploy).toContain("20260719032800_manual_japan_entry_report_v2.sql")
    expect(deploy).toContain("applyManualWorkVerifiedFormAndCopyDiagnosticsMigration")
    expect(deploy).toContain("20260719211533_manual_work_verified_form_and_copy_diagnostics.sql")
    expect(deploy).toContain("applyManualWorkDurableBatchesMigration")
    expect(deploy).toContain("20260720233215_manual_work_durable_batches.sql")
    expect(deploy).toContain("applyManualWorkBatchRealtimeMigration")
    expect(deploy).toContain("20260721123500_manual_work_batch_realtime.sql")
    expect(deploy).toContain("applyManualWorkReportOwnershipAndScaleMigration")
    expect(deploy).toContain("20260721193000_manual_work_report_ownership_and_scale.sql")
    expect(deploy).toContain("applyManualWorkTerminalSourceFailuresMigration")
    expect(deploy).toContain("20260722044000_manual_work_terminal_source_failures.sql")
    expect(deploy).toContain("applyManualWorkDurableRetryQueueMigration")
    expect(deploy).toContain("20260722123000_manual_work_durable_retry_queue.sql")
    expect(durableRetryMigration).toContain("manual_japan_entry_create_retry_batch")
    expect(durableRetryMigration).toContain("retry_requested")
    expect(durableRetryMigration).toContain("expected_work_id")
    expect(doctor).toContain("manual Japan Entry workbench has one-shot recovery, opportunity-first fit, a visual customer-facing V4 strategy report, server-drained durable 500-URL queue, paginated history")
    expect(doctor).toContain("no_automatic_country_adjustment")
    expect(doctor).toContain("manual copy experiment/report V4/durable batch/outcome constraint/RLS/zero-send guard")
    expect(experimentMigration).toContain("message_variant_requested")
    expect(experimentMigration).toContain("manually_sent_at")
    expect(experimentMigration).toContain("Never set by an automated delivery path")
    expect(anglesMigration).toContain("message_angle_requested")
    expect(anglesMigration).toContain("outreach_playbook")
    expect(anglesMigration).toContain("Unsupported competitor, opportunity, or mockup requests fall back to problem")
    expect(sourceLedgerMigration).toContain("manual_japan_entry_source_catalog")
    expect(sourceLedgerMigration).toContain("manual_japan_entry_work_sources")
    expect(sourceLedgerMigration).toContain("qualification_ledger")
    expect(sourceLedgerMigration).toContain("no collector, scheduler, or send path")
    expect(reportV2Migration).toContain("manual_japan_entry_v2")
    expect(reportV2Migration).toContain("must never downgrade a newer report")
    expect(reportV2Migration).toContain("manual_japan_entry_customer_v3")
    expect(reportV2Migration).toContain("manual_japan_entry_strategy_v4")
    expect(reportV2Migration).toContain("legacyTemplateUsed")
    expect(reportV2Migration).toContain("automaticSendAllowed")
    expect(deploy).toContain("reconcileManualWorkV4Artifacts")
    expect(deploy).toContain("/api/work/artifacts/reconcile")
    expect(deploy).toContain("result?.currentReports === result?.checked")
    expect(deploy).toContain("result?.legacyReports === 0")
    expect(doctor).toContain("report_data ->> 'schemaVersion' is distinct from 'manual_japan_entry_strategy_v4'")
    expect(formDiagnosticsMigration).toContain("generation_error")
    expect(formDiagnosticsMigration).toContain("updated_at < now() - interval '15 minutes'")
    expect(formDiagnosticsMigration).toContain("Interrupted analysis was recovered as retryable")
    expect(formDiagnosticsMigration).toContain("form_discovery #>> '{inspection,status}' = 'form'")
    expect(batchMigration).toContain("total_count BETWEEN 1 AND 500")
    expect(batchMigration).toContain("FOR UPDATE SKIP LOCKED")
    expect(batchMigration).toContain("sent boolean NOT NULL DEFAULT false CHECK (sent = false)")
    expect(batchRealtimeMigration).toContain("supabase_realtime")
    expect(batchRealtimeMigration).toContain("manual_japan_entry_batch_items")
    expect(ownershipMigration).toContain("legacy_report_slug")
    expect(ownershipMigration).toContain("queued_count integer NOT NULL DEFAULT 0")
    expect(ownershipMigration).toContain("idx_manual_japan_entry_work_twenty_company_id")
    expect(terminalFailuresMigration).toContain("status = 'rejected'")
    expect(terminalFailuresMigration).toContain("stage = 'complete'")
    expect(doctor).toContain("applyManualWorkTerminalSourceFailuresMigration")
    expect(twenty).toContain("'manual_work'")
    expect(service).toContain('purpose: "initial_interest"')
    expect(service).not.toContain('purpose: "commercial_offer"')
    expect(service).toContain('phase: "public evidence collection"')
    expect(service).toContain('phase: "company classification"')
    expect(service).toContain('phase: "initial message generation"')
    expect(service).toContain("maxAttempts: 2")
    expect(service).toContain("generationUsage = addDeepSeekUsage(generationUsage, result.usage)")
    expect(service).toContain('phase: "Twenty persistence and read-back"')
    expect(service).toContain("generation_error")
    expect(manualTwenty).toContain("twentyNumberMatches")
    expect(manualTwenty).toContain("twentyLinkMatches")
    expect(service).toContain('twenty_sync_status === "failed"')
    expect(service).toContain("ownedCompanyId: work.twenty_company_id")
    expect(profile).toContain("normalizeManualCompanyProfile")
    expect(profile).toContain("after one repair")
    expect(profile).toContain("JAPAN_ENTRY_FIT_CONTRACT_VERSION")
    expect(fitPolicy).toContain('"opportunity-first-v1"')
    expect(fitPolicy).toContain("DIGITAL_DELIVERY_PATTERN")
    expect(fitPolicy).toContain("Missing Japanese localization or current Japan presence is a market-entry readiness gap")
    expect(autoRecovery).toContain("maxAttempts > 3")
    expect(recoveryPolicy).toContain('item.status === "failed"')
    expect(recoveryPolicy).toContain('item.twenty_sync_status === "failed"')
    expect(recoveryPolicy).toContain('["completed", "needs_review"].includes(item.status)')
    expect(recoveryPolicy).toContain("isExplicitManualWorkArtifactRefresh")
    expect(manualTwenty).toContain("ManualTwentySyncError")
    expect(manualTwenty).toContain("Twenty保存確認")
    expect(copySmoke).toContain('purpose: "initial_interest"')
    expect(copySmoke).toContain("noUrlOrDomain")
    expect(copySmoke).toContain("noCommercialTerms")
    expect(copySmoke).toContain("copyReadySignature")
    expect(copySmoke).toContain("approvedSenderEmailOnce")
    expect(copyEnvelope).toContain('name: "Tomohiro H"')
    expect(copyEnvelope).toContain('company: "Paradigm LLC"')
    expect(copyEnvelope).toContain('email: "contact@paradigmjp.com"')
    expect(messageReview).toContain("Indefinite article must agree with the following company or product anchor")
    expect(historyItem).toContain("isManualWorkRecoveryAvailable")
    expect(historyItem).toContain("fastPriority(item)")
    expect(historyItem).toContain("ChatGPTブリーフを準備")
    expect(historyItem).toContain("自動送信: なし")
    expect(service).toContain("shouldUseTwentyOnlyRetry")
    expect(messageIntelligence).toContain("fastQualification")
    expect(messageIntelligence).toContain("文章生成APIは呼び出していません")
    expect(messageIntelligence).toContain("ChatGPT Pro手動バッチから取込・機械検証済み")
    expect(operatorNotice).toContain("fastQualification(item)")
    expect(operatorNotice).toContain("文章生成モデルも定型文も使っておらず、送信文はまだありません")
    expect(operatorNotice).toContain("解析結果は/workの履歴に保持され、外部送信は行っていません")
    expect(workPage).toContain('redirect("/admin/login?redirect=%2Fwork")')
    expect(workLayout).toContain('width: "device-width"')
    expect(workLayout).toContain('className="min-h-full w-full min-w-full overflow-x-clip')
    expect(workConsole).toContain('min-h-dvh w-full min-w-0 overflow-x-clip')
    expect(workConsole).toContain('mx-auto w-full min-w-0 max-w-[1480px]')
    expect(deepSeek).toContain("DeepSeek APIの残高不足で解析を停止しました")
    expect(workflowHelpers).toContain("productContext: input.evidence.productContext")
    expect(report).toContain("buildJapanEntryPersonalizationFacts")
    expect(report).toContain("MANUAL_JAPAN_ENTRY_REPORT_SCHEMA")
    expect(report).not.toContain("matchContentTemplate")
    expect(report).not.toContain("DiagnosticReportData")
    expect(reportTypes).toContain('"manual_japan_entry_strategy_v4"')
    expect(reportTypes).toContain("strategyChapters")
    expect(reportTypes).toContain('"customer_japan_entry_opportunity_report"')
    expect(reportResolver).toContain("resolveManualJapanEntryReportData")
    expect(reportPage).toContain("ManualJapanEntryReport")
    expect(reportPage).toContain("resolveManualJapanEntryReportData")
    expect(reportPage).not.toContain("DiagnosticReport")
    expect(reportPage).not.toContain("ensureSafeDiagnosticReport")
    expect(legacyReportPage).toContain("permanentRedirect(`/en/work-report/${manualAlias.token}`)")
    expect(artifactAuthority).toContain("restoreManualWorkTwentyHome")
    expect(artifactAuthority).toContain("persistCurrentManualWorkReport")
    expect(reportRenderer).toContain("Japan Entry Strategy Report")
    expect(reportRenderer).toContain("Ten decision chapters")
    expect(reportRenderer).toContain("Executive perspective")
    expect(reportRenderer).toContain("ManualReportVisuals")
    expect(reportVisuals).toContain("Readiness scorecard")
    expect(reportVisuals).toContain("Evidence architecture")
    expect(reportVisuals).toContain("Decision matrix")
    expect(strategyChapter).toContain("Chapter evidence composition")
    expect(strategyChapter).toContain("traceability map")
    expect(batchSchedule).toContain("after(async ()")
    expect(batchSchedule).toContain("dispatchManualWorkBatchDrain")
    expect(batchDrain).toContain("http://127.0.0.1:")
    expect(batchDrain).toContain("x-webhook-secret")
    expect(batchPreflight).toContain("preflightManualWorkBatch")
    expect(batchPreflight).toContain("maxTokens: 4")
    expect(batchEvents).toContain('type: "item"')
    expect(batchEvents).toContain('type: "batch"')
    expect(workStore).toContain("listManualJapanEntryWorkPage")
    expect(workStore).toContain("getManualWorkDashboardSummary")
    expect(messageReview).toContain("Repeated or near-duplicate sentences are prohibited")
    expect(reportRenderer).not.toContain("Private evidence brief")
    expect(reportRenderer).not.toContain("Never sent automatically")
    expect(conditionalSiteChrome).toContain("isStandaloneRoute")
    expect(standaloneRoutes).toContain("work-report")
    expect(formVerification).toContain('inspection.status === "form"')
  })
})
