/**
 * multi-page-generator.ts — DeepSeek generates full multi-page site content
 * as JSON, then builder writes each page as a .astro file.
 *
 * Output structure:
 *   pages/home.astro, pages/about.astro, pages/services.astro, ...
 *   All share PageLayout + Figma design system
 */
import { buildSystemPrompt } from "./astro-code-generator"

const DEEPSEEK_BASE_URL = process.env.DEEPSEEK_API_BASE || "https://api.deepseek.com/v1"
const DEEPSEEK_MODEL = process.env.DEEPSEEK_MODEL || "deepseek-chat"

export interface MultiPageManifest {
  site: {
    companyName: string
    locale: string
    industry: string
    location: string
    pages: string[]           // ["home","about","services","cases","faq","contact"] etc
    nav: { label: string; href: string }[]
    footer: { address?: string; phone?: string; email?: string }
  }
  pages: Record<string, {
    title: string
    description: string
    /** HTML content blocks — generated by DeepSeek using Figma design system */
    html: string
  }>
}

export interface MultiPageResult {
  ok: boolean
  manifest?: MultiPageManifest
  error?: string
}

// ── Page selection by industry ──

const PAGE_SUGGESTIONS: Record<string, string[]> = {
  "飲食店":     ["home","about","services","cases","faq","contact"],
  "建設業":     ["home","about","services","cases","pricing","faq","contact"],
  "歯科医院":   ["home","about","services","faq","contact"],
  "美容サロン": ["home","about","services","cases","faq","contact"],
  "小売店":     ["home","about","services","pricing","contact"],
  "会計事務所": ["home","about","services","cases","pricing","faq","contact"],
  "清掃業":     ["home","about","services","cases","faq","contact"],
  "コンサル":   ["home","about","services","cases","pricing","faq","blog","contact"],
  "default":     ["home","about","services","contact"],
}

function suggestPages(industry: string | null, locale: string): string[] {
  if (industry && PAGE_SUGGESTIONS[industry]) return PAGE_SUGGESTIONS[industry]
  return PAGE_SUGGESTIONS["default"]
}

// ── Generate ──

export async function generateMultiPageSite(
  input: {
    companyName: string
    domain: string
    industry: string | null
    location: string | null
    locale: string
    diagnosis: { pain_summary: string; issues: string[]; pagespeed_mobile: number | null; pagespeed_desktop: number | null; tech_stack: string[]; improvements: { headline: string; body: string; metrics: string[] }[] }
    realContent: { about?: string; services?: string; testimonials?: string; pricing?: string }
    availableImages: string[]
  }
): Promise<MultiPageResult> {
  const apiKey = process.env.DEEPSEEK_API_KEY
  if (!apiKey) return { ok: false, error: "DEEPSEEK_API_KEY not configured" }

  const isJa = input.locale === "ja"
  const suggestedPages = suggestPages(input.industry, input.locale)
  const system = buildSystemPrompt(input.industry)

  const user = [
    `企業名: ${input.companyName}`,
    `業種: ${input.industry || "不明"}`,
    `所在地: ${input.location || "不明"}`,
    `ドメイン: ${input.domain}`,
    `言語: ${input.locale}`,
    `生成すべきページ: ${suggestedPages.join(", ")}`,
    "",
    `診断: ${input.diagnosis.pain_summary}`,
    `PageSpeed: モバイル${input.diagnosis.pagespeed_mobile ?? "?"}点, デスクトップ${input.diagnosis.pagespeed_desktop ?? "?"}点`,
    input.realContent.about ? `会社概要: ${input.realContent.about.slice(0, 800)}` : "",
    input.realContent.services ? `サービス内容: ${input.realContent.services.slice(0, 800)}` : "",
    input.realContent.testimonials ? `お客様の声: ${input.realContent.testimonials.slice(0, 800)}` : "",
    "",
    "== 出力指示 ==",
    "以下のJSON形式で全ページの内容を出力せよ。各ページのhtmlは<section>の連続。Figmaトークン厳守。",
    "セクションはdark/light/glass交互。各セクション最低3行の本文段落。",
    "全セクションにfadeUpアニメーション。画像は使わずCSS gradientで。",
    "",
    "{",
    '  "site": {',
    `    "companyName": "${input.companyName}",`,
    `    "locale": "${input.locale}",`,
    `    "industry": "${input.industry || ""}",`,
    `    "location": "${input.location || ""}",`,
    `    "pages": ${JSON.stringify(suggestedPages)},`,
    `    "nav": [{"label":"ホーム","href":"/"},{"label":"サービス","href":"/services"},...],`,
    `    "footer": {"address":"${input.location || ""}","phone":"","email":""}`,
    "  },",
    '  "pages": {',
    '    "home": { "title":"...", "description":"...", "html":"<section class=\\"hero dark\\">...</section><section class=\\"about light\\">...</section>..." },',
    '    "about": { "title":"...", "description":"...", "html":"..." },',
    "    ...",
    "  }",
    "}",
    "",
    "各ページのhtmlは完全な<section>要素の連続。PageLayoutの中で使われる。",
    "nav/footer/headタグは不要（PageLayoutが生成する）。",
    "HTMLのみ。説明文不要。有効なJSON1つのみ出力。",
  ].filter(Boolean).join("\n")

  try {
    const res = await fetch(`${DEEPSEEK_BASE_URL}/chat/completions`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify({
        model: DEEPSEEK_MODEL,
        messages: [
          { role: "system", content: system },
          { role: "user", content: user },
        ],
        temperature: 0.7,
        max_tokens: 16384,
        response_format: { type: "json_object" },
      }),
      signal: AbortSignal.timeout(120_000),
    })

    const data = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> }
    let raw = data.choices?.[0]?.message?.content ?? ""
    if (!raw) return { ok: false, error: "DeepSeek returned empty" }

    raw = raw.replace(/```(?:json)?\s*|\s*```/g, "").trim()
    // Fix common JSON issues from LLM output
    raw = raw.replace(/[\u0000-\u001F]/g, " ")  // control chars
             .replace(/\\(?!["\\/bfnrtu])/g, "\\\\") // fix bad escapes
    let parsed: MultiPageManifest
    try {
      parsed = JSON.parse(raw) as MultiPageManifest
    } catch {
      // Try lenient parse: find the outermost { }
      const m = raw.match(/\{[\s\S]*\}/)
      if (!m) return { ok: false, error: "no valid JSON found" }
      try { parsed = JSON.parse(m[0]) as MultiPageManifest }
      catch { return { ok: false, error: "JSON parse failed after recovery" } }
    }

    if (!parsed.site || !parsed.pages || !parsed.pages.home) {
      return { ok: false, error: "invalid manifest: missing site or pages.home" }
    }

    return { ok: true, manifest: parsed }
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) }
  }
}

// ── Builder: manifest → .astro files ──

import { selectDesignSystem } from "./figma-design-system"
export { buildSystemPrompt } from "./astro-code-generator"

export function buildAstroPages(manifest: MultiPageManifest): Map<string, string> {
  const files = new Map<string, string>()
  const ds = selectDesignSystem(manifest.site.industry)
  const tokens = ds.colors.tokens
  const typo = ds.typography
  const space = ds.spacing

  // Build CSS custom properties from design tokens
  const cssVars = Object.entries(tokens)
    .map(([name, t]) => `  --c-${name}: ${t.light};`)
    .join("\n")

  const pageLayoutProps = JSON.stringify({
    companyName: manifest.site.companyName,
    pages: manifest.site.nav,
    footer: manifest.site.footer,
  })

  // Build each page
  for (const [slug, page] of Object.entries(manifest.pages)) {
    if (!page || !page.html) continue

    const isHome = slug === "home"
    const href = isHome ? "/" : `/${slug}`

    const astroCode = [
      "---",
      "import PageLayout from '../components/pipeline/PageLayout.astro'",
      "---",
      "",
      `<PageLayout`,
      `  companyName="${manifest.site.companyName}"`,
      `  pages={${JSON.stringify(manifest.site.nav)}}`,
      `  footer={${JSON.stringify(manifest.site.footer)}}`,
      ">",
      `  <style is:inline set:html={\``,
      "    :root {",
      cssVars,
      `      --font-heading: ${typo.families.heading};`,
      `      --font-body: ${typo.families.body};`,
      "    }",
      `    .section{padding:${space.sectionPadding} 0}`,
      `    .container{${space.containerMax}}`,
      "    .dark{background:var(--c-bg-dark);color:var(--c-text-dark)}",
      "    .light{background:var(--c-bg-light);color:var(--c-text-light)}",
      "    .glass{background:var(--c-bg-glass);color:var(--c-text-dark)}",
      `    h1{font-family:var(--font-heading);font-size:${typo.scale.h1.fontSize};font-weight:${typo.scale.h1.fontWeight};letter-spacing:${typo.scale.h1.letterSpacing};line-height:${typo.scale.h1.lineHeight}}`,
      `    h2{font-family:var(--font-heading);font-size:${typo.scale.h2.fontSize};font-weight:${typo.scale.h2.fontWeight};letter-spacing:${typo.scale.h2.letterSpacing}}`,
      `    h3{font-size:${typo.scale.h3.fontSize};font-weight:${typo.scale.h3.fontWeight}}`,
      "    .card{background:rgba(255,255,255,.08);padding:2.5rem 2rem;border-radius:20px;border:1px solid rgba(255,255,255,.06);transition:transform .3s ease,box-shadow .3s ease}",
      "    .card:hover{transform:translateY(-4px);box-shadow:0 20px 60px rgba(0,0,0,.2)}",
      "    .btn{display:inline-block;background:linear-gradient(135deg,var(--c-primary),var(--c-accent));color:#fff;padding:1rem 2.5rem;border-radius:50px;text-decoration:none;font-weight:700;transition:transform .3s ease,box-shadow .3s ease;box-shadow:0 4px 24px var(--glow)}",
      "    .btn:hover{transform:translateY(-2px);box-shadow:0 8px 30px var(--glow)}",
      "    .fadeUp{animation:fadeUp .8s ease both}",
      "    @keyframes fadeUp{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:translateY(0)}}",
      "    @media(max-width:768px){.container{padding:0 1rem}}",
      "  \`}></style>",
      "",
      `  <main>`,
      `    ${page.html}`,
      `  </main>`,
      "</PageLayout>",
      ""
    ].join("\n")

    const fileName = isHome ? "index.astro" : `${slug}.astro`
    files.set(fileName, astroCode)
  }

  return files
}
