/**
 * procedural-design.ts — No templates. Design emerges mathematically
 * from company data. LLM extracts numeric parameters (0.0-1.0),
 * algorithms compute the visual output.
 */
const API = process.env.DEEPSEEK_API_BASE || "https://api.deepseek.com/v1"
const MODEL = process.env.DEEPSEEK_MODEL || "deepseek-chat"

export interface BrandDNA {
  /** Unique seed derived from company identity */
  brand_seed: string
  /** 0.0-1.0: Solidity/trust. Higher = serif fonts, wider spacing, heavier weights */
  gravity: number
  /** 0.0-1.0: Speed/urgency. Higher = faster animations, tighter layouts, bold CTAs */
  velocity: number
  /** 0.0-1.0: Information density. Higher = more grid columns, more sections */
  complexity: number
  /** 0.0-1.0: Warmth. Higher = warm colors, rounded corners, softer shadows */
  warmth: number
  /** 0-360: Base hue derived from industry */
  color_hue: number
  /** Content generated by LLM */
  copy: {
    headline: string
    subheadline: string
    sections: Array<{ title: string; body: string }>
    cta: string
  }
}

export interface ProceduralTokens {
  /** CSS custom properties */
  css: Record<string, string>
  /** Typography scale */
  typography: {
    fontFamily: string
    headingWeight: number
    bodySize: string
    headingSize: string
    letterSpacing: string
  }
  /** Spacing system */
  spacing: {
    sectionPadding: string
    cardPadding: string
    gap: string
    containerMax: string
  }
  /** Derived color palette */
  palette: {
    primary: string; primaryLight: string; primaryDark: string
    background: string; surface: string
    text: string; textMuted: string
    accent: string
    border: string
    shadow: string
  }
  /** Grid layout */
  layout: {
    heroColumns: string
    cardColumns: string
    cardMinWidth: string
  }
  /** Animation */
  animation: {
    duration: string
    easing: string
    delay: string
  }
  /** Shader seed for WebGL backgrounds */
  shaderSeed: number
}

// ── Step 1: LLM extracts BrandDNA from company data ──

export async function extractBrandDNA(company: {
  name: string; domain: string; industry: string | null; location: string | null
  founded?: string; employeeCount?: number; reviewRating?: number
  aboutText?: string; services?: string[]; painSummary?: string
}): Promise<{ ok: boolean; dna?: BrandDNA; error?: string }> {
  const apiKey = process.env.DEEPSEEK_API_KEY
  if (!apiKey) return { ok: false, error: "no API key" }

  const prompt = [
    "あなたは企業データをブランドデザインパラメータに変換する分析エンジンです。",
    "テキストは出力しない。JSONの数値パラメータのみを出力せよ。",
    "",
    "== パラメータ定義 (すべて 0.0〜1.0) ==",
    "gravity: 堅牢さ・伝統・信頼感。高いほどセリフ体・広い余白・太字",
    "velocity: スピード感・緊急性・モダンさ。高いほど速いアニメ・タイトなレイアウト",
    "complexity: 情報密度。高いほど多カラム・多セクション",
    "warmth: 温かみ。高いほど暖色・角丸・ソフトシャドウ",
    "color_hue: 業種から導出するベース色相 (0-360)",
    "",
    "== 企業データ ==",
    `名前: ${company.name}`,
    `業種: ${company.industry || "不明"}`,
    `所在地: ${company.location || "不明"}`,
    `創業: ${company.founded || "不明"}`,
    `従業員: ${company.employeeCount || "不明"}人`,
    `評価: ${company.reviewRating || "?"}/5`,
    `概要: ${company.aboutText || ""}`,
    `サービス: ${(company.services || []).join(", ")}`,
    `課題: ${company.painSummary || ""}`,
    "",
    "上記からbrand_seed（一意の文字列）と6つの数値パラメータをJSONで出力せよ。",
    '{"brand_seed":"...", "gravity":0.X, "velocity":0.X, "complexity":0.X, "warmth":0.X, "color_hue":XXX,',
    ' "copy":{"headline":"...", "subheadline":"...", "sections":[{"title":"...","body":"..."}], "cta":"..."}}',
  ].join("\n")

  try {
    const res = await fetch(`${API}/chat/completions`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify({
        model: MODEL, messages: [{ role: "user", content: prompt }],
        temperature: 0.6, max_tokens: 1024,
        response_format: { type: "json_object" },
      }),
      signal: AbortSignal.timeout(30000),
    })
    const data = await res.json() as any
    const raw = data.choices?.[0]?.message?.content || ""
    const dna = JSON.parse(raw.replace(/```json\s*|\s*```/g, ""))
    
    // Validate ranges
    dna.gravity = Math.max(0, Math.min(1, Number(dna.gravity) || 0.5))
    dna.velocity = Math.max(0, Math.min(1, Number(dna.velocity) || 0.5))
    dna.complexity = Math.max(0, Math.min(1, Number(dna.complexity) || 0.5))
    dna.warmth = Math.max(0, Math.min(1, Number(dna.warmth) || 0.5))
    dna.color_hue = ((Number(dna.color_hue) || 210) % 360 + 360) % 360

    return { ok: true, dna }
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) }
  }
}

// ── Step 2: Compute procedural design tokens from BrandDNA ──

export function computeProceduralTokens(dna: BrandDNA): ProceduralTokens {
  const g = dna.gravity
  const v = dna.velocity
  const c = dna.complexity
  const w = dna.warmth
  const h = dna.color_hue

  // Typography
  const isSerif = g > 0.6
  const headingWeight = Math.round(400 + g * 500) // 400-900
  const headingSize = `clamp(${2 + g * 2}rem, ${4 + g * 4}vw, ${3 + g * 3}rem)`  // bigger for gravity
  const bodySize = `clamp(${0.85 + c * 0.15}rem, 1.1vw, ${1 + c * 0.1}rem)`  // bigger for complexity
  const letterSpacing = `${-0.04 + g * 0.02}em`  // tighter for high gravity

  // Colors — procedural palette from single hue
  const palette = computePalette(h, w)

  // Spacing
  const sectionPadding = `clamp(${2 + g * 3}rem, ${5 + g * 5}vw, ${4 + g * 4}rem)`
  const cardPadding = `${1 + g * 1}rem ${1 + c * 0.5}rem`
  const gap = `${1 + c * 0.5}rem`
  const containerMax = `${800 + c * 400}px`

  // Layout grid
  const columns = Math.round(1 + c * 3) // 1-4 columns
  const cardMinWidth = `${200 + c * 100}px`

  // Animation
  const duration = `${0.3 + v * 0.4}s`  // 0.3-0.7s
  const easing = v > 0.5 ? "cubic-bezier(0.22,1,0.36,1)" : "cubic-bezier(0.16,1,0.3,1)"
  const delay = `${0.05 + (1 - v) * 0.15}s`

  // Shader seed
  const shaderSeed = dna.brand_seed.split("").reduce((acc, ch) => acc + ch.charCodeAt(0), 0)

  return {
    css: {
      "--font-family": isSerif ? "'Noto Serif JP', 'Georgia', serif" : "'Inter', 'Space Grotesk', sans-serif",
      "--font-heading-weight": String(headingWeight),
      "--font-heading-size": headingSize,
      "--font-body-size": bodySize,
      "--letter-spacing": letterSpacing,
      "--color-primary": palette.primary,
      "--color-primary-light": palette.primaryLight,
      "--color-primary-dark": palette.primaryDark,
      "--color-bg": palette.background,
      "--color-surface": palette.surface,
      "--color-text": palette.text,
      "--color-text-muted": palette.textMuted,
      "--color-accent": palette.accent,
      "--color-border": palette.border,
      "--color-shadow": palette.shadow,
      "--section-padding": sectionPadding,
      "--card-padding": cardPadding,
      "--gap": gap,
      "--container-max": containerMax,
      "--radius": `${4 + w * 16}px`,  // 4-20px
      "--transition": `all ${duration} ${easing}`,
    },
    typography: { fontFamily: isSerif ? "'Noto Serif JP', serif" : "'Inter', sans-serif", headingWeight, bodySize, headingSize, letterSpacing },
    spacing: { sectionPadding, cardPadding, gap, containerMax },
    palette,
    layout: { heroColumns: columns > 1 ? `1fr ${columns - 1}fr` : "1fr", cardColumns: `repeat(auto-fit, minmax(${cardMinWidth}, 1fr))`, cardMinWidth },
    animation: { duration, easing, delay },
    shaderSeed,
  }
}

// ── Procedural color palette from single hue ──

function computePalette(hue: number, warmth: number): ProceduralTokens["palette"] {
  const hsl = (h: number, s: number, l: number) => `hsl(${h}, ${s}%, ${l}%)`
  
  const primaryHue = hue
  const accentHue = (hue + 30 + warmth * 30) % 360
  const bgHue = hue
  const saturation = 40 + warmth * 30

  return {
    primary: hsl(primaryHue, saturation, 45),
    primaryLight: hsl(primaryHue, saturation, 65),
    primaryDark: hsl(primaryHue, saturation, 25),
    background: hsl(bgHue, 10 + warmth * 20, 97 - warmth * 5),
    surface: hsl(bgHue, 5, 100),
    text: hsl(bgHue, 15, 10 + (1 - warmth) * 10),
    textMuted: hsl(bgHue, 10, 45),
    accent: hsl(accentHue, 60, 50),
    border: hsl(bgHue, 10, 85 + (1 - warmth) * 5),
    shadow: `0 ${4 + warmth * 8}px ${16 + warmth * 16}px rgba(0,0,0,${0.04 + warmth * 0.04})`,
  }
}

// ── Step 3: Generate complete HTML from BrandDNA + ProceduralTokens ──

export function generateProceduralHTML(dna: BrandDNA, tokens: ProceduralTokens): string {
  const p = tokens.palette
  const css = Object.entries(tokens.css).map(([k, v]) => `    ${k}: ${v};`).join("\n")

  const sections = dna.copy.sections.map((s, i) => `
    <section style="padding:var(--section-padding) 0;${i % 2 === 1 ? `background:${p.surface};` : ""}animation:fadeIn var(--transition) ${i * 0.1}s both">
      <div style="max-width:var(--container-max);margin:0 auto;padding:0 clamp(1rem,3vw,2rem)">
        <h2 style="font-family:var(--font-family);font-weight:var(--font-heading-weight);font-size:clamp(1.5rem,3vw,2.5rem);letter-spacing:var(--letter-spacing);margin-bottom:1rem;color:${p.text}">${s.title}</h2>
        <p style="font-size:var(--font-body-size);color:${p.textMuted};line-height:1.8;max-width:${tokens.layout.cardMinWidth}">${s.body}</p>
      </div>
    </section>`).join("\n")

  return `<!doctype html>
<html lang="ja">
<head>
<meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>${dna.copy.headline} — ${dna.brand_seed}</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=Noto+Serif+JP:wght@400;500;700;900&family=Space+Grotesk:wght@400;500;700&display=swap" rel="stylesheet">
<style>
:root {
${css}
}
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
body{font-family:var(--font-family);background:var(--color-bg);color:var(--color-text);line-height:1.7;-webkit-font-smoothing:antialiased;overflow-x:hidden}
h1,h2,h3{font-family:var(--font-family);font-weight:var(--font-heading-weight);letter-spacing:var(--letter-spacing);line-height:1.15}
a{color:var(--color-primary);text-decoration:none}
@keyframes fadeIn{from{opacity:0;transform:translateY(${tokens.animation.duration === "0.3s" ? "12px" : "24px"})}to{opacity:1;transform:translateY(0)}}
@keyframes shimmer{0%{background-position:-200% 0}100%{background-position:200% 0}}
</style>
</head>
<body>
<nav style="position:sticky;top:0;z-index:100;background:rgba(255,255,255,0.9);backdrop-filter:blur(16px);border-bottom:1px solid ${p.border};padding:0 clamp(1rem,4vw,2rem);height:64px;display:flex;align-items:center;justify-content:space-between">
  <strong style="font-size:1.1rem;letter-spacing:var(--letter-spacing)">${dna.brand_seed}</strong>
  <a href="#cta" style="padding:10px 24px;background:${p.primary};color:#fff;border-radius:var(--radius);font-weight:600;font-size:0.9rem">${dna.copy.cta}</a>
</nav>

<header style="display:flex;align-items:center;justify-content:center;min-height:${dna.gravity > 0.6 ? "90vh" : "70vh"};text-align:center;padding:var(--section-padding) clamp(1rem,3vw,2rem);${dna.gravity > 0.6 ? `background:linear-gradient(180deg,${p.primaryLight}08,${p.background});` : ""}animation:fadeIn var(--transition) both">
  <div style="max-width:700px">
    <h1 style="font-size:var(--font-heading-size);margin-bottom:1rem;color:${p.text}">${dna.copy.headline}</h1>
    <p style="font-size:${dna.complexity > 0.5 ? "var(--font-body-size)" : "clamp(1rem,1.5vw,1.25rem)"};color:${p.textMuted};margin-bottom:2rem;max-width:500px;margin-left:auto;margin-right:auto">${dna.copy.subheadline}</p>
    <a href="#cta" style="display:inline-flex;padding:14px 32px;background:${p.primary};color:#fff;border-radius:var(--radius);font-weight:600;font-size:1rem;text-decoration:none;box-shadow:${p.shadow};transition:var(--transition)">${dna.copy.cta}</a>
  </div>
</header>

${sections}

<footer id="cta" style="text-align:center;padding:var(--section-padding) clamp(1rem,3vw,2rem);background:${p.primaryDark};color:#fff">
  <h2 style="font-size:clamp(1.5rem,3vw,2.5rem);margin-bottom:1rem">${dna.copy.cta}</h2>
  <p style="opacity:0.8;margin-bottom:2rem;max-width:400px;margin-left:auto;margin-right:auto">${dna.copy.subheadline}</p>
  <a href="/contact" style="display:inline-flex;padding:16px 36px;background:#fff;color:${p.primaryDark};border-radius:var(--radius);font-weight:700;font-size:1rem;text-decoration:none">お問い合わせ</a>
  <div style="margin-top:3rem;opacity:0.4;font-size:0.8rem">&copy; ${new Date().getFullYear()} ${dna.brand_seed}</div>
</footer>
</body>
</html>`
}
