import { getServiceSalesSupabase } from "@/lib/supabase"
import { findCompanyByDomain, findCompanyById, findCompanyBySlug } from "./companies"
import { matchContentTemplate, type ContentAssetType } from "./content-templates"
import { fetchDiagnosticReport, type DiagnosticReportData } from "./diagnostic"
import { labelForIndustry, themeForIndustry } from "./render-quality"
import { normalizeReportLocale, type ReportLocale } from "./routing"
import { localeToRegion, type Region } from "./types"
import { DB_TABLES } from "@/lib/sales/db-tables"

export interface SalesAssetResult {
  ok: boolean
  asset_type: ContentAssetType
  company_name?: string
  content?: string
  content_template?: {
    title: string
    quality_bar: string
    dify_selection_rule: string
  }
  delivery_id?: string
  error?: string
}

const isUuid = (value: string): boolean =>
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value)

function deliveryTypeFor(assetType: ContentAssetType): string {
  if (assetType === "sales_video") return "動画ブリーフ"
  if (assetType === "astro_demo_site") return "Astroデモサイト"
  if (assetType === "sales_deck") return "提案資料"
  return "診断レポート"
}

function clean(value: string | null | undefined): string {
  return (value ?? "").replace(/\s+/g, " ").trim()
}

function slideEscape(value: string | null | undefined): string {
  return clean(value).replaceAll("\n", " ")
}

function deckMarkdown(report: DiagnosticReportData, templateTitle: string): string {
  const isJa = report.report_locale === "ja"
  const theme = themeForIndustry(report.industry)
  const industry = labelForIndustry(report.industry, report.report_locale)
  const actions = report.intelligence.nextActions.map((action) => `- ${slideEscape(action)}`).join("\n")
  const signals = report.intelligence.signals
    .slice(0, 6)
    .map((signal) => `- **${slideEscape(signal.label)}**: ${slideEscape(signal.value)} (${slideEscape(signal.source)})`)
    .join("\n")
  const pains = report.acts.map((act) => `- **${slideEscape(act.headline)}**: ${slideEscape(act.body)}`).join("\n")

  const copy = {
    subtitle: isJa ? "診断データから作成した、実行前提の提案資料" : "A proposal built from diagnostic evidence",
    takeaway: isJa ? "結論" : "Executive takeaway",
    monthlyLoss: isJa ? "推定月間機会損失" : "estimated monthly opportunity loss",
    sourceConfidence: isJa ? "データ取得信頼度" : "source confidence",
    priorityThemes: isJa ? "優先改善テーマ" : "priority themes",
    evidence: isJa ? "根拠データ" : "Evidence",
    painStructure: isJa ? "痛みの構造" : "Pain structure",
    demoAndReport: isJa ? "診断URLと差し替えデモ" : "Demo and report",
    report: isJa ? "診断レポート" : "Report",
    demo: isJa ? "Astro差し替えデモ" : "Astro replacement demo",
    notGenerated: isJa ? "未生成" : "Not generated yet",
    selectedTemplate: isJa ? "適用テンプレート" : "Selected template",
    proposal: isJa ? "提案" : "Proposal",
    qualityBar: isJa ? "テンプレート品質基準" : "Template quality bar",
    rollout: isJa ? "導入順序" : "Rollout",
    nextActions: isJa ? "次アクション" : "Next actions",
    step1: isJa ? "診断結果を確認し、改善優先度を決める" : "Review diagnostic findings and decide priorities",
    step2: isJa ? "Astro/Next.jsで差し替えデモを本番設計へ変換する" : "Convert the demo into production-ready Astro/Next.js design",
    step3: isJa ? "フォーム、予約、計測イベントを接続する" : "Connect forms, booking, and tracking events",
    step4: isJa ? "公開後7日で初期KPIを確認する" : "Review initial KPIs after seven days",
  }

  return `---
theme: seriph
title: ${report.company_name} Proposal
info: Generated by Paradigm Sales OS
class: text-left
drawings:
  persist: false
transition: slide-left
mdc: true
---

<style>
:root {
  --slidev-theme-primary: ${theme.accent};
  --pd-ink: ${theme.ink};
  --pd-muted: ${theme.muted};
  --pd-soft: ${theme.accentSoft};
}
.slidev-layout { color: var(--pd-ink); letter-spacing: 0; }
.slidev-layout h1 { font-size: 2.9rem; line-height: 1.05; letter-spacing: 0; }
.slidev-layout h2 { font-size: 2.1rem; letter-spacing: 0; }
.kpi { border: 1px solid #e5e7eb; border-radius: 8px; padding: 18px; background: #fff; }
.kpi b { font-size: 2rem; display: block; color: var(--slidev-theme-primary); }
.bar { height: 8px; border-radius: 999px; background: #e5e7eb; overflow: hidden; }
.bar span { display: block; height: 100%; background: var(--slidev-theme-primary); }
</style>

# ${report.company_name}

${copy.subtitle}

<div class="mt-8 text-sm opacity-70">${industry} / ${templateTitle}</div>

---

# ${copy.takeaway}

${report.hook}

<div class="grid grid-cols-3 gap-4 mt-8">
  <div class="kpi"><b>${report.total_loss}</b><span>${copy.monthlyLoss}</span></div>
  <div class="kpi"><b>${report.source_coverage.score}%</b><span>${copy.sourceConfidence}</span></div>
  <div class="kpi"><b>${report.acts.length}</b><span>${copy.priorityThemes}</span></div>
</div>

---

# ${copy.evidence}

${signals}

<div class="bar mt-8"><span style="width:${report.source_coverage.score}%"></span></div>

---

# ${copy.painStructure}

${pains}

---

# ${copy.demoAndReport}

- ${copy.report}: ${report.report_url}
- ${copy.demo}: ${report.demo_url ?? copy.notGenerated}
- ${copy.selectedTemplate}: ${templateTitle}

---

# ${copy.proposal}

${report.cta_text}

${copy.qualityBar}:
${report.content_template.quality_bar}

---

# ${copy.rollout}

1. ${copy.step1}
2. ${copy.step2}
3. ${copy.step3}
4. ${copy.step4}

---

# ${copy.nextActions}

${actions}
`
}

function videoBrief(report: DiagnosticReportData, templateTitle: string): string {
  const isJa = report.report_locale === "ja"
  const theme = themeForIndustry(report.industry)
  return JSON.stringify(
    {
      title: `${report.company_name} diagnostic sales video`,
      renderer: "HyperFrames / Remotion compatible",
      template: templateTitle,
      language: report.report_locale,
      duration_sec: 60,
      visual_theme: {
        accent: theme.accent,
        accent_dark: theme.accentDark,
        paper: theme.paper,
        tone: isJa
          ? "落ち着いた経営者向け。煽らず、根拠と改善後の姿を見せる。"
          : "Executive, calm, evidence-first.",
      },
      toolchain: ["Dify Cloud", "DeepSeek V4", "ComfyUI", "HyperFrames", "Remotion", "Faster Whisper", "Cloudflare R2"],
      scenes: [
        {
          id: "hook",
          seconds: 8,
          caption: report.hook,
          visual: "Clean headline over measured website evidence, subtle cursor scan.",
        },
        {
          id: "evidence",
          seconds: 14,
          caption: report.acts[0]?.headline,
          visual: "Metric card with PageSpeed/source data, no exaggerated warning effects.",
        },
        {
          id: "business_impact",
          seconds: 14,
          caption: report.total_loss,
          visual: "Opportunity loss counter and three objective evidence chips.",
        },
        {
          id: "solution",
          seconds: 16,
          caption: report.cta_text,
          visual: "Before-to-after website layout reveal, Astro demo preview, CTA path.",
        },
        {
          id: "cta",
          seconds: 8,
          caption: report.report_url,
          visual: "Simple booking CTA with report and demo URLs.",
        },
      ],
      comfyui_prompts: [
        "Modern business website mockup, clean executive design, realistic browser frame, no fake logos",
        "Subtle motion background for sales diagnostic video, professional, high trust, no stock-photo cliche",
      ],
      safety: {
        no_unavailable_evidence: true,
        keep_urls_exact: true,
        human_review_before_live_send: true,
      },
    },
    null,
    2,
  )
}

function reportJson(report: DiagnosticReportData): string {
  return JSON.stringify(
    {
      company_name: report.company_name,
      locale: report.report_locale,
      template: report.content_template,
      hook: report.hook,
      acts: report.acts,
      source_coverage: report.source_coverage,
      intelligence: report.intelligence,
      report_url: report.report_url,
      demo_url: report.demo_url,
      screenshot_url: report.screenshot_url ?? null,
      screenshot_mobile_url: report.screenshot_mobile_url ?? null,
      evidence_screenshot_url: report.evidence_screenshot_url ?? null,
      evidence_screenshot_kind: report.evidence_screenshot_kind ?? null,
      visual_annotations: report.visual_annotations ?? [],
      improvement_preview: report.improvement_preview ?? null,
      visitor_journey: report.visitor_journey ?? [],
      renderer: "Next.js professional report v2",
    },
    null,
    2,
  )
}

function astroBrief(report: DiagnosticReportData, templateTitle: string): string {
  const theme = themeForIndustry(report.industry)
  return JSON.stringify(
    {
      title: `${report.company_name} Astro replacement demo`,
      template: templateTitle,
      renderer: "Astro professional demo v2",
      theme,
      sections: ["hero", "proof_bar", "service_cards", "case_preview", "booking_cta"],
      copy_inputs: {
        hook: report.hook,
        cta: report.cta_text,
        pains: report.acts.map((act) => act.headline),
        report_url: report.report_url,
        source_confidence: report.source_coverage.score,
      },
      quality_bar: "Mobile first, no generic hero, visible difference from current site, trust proof and CTA in first viewport.",
    },
    null,
    2,
  )
}

async function saveDelivery(input: {
  companyId: string
  companyName: string
  assetType: ContentAssetType
  content: string
  templateTitle: string
  region: Region
  reportLocale: ReportLocale
  targetCountry: string
}): Promise<string | undefined> {
  const sb = getServiceSalesSupabase()
  if (!sb) return undefined

  const { data, error } = await sb
    .from(DB_TABLES.SALES_DELIVERIES)
    .insert({
      region: input.region,
      delivery_name: `${input.companyName} ${input.templateTitle}`,
      delivery_type: deliveryTypeFor(input.assetType),
      status: "レビュー待ち",
      created_by: "sales-os",
      meta: {
        company_id: input.companyId,
        asset_type: input.assetType,
        generated_content: input.content,
        template_title: input.templateTitle,
        report_locale: input.reportLocale,
        target_country: input.targetCountry,
        renderer_version: "professional-v2",
      },
    })
    .select("id")
    .single()

  if (error) {
    console.error("[sales-assets] delivery insert failed:", error.message)
    return undefined
  }
  return typeof data?.id === "string" ? data.id : undefined
}

export async function generateSalesAsset(input: {
  companyIdOrSlugOrDomain: string
  assetType: ContentAssetType
  reportLocale?: string | null
}): Promise<SalesAssetResult> {
  const requestedLocale = input.reportLocale ? normalizeReportLocale(input.reportLocale, "jp") : null
  const requestedRegion = requestedLocale ? localeToRegion(requestedLocale) : "jp"
  const company = isUuid(input.companyIdOrSlugOrDomain)
    ? await findCompanyById(input.companyIdOrSlugOrDomain)
    : input.companyIdOrSlugOrDomain.includes(".")
      ? await findCompanyByDomain(input.companyIdOrSlugOrDomain)
      : await findCompanyBySlug(input.companyIdOrSlugOrDomain, requestedRegion)

  if (!company) return { ok: false, asset_type: input.assetType, error: "company not found" }

  const report = await fetchDiagnosticReport({
    companyId: company.id,
    reportLocale: requestedLocale ?? company.report_locale ?? undefined,
  })
  if (!report) return { ok: false, asset_type: input.assetType, error: "diagnostic report unavailable" }

  const contentTemplate = await matchContentTemplate({
    reportLocale: report.report_locale,
    targetCountry: report.target_country,
    industry: report.industry,
    assetType: input.assetType,
    templateVariant: report.template_variant,
  })

  const content =
    input.assetType === "sales_deck"
      ? deckMarkdown(report, contentTemplate.title)
      : input.assetType === "sales_video"
        ? videoBrief(report, contentTemplate.title)
        : input.assetType === "astro_demo_site"
          ? astroBrief(report, contentTemplate.title)
          : reportJson(report)

  const deliveryId = await saveDelivery({
    companyId: company.id,
    companyName: company.company_name,
    assetType: input.assetType,
    content,
    templateTitle: contentTemplate.title,
    region: localeToRegion(report.report_locale),
    reportLocale: report.report_locale,
    targetCountry: report.target_country,
  })

  return {
    ok: true,
    asset_type: input.assetType,
    company_name: company.company_name,
    content,
    delivery_id: deliveryId,
    content_template: {
      title: contentTemplate.title,
      quality_bar: contentTemplate.quality_bar,
      dify_selection_rule: contentTemplate.dify_selection_rule,
    },
  }
}
