import type { RevenueSourceRegistryItem } from "./source-registry-types"

function item(input: RevenueSourceRegistryItem): RevenueSourceRegistryItem {
  return input
}

export const REVENUE_SOURCE_REGISTRY_CORE: RevenueSourceRegistryItem[] = [
  item({
    slug: "passive_inventory",
    label: "Passive internet inventory",
    category: "list",
    lane: "tech_footprint",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "bulk",
    env: ["PASSIVE_DOMAIN_FEED_DIR", "PASSIVE_DOMAIN_FEED_URLS", "CZDS_ZONE_FILE_DIR", "CZDS_USERNAME", "CZDS_PASSWORD", "MASSDNS_BIN"],
    primaryInput: "approved zone/domain feeds and CNAME records",
    primaryOutput: "stack-matched and geo-matched candidate domains without visiting target websites",
    notes: "Secondary inventory only. Production promotion requires an evidence-bearing company source record before DNS or site verification.",
  }),
  item({
    slug: "multi_source_domains",
    label: "Multi-source domain acquisition",
    category: "list",
    lane: "tech_footprint",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "bulk",
    env: [],
    primaryInput: "operator-approved official and industry source records",
    primaryOutput: "deduplicated company identities with source-page provenance",
    notes: "Production candidate runs fail closed unless company name, domain, target country, and source page are stored before site verification.",
  }),
  item({
    slug: "common_crawl",
    label: "Common Crawl per-domain evidence",
    category: "analysis",
    lane: "enrichment",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: [],
    primaryInput: "domain",
    primaryOutput: "pages in index and last crawl timestamp",
    notes: "Called from enrich.ts for known domains.",
  }),
  item({
    slug: "crtsh",
    label: "crt.sh certificate transparency",
    category: "analysis",
    lane: "tech_footprint",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: [],
    primaryInput: "domain",
    primaryOutput: "certificate and subdomain evidence",
    notes: "Called from enrich.ts. Also useful for discovering newly observed domains.",
  }),
  item({
    slug: "wappalyzer_local",
    label: "Local Wappalyzer-style detector",
    category: "analysis",
    lane: "tech_footprint",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: [],
    primaryInput: "homepage HTML and headers",
    primaryOutput: "technology stack detections",
    notes: "Implemented with local signatures in sources/wappalyzer.ts. This is not Wappalyzer CLI.",
  }),
  item({
    slug: "schema_org",
    label: "schema.org extraction",
    category: "analysis",
    lane: "tech_footprint",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: [],
    primaryInput: "URL",
    primaryOutput: "organization, local business, address, phone signals",
    notes: "Called from enrich.ts and important for country/name confidence.",
  }),
  item({
    slug: "sitemap",
    label: "Sitemap analysis",
    category: "analysis",
    lane: "tech_footprint",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: [],
    primaryInput: "domain",
    primaryOutput: "public URL inventory",
    notes: "Called from enrich.ts.",
  }),
  item({
    slug: "html_metadata",
    label: "HTML metadata scan",
    category: "analysis",
    lane: "tech_footprint",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: [],
    primaryInput: "homepage URL",
    primaryOutput: "title, description, OGP, canonical, form count",
    notes: "Part of scanDomain. Some scanner outputs still need cleaner meta persistence.",
  }),
  item({
    slug: "pagespeed",
    label: "PageSpeed Insights / Lighthouse",
    category: "analysis",
    lane: "enrichment",
    cost: "free_with_limits",
    implementationStatus: "live_if_configured",
    scaleTier: "per_domain_deep",
    env: ["GOOGLE_PSI_API_KEY"],
    primaryInput: "URL",
    primaryOutput: "mobile and desktop performance scores",
    notes: "scanDomain calls the PageSpeed client; practical bulk usage needs quota control.",
  }),
  item({
    slug: "dns_doh",
    label: "DNS over HTTPS",
    category: "analysis",
    lane: "enrichment",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: [],
    primaryInput: "domain",
    primaryOutput: "MX, SPF, DMARC, email provider, DNSSEC",
    notes: "Called from enrich.ts.",
  }),
  item({
    slug: "ssllabs",
    label: "SSL Labs",
    category: "analysis",
    lane: "enrichment",
    cost: "free_with_limits",
    implementationStatus: "live",
    scaleTier: "per_domain_deep",
    env: [],
    primaryInput: "domain",
    primaryOutput: "TLS grade and certificate risk",
    notes: "Called from enrich.ts. Should not be run across every raw candidate.",
  }),
  item({
    slug: "hsts_preload",
    label: "HSTS preload",
    category: "analysis",
    lane: "enrichment",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: [],
    primaryInput: "domain",
    primaryOutput: "HSTS preload status",
    notes: "Called from enrich.ts.",
  }),
  item({
    slug: "mozilla_observatory",
    label: "Mozilla Observatory",
    category: "analysis",
    lane: "enrichment",
    cost: "free_with_limits",
    implementationStatus: "live",
    scaleTier: "per_domain_deep",
    env: ["MOZILLA_OBSERVATORY_API_URL"],
    primaryInput: "domain",
    primaryOutput: "security header score",
    notes: "Called from enrich.ts. The env is optional in source coverage but health can be configured.",
  }),
  item({
    slug: "whois",
    label: "WHOIS / RDAP",
    category: "analysis",
    lane: "enrichment",
    cost: "free_with_limits",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: [],
    primaryInput: "domain",
    primaryOutput: "registration and registrar signals",
    notes: "Called from enrich.ts.",
  }),
  item({
    slug: "wayback_machine",
    label: "Wayback Machine",
    category: "analysis",
    lane: "enrichment",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: [],
    primaryInput: "domain",
    primaryOutput: "historical presence and first/last snapshots",
    notes: "Called from enrich.ts.",
  }),
  item({
    slug: "tranco",
    label: "Tranco",
    category: "analysis",
    lane: "enrichment",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: [],
    primaryInput: "domain",
    primaryOutput: "rank signal",
    notes: "Called from enrich.ts.",
  }),
  item({
    slug: "open_corporates",
    label: "OpenCorporates",
    category: "list",
    lane: "enrichment",
    cost: "free_with_limits",
    implementationStatus: "live",
    scaleTier: "per_domain_deep",
    env: [],
    primaryInput: "domain-derived company name",
    primaryOutput: "registry candidates",
    notes: "Called from enrich.ts. Free quota is small and SMB coverage is weak.",
  }),
  item({
    slug: "gbizinfo",
    label: "gBizInfo",
    category: "list",
    lane: "enrichment",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "per_domain_deep",
    env: [],
    primaryInput: "company name",
    primaryOutput: "Japan registry facts",
    notes: "Called from enrich.ts. Japan-only.",
  }),
  item({
    slug: "github_rest",
    label: "GitHub REST",
    category: "analysis",
    lane: "enrichment",
    cost: "free_with_limits",
    implementationStatus: "live",
    scaleTier: "per_domain_deep",
    env: ["GITHUB_TOKEN"],
    primaryInput: "domain or org name",
    primaryOutput: "public engineering activity",
    notes: "Called from enrich.ts. More useful for tech companies than local SMBs.",
  }),
  item({
    slug: "spiderfoot",
    label: "SpiderFoot",
    category: "analysis",
    lane: "enrichment",
    cost: "env_required",
    implementationStatus: "live_if_configured",
    scaleTier: "per_domain_deep",
    env: ["SPIDERFOOT_API_URL"],
    primaryInput: "domain",
    primaryOutput: "OSINT scan and fallback DNS/CT/RDAP data",
    notes: "Called from enrich.ts. Falls back to public APIs when the worker is unreachable.",
  }),
  item({
    slug: "katana",
    label: "Katana",
    category: "analysis",
    lane: "enrichment",
    cost: "env_required",
    implementationStatus: "live_if_configured",
    scaleTier: "per_domain_deep",
    env: ["KATANA_API_URL"],
    primaryInput: "URL",
    primaryOutput: "crawled URLs",
    notes: "Called from enrich.ts. Falls back to URLscan/Common Crawl/direct URL list.",
  }),
  item({
    slug: "maigret",
    label: "Maigret",
    category: "analysis",
    lane: "enrichment",
    cost: "env_required",
    implementationStatus: "live_if_configured",
    scaleTier: "per_domain_deep",
    env: ["MAIGRET_API_URL"],
    primaryInput: "domain-derived username",
    primaryOutput: "public profile candidates",
    notes: "Called from enrich.ts. Precision for SMBs is limited.",
  }),
  item({
    slug: "form_discovery_http",
    label: "HTTP form discovery",
    category: "outreach",
    lane: "outreach",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: [],
    primaryInput: "homepage URL",
    primaryOutput: "contact form URL candidates",
    notes: "Main current form URL lane: homepage anchors, sitemap, common paths, optional LLM.",
  }),
  item({
    slug: "crawl4ai",
    label: "Crawl4AI form discovery",
    category: "outreach",
    lane: "outreach",
    cost: "env_required",
    implementationStatus: "live_if_configured",
    scaleTier: "browser_expensive",
    env: ["CRAWL4AI_BASE_URL"],
    primaryInput: "origin URL",
    primaryOutput: "contact form URL candidates",
    notes: "Directly wired into discoverFormUrl when configured.",
  }),
  item({
    slug: "crawlee",
    label: "Crawlee worker",
    category: "outreach",
    lane: "outreach",
    cost: "env_required",
    implementationStatus: "partial",
    scaleTier: "browser_expensive",
    env: ["CRAWLEE_WORKER_URL"],
    primaryInput: "URL",
    primaryOutput: "page text, links, form count",
    notes: "Called from enrich.ts for extraction, but not yet a first-class form URL decision source.",
  }),
  item({
    slug: "whoxy",
    label: "Whoxy API WHOIS",
    category: "list",
    lane: "enrichment",
    cost: "free_with_limits",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: ["WHOXY_API_KEY"],
    primaryInput: "domain",
    primaryOutput: "company name, registrant country, email, registrar, creation/expiry date",
    notes: "Free tier returns company + country for millions of domains. Newly registered domains are high-signal SMB candidates.",
  }),
  item({
    slug: "country_nic",
    label: "Country NIC RDAP",
    category: "list",
    lane: "enrichment",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: [],
    primaryInput: "domain + country code",
    primaryOutput: "registrar, creation date, organization name from official NIC",
    notes: "UK (.uk 10M), AU (.au 4M), JP (.jp 1.7M), DE (.de), CA (.ca), US (.us). Official registries via RDAP — no API key, lenient bot limits.",
  }),
  item({
    slug: "manta",
    label: "Manta.com SMB Directory",
    category: "list",
    lane: "no_website_local_smb",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "bulk",
    env: [],
    primaryInput: "category + location",
    primaryOutput: "US SMB names, categories, locations, employee counts (<10)",
    notes: "US small business directory focused on <10 employee companies. No large enterprises listed. Category-based bulk search.",
  }),
  item({
    slug: "bbb",
    label: "BBB.org Local Business",
    category: "list",
    lane: "no_website_local_smb",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "bulk",
    env: [],
    primaryInput: "category + location",
    primaryOutput: "US/CA SMB names, ratings, years in business, accreditation",
    notes: "Better Business Bureau directory. Long-established local businesses (plumbers, painters, lawyers, dentists). No API — public search.",
  }),
  item({
    slug: "hello_work",
    label: "Hello Work Job Postings",
    category: "list",
    lane: "no_website_local_smb",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "bulk",
    env: [],
    primaryInput: "industry + prefecture (Japan)",
    primaryOutput: "Japan SMB names, industries, prefectures, job categories",
    notes: "Companies posting jobs on Hello Work have hiring budget but often lack websites. Japan-only. 5 prefectures × 8 industries = 40 search combinations.",
  }),
  item({
    slug: "smb_purification",
    label: "SMB Purification Pipeline",
    category: "orchestration",
    lane: "tech_footprint",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "bulk",
    env: ["CRAWL4AI_BASE_URL"],
    primaryInput: "country code + TLDs",
    primaryOutput: "scored SMB candidate domains with tech stack and renovation signals",
    notes: "3-stage: CZDS zone → enterprise exclusion → Crawl4AI fast scan → Wappalyzer deep. Filters 200M domains to 2-3M renovation candidates.",
  }),
]
