import type { RevenueSourceRegistryItem } from "./source-registry-types"

function item(input: RevenueSourceRegistryItem): RevenueSourceRegistryItem {
  return input
}

export const REVENUE_SOURCE_REGISTRY_OPS: RevenueSourceRegistryItem[] = [
  item({
    slug: "stagehand",
    label: "Stagehand",
    category: "outreach",
    lane: "outreach",
    cost: "env_required",
    implementationStatus: "implemented_not_wired",
    scaleTier: "browser_expensive",
    env: ["STAGEHAND_ENABLED", "STAGEHAND_URL", "STAGEHAND_API_KEY"],
    primaryInput: "URL",
    primaryOutput: "browser-extracted site data and forms",
    notes: "Code exists, but the SDK package is not in package.json and the core path is gated by STAGEHAND_ENABLED.",
  }),
  item({
    slug: "steel",
    label: "Steel.dev",
    category: "outreach",
    lane: "outreach",
    cost: "env_required",
    implementationStatus: "live_if_configured",
    scaleTier: "browser_expensive",
    env: ["STEEL_BASE_URL"],
    primaryInput: "URL",
    primaryOutput: "text, links, metadata, screenshots",
    notes: "Called from enrich.ts and browser-search fallback. Heavy, not a bulk acquisition primitive.",
  }),
  item({
    slug: "browser_search",
    label: "Browser search",
    category: "list",
    lane: "tech_footprint",
    cost: "env_required",
    implementationStatus: "partial",
    scaleTier: "browser_expensive",
    env: ["FLARESOLVERR_URL", "STEEL_BASE_URL"],
    primaryInput: "search query",
    primaryOutput: "candidate domains",
    notes: "Implemented, but should be fallback/verification only because search engines block bulk collection.",
  }),
  item({
    slug: "whoogle",
    label: "Whoogle",
    category: "list",
    lane: "tech_footprint",
    cost: "env_required",
    implementationStatus: "implemented_not_wired",
    scaleTier: "browser_expensive",
    env: ["WHOOGLE_BASE_URL"],
    primaryInput: "search query",
    primaryOutput: "candidate domains",
    notes: "Lead discovery code exists, but search dependency makes it a fallback only.",
  }),
  item({
    slug: "overpass",
    label: "Overpass API",
    category: "list",
    lane: "no_website_local_smb",
    cost: "free",
    implementationStatus: "implemented_not_wired",
    scaleTier: "bulk",
    env: ["OVERPASS_API_URL"],
    primaryInput: "local business query",
    primaryOutput: "business listings with website tags",
    notes: "Useful for some local SMBs, but coverage is too low to be the global primary source.",
  }),
  item({
    slug: "whoisds_nrd",
    label: "WhoisDS newly registered domains",
    category: "list",
    lane: "tech_footprint",
    cost: "env_required",
    implementationStatus: "implemented_not_wired",
    scaleTier: "bulk",
    env: ["WHOISDS_NRD_URL"],
    primaryInput: "NRD feed URL",
    primaryOutput: "fresh candidate domains",
    notes: "Lead discovery code exists and can feed the tech-footprint candidate table.",
  }),
  item({
    slug: "rsshub_jobs",
    label: "RSSHub jobs",
    category: "list",
    lane: "no_website_local_smb",
    cost: "env_required",
    implementationStatus: "implemented_not_wired",
    scaleTier: "bulk",
    env: ["RSSHUB_BASE_URL", "RSSHUB_JOB_ROUTE_TEMPLATE"],
    primaryInput: "job query",
    primaryOutput: "hiring signal candidates",
    notes: "Secondary signal source for budget/timing.",
  }),
  item({
    slug: "directory_presets",
    label: "Agency, partner and events directories",
    category: "list",
    lane: "no_website_local_smb",
    cost: "free_with_limits",
    implementationStatus: "implemented_not_wired",
    scaleTier: "manual",
    env: [],
    primaryInput: "industry and region query",
    primaryOutput: "directory listing candidates",
    notes: "Current code routes many presets through search. Needs non-search adapters for stable bulk use.",
  }),
  item({
    slug: "builtwith_free",
    label: "BuiltWith free page lookup",
    category: "analysis",
    lane: "enrichment",
    cost: "free_with_limits",
    implementationStatus: "partial",
    scaleTier: "per_domain_deep",
    env: [],
    primaryInput: "domain",
    primaryOutput: "technology hints from BuiltWith public page",
    notes: "Called from enrich.ts. Not reliable for bulk extraction and should not be a primary source.",
  }),
  item({
    slug: "jina_reader",
    label: "Jina Reader",
    category: "analysis",
    lane: "enrichment",
    cost: "free_with_limits",
    implementationStatus: "live",
    scaleTier: "per_domain_deep",
    env: [],
    primaryInput: "URL",
    primaryOutput: "readable markdown and title",
    notes: "Called from enrich.ts for deep content evidence.",
  }),
  item({
    slug: "green_web",
    label: "Green Web Foundation",
    category: "analysis",
    lane: "enrichment",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: [],
    primaryInput: "domain",
    primaryOutput: "green hosting signal",
    notes: "Called from enrich.ts. Coverage detection key needs alignment.",
  }),
  item({
    slug: "safe_browsing",
    label: "Google Safe Browsing",
    category: "analysis",
    lane: "enrichment",
    cost: "env_required",
    implementationStatus: "live_if_configured",
    scaleTier: "per_domain_light",
    env: ["GOOGLE_SAFE_BROWSING_API_KEY"],
    primaryInput: "domain",
    primaryOutput: "malware/phishing safety signal",
    notes: "Called from enrich.ts; returns configured=false when no key exists.",
  }),
  item({
    slug: "emailrep",
    label: "EmailRep",
    category: "analysis",
    lane: "enrichment",
    cost: "free_with_limits",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: [],
    primaryInput: "domain or email",
    primaryOutput: "reputation signal",
    notes: "Called from enrich.ts. Coverage detection key needs alignment.",
  }),
  item({
    slug: "cloudflare_radar",
    label: "Cloudflare Radar",
    category: "analysis",
    lane: "enrichment",
    cost: "env_required",
    implementationStatus: "live_if_configured",
    scaleTier: "per_domain_light",
    env: ["CLOUDFLARE_API_TOKEN"],
    primaryInput: "domain",
    primaryOutput: "traffic/category context",
    notes: "Called from enrich.ts.",
  }),
  item({
    slug: "subfinder",
    label: "Subfinder",
    category: "analysis",
    lane: "enrichment",
    cost: "env_required",
    implementationStatus: "live_if_configured",
    scaleTier: "per_domain_deep",
    env: ["SUBFINDER_BIN"],
    primaryInput: "domain",
    primaryOutput: "passive subdomains",
    notes: "Called from enrich.ts.",
  }),
  item({
    slug: "trufflehog",
    label: "TruffleHog public repo scan",
    category: "analysis",
    lane: "enrichment",
    cost: "free_with_limits",
    implementationStatus: "live",
    scaleTier: "per_domain_deep",
    env: [],
    primaryInput: "domain",
    primaryOutput: "public secret exposure hints",
    notes: "Called from enrich.ts.",
  }),
  item({
    slug: "smb_signals",
    label: "SMB signals",
    category: "analysis",
    lane: "enrichment",
    cost: "free_with_limits",
    implementationStatus: "partial",
    scaleTier: "per_domain_deep",
    env: [],
    primaryInput: "domain, tech stack, MX records",
    primaryOutput: "maturity and visit range estimate",
    notes: "Called from enrich.ts, but includes Google search and should be reworked before bulk use.",
  }),
  item({
    slug: "market_data",
    label: "Market data",
    category: "analysis",
    lane: "enrichment",
    cost: "internal",
    implementationStatus: "live",
    scaleTier: "per_domain_light",
    env: [],
    primaryInput: "industry",
    primaryOutput: "industry benchmark context",
    notes: "Static/internal market data is added during enrichment when industry is known.",
  }),
  item({
    slug: "dify",
    label: "Dify diagnosis",
    category: "orchestration",
    lane: "orchestration",
    cost: "env_required",
    implementationStatus: "live_if_configured",
    scaleTier: "post_lead",
    env: ["DIFY_API_KEY"],
    primaryInput: "enriched company",
    primaryOutput: "pain diagnosis and report content",
    notes: "Used after candidate promotion, not for bulk acquisition.",
  }),
  item({
    slug: "deepseek",
    label: "DeepSeek personalization",
    category: "orchestration",
    lane: "orchestration",
    cost: "env_required",
    implementationStatus: "live_if_configured",
    scaleTier: "post_lead",
    env: ["DEEPSEEK_API_KEY"],
    primaryInput: "company and evidence",
    primaryOutput: "personalized copy",
    notes: "Used for personalized hooks/copy.",
  }),
  item({
    slug: "trigger_dev",
    label: "Trigger.dev",
    category: "orchestration",
    lane: "orchestration",
    cost: "env_required",
    implementationStatus: "live_if_configured",
    scaleTier: "post_lead",
    env: ["TRIGGER_SECRET_KEY", "TRIGGER_ACCESS_TOKEN", "TRIGGER_DEV_API_KEY"],
    primaryInput: "queued job",
    primaryOutput: "durable enrichment execution",
    notes: "Orchestrator, not a data source.",
  }),
  item({
    slug: "twenty",
    label: "Twenty CRM",
    category: "orchestration",
    lane: "orchestration",
    cost: "env_required",
    implementationStatus: "live_if_configured",
    scaleTier: "post_lead",
    env: ["TWENTY_BASE_URL", "TWENTY_API_KEY"],
    primaryInput: "promoted sales company",
    primaryOutput: "CRM company/contact sync",
    notes: "CRM mirror. Supabase remains SSOT.",
  }),
  item({
    slug: "google_places",
    label: "Google Places",
    category: "list",
    lane: "disabled",
    cost: "disabled_by_policy",
    implementationStatus: "disabled_by_policy",
    scaleTier: "manual",
    env: ["GOOGLE_PLACES_API_KEY"],
    primaryInput: "local query",
    primaryOutput: "place listing",
    notes: "Paid API. Disabled for this free-first list acquisition direction.",
  }),
  item({
    slug: "apollo",
    label: "Apollo",
    category: "list",
    lane: "disabled",
    cost: "disabled_by_policy",
    implementationStatus: "disabled_by_policy",
    scaleTier: "manual",
    env: ["APOLLO_API_KEY"],
    primaryInput: "company/person query",
    primaryOutput: "B2B company/contact data",
    notes: "Paid list/contact source. Disabled by policy for this project direction.",
  }),
  item({
    slug: "hunter_snov",
    label: "Hunter / Snov",
    category: "list",
    lane: "disabled",
    cost: "disabled_by_policy",
    implementationStatus: "disabled_by_policy",
    scaleTier: "manual",
    env: ["HUNTER_API_KEY", "SNOV_CLIENT_ID", "SNOV_CLIENT_SECRET"],
    primaryInput: "domain",
    primaryOutput: "email contacts",
    notes: "Paid contact discovery. Disabled by policy for list acquisition.",
  }),
  item({
    slug: "serp_tavily",
    label: "SerpAPI / Tavily",
    category: "analysis",
    lane: "disabled",
    cost: "disabled_by_policy",
    implementationStatus: "disabled_by_policy",
    scaleTier: "manual",
    env: ["SERPAPI_API_KEY", "TAVILY_API_KEY"],
    primaryInput: "search query",
    primaryOutput: "search evidence",
    notes: "Paid search APIs. Disabled by policy.",
  }),
  item({
    slug: "storeleads_cartleads",
    label: "StoreLeads / CartLeads",
    category: "list",
    lane: "disabled",
    cost: "disabled_by_policy",
    implementationStatus: "disabled_by_policy",
    scaleTier: "manual",
    env: ["STORELEADS_API_KEY", "CARTLEADS_API_KEY"],
    primaryInput: "technology or domain query",
    primaryOutput: "ecommerce store list",
    notes: "Paid BuiltWith-like sources. Disabled by policy.",
  }),
  item({
    slug: "dataforseo",
    label: "DataForSEO",
    category: "analysis",
    lane: "disabled",
    cost: "disabled_by_policy",
    implementationStatus: "disabled_by_policy",
    scaleTier: "manual",
    env: ["DATAFORSEO_LOGIN", "DATAFORSEO_PASSWORD"],
    primaryInput: "domain or keyword",
    primaryOutput: "SEO/lighthouse/search data",
    notes: "Paid API. Not part of the free-first acquisition system.",
  }),
  item({
    slug: "shodan_censys_securitytrails",
    label: "Shodan / Censys / SecurityTrails",
    category: "analysis",
    lane: "enrichment",
    cost: "paid",
    implementationStatus: "catalog_only",
    scaleTier: "per_domain_deep",
    env: ["SHODAN_API_KEY", "CENSYS_API_ID", "SECURITYTRAILS_API_KEY"],
    primaryInput: "domain or IP",
    primaryOutput: "exposure and infra history",
    notes: "Cataloged and health-checkable, but not a core free acquisition path.",
  }),
  item({
    slug: "no_website_directories",
    label: "No-website local SMB directories",
    category: "list",
    lane: "no_website_local_smb",
    cost: "free_with_limits",
    implementationStatus: "catalog_only",
    scaleTier: "bulk",
    env: [],
    primaryInput: "country, region, category, directory adapter",
    primaryOutput: "business listings without official website evidence",
    notes: "Target architecture for HP-less SMB proposals. Needs dedicated adapters beyond search presets.",
  }),
  item({
    slug: "ct_log_bulk",
    label: "crt.sh bulk certificate transparency",
    category: "list",
    lane: "tech_footprint",
    cost: "free",
    implementationStatus: "live",
    scaleTier: "bulk",
    env: [],
    primaryInput: "TLD pattern",
    primaryOutput: "certificate-observed candidate domains",
    notes: "Wired into the production multi-source candidate runner through sources/crtsh-bulk.ts.",
  }),
  item({
    slug: "http_archive",
    label: "HTTP Archive",
    category: "list",
    lane: "tech_footprint",
    cost: "free_with_limits",
    implementationStatus: "catalog_only",
    scaleTier: "bulk",
    env: ["HTTPARCHIVE_BIGQUERY_PROJECT_ID"],
    primaryInput: "BigQuery technology/signature query",
    primaryOutput: "technology-filtered origin list",
    notes: "Good future bulk source for stack-level extraction when BigQuery is available.",
  })
]
