/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    posts: Post;
    services: Service;
    faqs: Faq;
    works: Work;
    pricing: Pricing;
    leads: Lead;
    media: Media;
    'audit-logs': AuditLog;
    pages: Page;
    'team-members': TeamMember;
    testimonials: Testimonial;
    categories: Category;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('ja' | 'en' | 'ko' | 'zh' | 'de' | 'fr' | 'es' | 'pt' | 'ru' | 'ar' | 'vi' | 'id')
    | ('ja' | 'en' | 'ko' | 'zh' | 'de' | 'fr' | 'es' | 'pt' | 'ru' | 'ar' | 'vi' | 'id')[];
  globals: {
    settings: Setting;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'ja' | 'en' | 'ko' | 'zh' | 'de' | 'fr' | 'es' | 'pt' | 'ru' | 'ar' | 'vi' | 'id';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * CMSユーザー管理（admin=全権 / editor=編集 / viewer=閲覧のみ）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * admin=全権 / editor=本番データ作成更新 / viewer=読み取りのみ
   */
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * ブログ記事の管理（日本語・英語）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URLに使用される識別子。英数字とハイフンのみ
   */
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  category?: string | null;
  readTime?: string | null;
  /**
   * Categories から選択。設定すると上の自由テキスト category より優先表示されます。
   */
  categoryRef?: (number | null) | Category;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  /**
   * この記事を表示するロケール（複数選択可・12 locale）。
   */
  availableLocales: ('ja' | 'en' | 'ko' | 'zh' | 'de' | 'fr' | 'es' | 'pt' | 'ru' | 'ar' | 'vi' | 'id')[];
  /**
   * 検索エンジン最適化
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 画像・ファイルの管理（thumb=一覧・card=カード・hero=ヒーロー・og=OGP）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * ブログ記事のカテゴリー分類。Posts から参照されます。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * 英数字とハイフンのみ。例: japan-business, ai-automation
   */
  slug: string;
  description?: string | null;
  color?: ('indigo' | 'emerald' | 'rose' | 'amber' | 'violet' | 'teal') | null;
  sortOrder?: number | null;
  /**
   * このカテゴリーを表示するロケール（複数選択可・12 locale）。
   */
  availableLocales: ('ja' | 'en' | 'ko' | 'zh' | 'de' | 'fr' | 'es' | 'pt' | 'ru' | 'ar' | 'vi' | 'id')[];
  updatedAt: string;
  createdAt: string;
}
/**
 * サービスの管理
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  slug: string;
  tagline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 例: Globe, Search, Bot, MapPin
   */
  icon?: string | null;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  /**
   * このサービスを表示するロケール（複数選択可）。12 locale から自由に組み合わせ可能。
   */
  availableLocales: ('ja' | 'en' | 'ko' | 'zh' | 'de' | 'fr' | 'es' | 'pt' | 'ru' | 'ar' | 'vi' | 'id')[];
  /**
   * ⚠️ このフィールドは 2026-05-12 に廃止されました。availableLocales を使用してください。
   */
  locale?: ('ja' | 'en' | 'both') | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * よくある質問の管理
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  sortOrder?: number | null;
  /**
   * この FAQ を表示するロケール（複数選択可・12 locale）。
   */
  availableLocales: ('ja' | 'en' | 'ko' | 'zh' | 'de' | 'fr' | 'es' | 'pt' | 'ru' | 'ar' | 'vi' | 'id')[];
  /**
   * ⚠️ このフィールドは 2026-05-12 に廃止されました。availableLocales を使用してください。
   */
  locale?: ('ja' | 'en' | 'both') | null;
  category?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 制作実績・事例の管理
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  title: string;
  industry: string;
  description?: string | null;
  challenge?: string | null;
  solution?: string | null;
  /**
   * 例: 売上150%増加、SEO流入3倍
   */
  metrics?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  color?: ('indigo' | 'emerald' | 'rose' | 'amber' | 'violet' | 'teal') | null;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  /**
   * この実績を表示するロケール（複数選択可・12 locale）。海外向け事例は EN/各言語単独公開も可。
   */
  availableLocales: ('ja' | 'en' | 'ko' | 'zh' | 'de' | 'fr' | 'es' | 'pt' | 'ru' | 'ar' | 'vi' | 'id')[];
  /**
   * ⚠️ このフィールドは 2026-05-12 に廃止されました。availableLocales を使用してください。
   */
  locale?: ('ja' | 'en' | 'both') | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 料金プランの管理
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  planName: string;
  /**
   * 例: web, meo, seo, ai, japan-entry-package
   */
  serviceId: string;
  price: number;
  currency: 'jpy' | 'usd';
  billingCycle?: ('monthly' | 'yearly' | 'one-time') | null;
  description?: string | null;
  features?:
    | {
        feature: string;
        included?: boolean | null;
        id?: string | null;
      }[]
    | null;
  isPopular?: boolean | null;
  ctaLabel?: string | null;
  sortOrder?: number | null;
  /**
   * このプランを表示するロケール（複数選択可・12 locale）。JPY=JA / USD=その他が自然なデフォルト・PPP 価格表は s3-4 参照。
   */
  availableLocales: ('ja' | 'en' | 'ko' | 'zh' | 'de' | 'fr' | 'es' | 'pt' | 'ru' | 'ar' | 'vi' | 'id')[];
  /**
   * ⚠️ このフィールドは 2026-05-12 に廃止されました。availableLocales を使用してください。
   */
  locale?: ('ja' | 'en' | 'both') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * お問い合わせ・リードの管理
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  companyName?: string | null;
  email: string;
  phone?: string | null;
  subject?: string | null;
  message?: string | null;
  serviceInterest?: ('web' | 'meo' | 'seo' | 'ai' | 'japan-entry' | 'other') | null;
  budget?: string | null;
  pipelineStage?: ('new' | 'in_discussion' | 'proposal_sent' | 'closed_won' | 'closed_lost') | null;
  source?: string | null;
  locale?: ('ja' | 'en') | null;
  /**
   * 顧客には非表示
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * コレクション変更の監査ログ（自動記録・読み取り専用）。新しい順に表示。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  collection: string;
  action: 'create' | 'update' | 'delete';
  documentId?: string | null;
  userEmail?: string | null;
  userRole?: string | null;
  /**
   * 変更前/変更後のJSON差分（最大8KB）
   */
  diff?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Block ベースのビジュアルページ (Hero/Section/CardGrid/CTA/FAQ/RichText 等を組み合わせ)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * 例: about-us, why-paradigm, japan-entry-guide
   */
  slug: string;
  /**
   * Open Graph + Twitter Card にも使われます
   */
  description?: string | null;
  ogImage?: (number | null) | Media;
  /**
   * title / description / canonical / robots — page.tsx の generateMetadata から参照
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    noindex?: boolean | null;
    canonical?: string | null;
  };
  layout?:
    | (
        | HeroBlockType
        | SectionBlockType
        | CardGridBlockType
        | CTABlockType
        | FAQBlockType
        | RichTextBlockType
        | {
            kicker?: string | null;
            title?: string | null;
            subtitle?: string | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  sublabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            background?: ('default' | 'surface' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            kicker?: string | null;
            title?: string | null;
            items?:
              | {
                  name: string;
                  location?: string | null;
                  text: string;
                  avatar?: (number | null) | Media;
                  rating?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            kicker?: string | null;
            title?: string | null;
            subtitle?: string | null;
            steps?:
              | {
                  title: string;
                  description: string;
                  /**
                   * 例: Headphones / PenTool / Code2 / TrendingUp
                   */
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'process';
          }
        | {
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            direction?: ('left' | 'right') | null;
            speed?: ('slow' | 'normal' | 'fast') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'marquee';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            tiers?:
              | {
                  name: string;
                  price?: string | null;
                  period?: string | null;
                  description?: string | null;
                  features?: string | null;
                  ctaLabel?: string | null;
                  ctaHref?: string | null;
                  highlighted?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            kicker?: string | null;
            title?: string | null;
            subtitle?: string | null;
            leftLabel?: string | null;
            rightLabel?: string | null;
            rows?:
              | {
                  item: string;
                  leftValue?: string | null;
                  rightValue?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'comparison';
          }
      )[]
    | null;
  /**
   * 12 locale から多選択。ja/en は独自設計母版・他10ロケールは翻訳版として展開。
   */
  availableLocales: ('ja' | 'en' | 'ko' | 'zh' | 'de' | 'fr' | 'es' | 'pt' | 'ru' | 'ar' | 'vi' | 'id')[];
  isHomepage?: boolean | null;
  /**
   * ⚠️ このフィールドは 2026-05-12 に廃止されました。availableLocales を使用してください。既存データ移行後に DB 列も drop 予定。
   */
  locale?: ('ja' | 'en' | 'both') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlockType".
 */
export interface HeroBlockType {
  variant?: ('centered' | 'split-image' | 'video-bg') | null;
  badge?: string | null;
  title: string;
  subtitle?: string | null;
  primaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  image?: (number | null) | Media;
  videoUrl?: string | null;
  stats?:
    | {
        value: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionBlockType".
 */
export interface SectionBlockType {
  kicker?: string | null;
  title: string;
  subtitle?: string | null;
  alignment?: ('center' | 'left') | null;
  background?: ('default' | 'surface' | 'accent-soft') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlockType".
 */
export interface CardGridBlockType {
  title?: string | null;
  variant?: ('bento' | 'equal' | 'list') | null;
  columns?: ('2' | '3' | '4') | null;
  cards?:
    | {
        icon?: string | null;
        title: string;
        description?: string | null;
        href?: string | null;
        image?: (number | null) | Media;
        highlighted?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'card-grid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlockType".
 */
export interface CTABlockType {
  title: string;
  subtitle?: string | null;
  primaryCta: {
    label: string;
    href: string;
  };
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  background?: ('gradient' | 'surface' | 'accent') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlockType".
 */
export interface FAQBlockType {
  title?: string | null;
  subtitle?: string | null;
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlockType".
 */
export interface RichTextBlockType {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  maxWidth?: ('prose' | 'wide' | 'full') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'rich-text';
}
/**
 * About ページのチームメンバー。実在メンバーのみ (ストックフォト禁止)。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  socials?:
    | {
        platform?: ('twitter' | 'linkedin' | 'github' | 'website' | 'email') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  /**
   * このメンバーを表示するロケール（複数選択可・12 locale）。
   */
  availableLocales: ('ja' | 'en' | 'ko' | 'zh' | 'de' | 'fr' | 'es' | 'pt' | 'ru' | 'ar' | 'vi' | 'id')[];
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 実在顧客の声のみ掲載 (捏造・架空証言禁止)。掲載許諾済みのものだけ公開されます。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  authorName: string;
  authorTitle?: string | null;
  company?: string | null;
  photo?: (number | null) | Media;
  rating?: number | null;
  serviceTag?: ('web' | 'meo' | 'seo' | 'ai' | 'video' | 'japan-entry' | 'other') | null;
  /**
   * 🚨 顧客から掲載許諾を得ている場合のみ ON。OFF のものは公開対象外。
   */
  consentGiven?: boolean | null;
  /**
   * 氏名を伏せて業種・会社規模のみ表示する場合に ON。
   */
  isAnonymous?: boolean | null;
  sortOrder?: number | null;
  /**
   * この声を表示するロケール（複数選択可・12 locale）。
   */
  availableLocales: ('ja' | 'en' | 'ko' | 'zh' | 'de' | 'fr' | 'es' | 'pt' | 'ru' | 'ar' | 'vi' | 'id')[];
  /**
   * consentGiven と両方 ON で初めて公開されます。
   */
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'pricing';
        value: number | Pricing;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  coverImage?: T;
  category?: T;
  readTime?: T;
  categoryRef?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  availableLocales?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  icon?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  sortOrder?: T;
  availableLocales?: T;
  locale?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  sortOrder?: T;
  availableLocales?: T;
  locale?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  title?: T;
  industry?: T;
  description?: T;
  challenge?: T;
  solution?: T;
  metrics?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  color?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  sortOrder?: T;
  availableLocales?: T;
  locale?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  planName?: T;
  serviceId?: T;
  price?: T;
  currency?: T;
  billingCycle?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        included?: T;
        id?: T;
      };
  isPopular?: T;
  ctaLabel?: T;
  sortOrder?: T;
  availableLocales?: T;
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  companyName?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  serviceInterest?: T;
  budget?: T;
  pipelineStage?: T;
  source?: T;
  locale?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  collection?: T;
  action?: T;
  documentId?: T;
  userEmail?: T;
  userRole?: T;
  diff?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  ogImage?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        noindex?: T;
        canonical?: T;
      };
  layout?:
    | T
    | {
        hero?: T | HeroBlockTypeSelect<T>;
        section?: T | SectionBlockTypeSelect<T>;
        'card-grid'?: T | CardGridBlockTypeSelect<T>;
        cta?: T | CTABlockTypeSelect<T>;
        faq?: T | FAQBlockTypeSelect<T>;
        'rich-text'?: T | RichTextBlockTypeSelect<T>;
        stats?:
          | T
          | {
              kicker?: T;
              title?: T;
              subtitle?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    sublabel?: T;
                    id?: T;
                  };
              background?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              kicker?: T;
              title?: T;
              items?:
                | T
                | {
                    name?: T;
                    location?: T;
                    text?: T;
                    avatar?: T;
                    rating?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              kicker?: T;
              title?: T;
              subtitle?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        marquee?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              direction?: T;
              speed?: T;
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              title?: T;
              subtitle?: T;
              tiers?:
                | T
                | {
                    name?: T;
                    price?: T;
                    period?: T;
                    description?: T;
                    features?: T;
                    ctaLabel?: T;
                    ctaHref?: T;
                    highlighted?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        comparison?:
          | T
          | {
              kicker?: T;
              title?: T;
              subtitle?: T;
              leftLabel?: T;
              rightLabel?: T;
              rows?:
                | T
                | {
                    item?: T;
                    leftValue?: T;
                    rightValue?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  availableLocales?: T;
  isHomepage?: T;
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlockType_select".
 */
export interface HeroBlockTypeSelect<T extends boolean = true> {
  variant?: T;
  badge?: T;
  title?: T;
  subtitle?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  image?: T;
  videoUrl?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionBlockType_select".
 */
export interface SectionBlockTypeSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  subtitle?: T;
  alignment?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlockType_select".
 */
export interface CardGridBlockTypeSelect<T extends boolean = true> {
  title?: T;
  variant?: T;
  columns?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        href?: T;
        image?: T;
        highlighted?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlockType_select".
 */
export interface CTABlockTypeSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlockType_select".
 */
export interface FAQBlockTypeSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlockType_select".
 */
export interface RichTextBlockTypeSelect<T extends boolean = true> {
  content?: T;
  maxWidth?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  sortOrder?: T;
  availableLocales?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  authorTitle?: T;
  company?: T;
  photo?: T;
  rating?: T;
  serviceTag?: T;
  consentGiven?: T;
  isAnonymous?: T;
  sortOrder?: T;
  availableLocales?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  sortOrder?: T;
  availableLocales?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * サイト全体の設定
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  description?: string | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    businessHours?: string | null;
  };
  social?: {
    twitter?: string | null;
    instagram?: string | null;
    facebook?: string | null;
    linkedin?: string | null;
    line?: string | null;
  };
  maintenance?: {
    maintenanceMode?: boolean | null;
    maintenanceMessage?: string | null;
  };
  /**
   * 各ページが個別指定しない場合に使われる既定の SEO 値。
   */
  seo?: {
    defaultMetaTitle?: string | null;
    defaultMetaDescription?: string | null;
    keywords?: string | null;
    defaultOgImage?: (number | null) | Media;
    favicon?: (number | null) | Media;
    /**
     * 例: @paradigm_jp
     */
    twitterHandle?: string | null;
  };
  /**
   * GTM / GA4 / Meta Pixel の ID。空欄なら読み込みません。Umami は別 (umamiByLocale)。
   */
  tracking?: {
    /**
     * 例: GTM-XXXXXXX
     */
    gtmId?: string | null;
    /**
     * 例: G-XXXXXXXXXX
     */
    ga4Id?: string | null;
    metaPixelId?: string | null;
    /**
     * ⚠️ admin のみ編集可。信頼できるコードのみ。<head> 末尾に挿入されます (XSS リスク)。
     */
    headScripts?: string | null;
    /**
     * ⚠️ admin のみ編集可。信頼できるコードのみ。<body> 末尾に挿入されます (XSS リスク)。
     */
    bodyScripts?: string | null;
  };
  /**
   * サイト最上部の告知バー。表示する場合は enabled を ON。
   */
  announcement?: {
    enabled?: boolean | null;
    message?: string | null;
    linkLabel?: string | null;
    linkHref?: string | null;
    variant?: ('ink' | 'accent' | 'tech') | null;
  };
  /**
   * 特定商取引法・フッター・構造化データで使う会社の正式情報。
   */
  company?: {
    legalName?: string | null;
    representativeName?: string | null;
    registrationNumber?: string | null;
    foundedYear?: string | null;
    postalCode?: string | null;
    address?: string | null;
  };
  /**
   * locale 別の Umami site ID。lookup は当該 locale → ja → null の順で fallback。
   */
  umamiByLocale?:
    | {
        locale: 'ja' | 'en' | 'ko' | 'zh' | 'de' | 'fr' | 'es' | 'pt' | 'ru' | 'ar' | 'vi' | 'id';
        /**
         * Umami が払い出す UUID
         */
        websiteId: string;
        id?: string | null;
      }[]
    | null;
  /**
   * locale 別の Cal.com URL。lookup は当該 locale → ja → default の順で fallback。
   */
  calendarByLocale?:
    | {
        locale: 'ja' | 'en' | 'ko' | 'zh' | 'de' | 'fr' | 'es' | 'pt' | 'ru' | 'ar' | 'vi' | 'id';
        /**
         * 例: https://cal.com/paradigm/intro-en
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 非推奨: umamiByLocale (array) を使用してください。後方互換のため残存。
   */
  analytics?: {
    umamiWebsiteId?: string | null;
    umamiWebsiteIdEn?: string | null;
  };
  /**
   * 非推奨: calendarByLocale (array) を使用してください。後方互換のため残存。
   */
  calendarUrl?: {
    ja?: string | null;
    en?: string | null;
  };
  /**
   * 色・フォント・角丸を admin から編集します。空のままならデフォルトを使用。色は #FAFAF7 / rgb(250, 250, 247) / 250 250 247 のいずれかの形式。
   */
  theme?: {
    colors?: {
      /**
       * デフォルト: #FAFAF7
       */
      paper?: string | null;
      /**
       * デフォルト: #F1F0EA
       */
      paperDeep?: string | null;
      /**
       * デフォルト: #1C1C2E
       */
      ink?: string | null;
      inkSoft?: string | null;
      inkMute?: string | null;
      line?: string | null;
      /**
       * デフォルト: #6366F1 (インディゴ)
       */
      accent?: string | null;
      /**
       * デフォルト: #14B8A6
       */
      tech?: string | null;
      glow?: string | null;
    };
    fonts?: {
      /**
       * 例: 'Noto Sans JP', system-ui, sans-serif
       */
      display?: string | null;
      /**
       * 例: 'Noto Sans', 'Noto Sans JP', sans-serif
       */
      body?: string | null;
    };
    radius?: {
      sm?: string | null;
      md?: string | null;
      lg?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * サイト上部のナビゲーション・CTA ボタン。日本語で保存すると全 12 言語に自動翻訳されます。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * ヘッダー中央に並ぶリンク。上から順に表示。href は内部パス (/about) または外部 URL。
   */
  navItems?:
    | {
        label: string;
        href: string;
        openInNewTab?: boolean | null;
        /**
         * 設定するとこのリンクがドロップダウンメニューになります。
         */
        children?:
          | {
              label: string;
              href: string;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    enabled?: boolean | null;
    /**
     * 空のとき messages の cta.primary を使用
     */
    label?: string | null;
    href?: string | null;
  };
  showLocaleSwitcher?: boolean | null;
  showThemeToggle?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * サイト下部のリンク列・SNS・法的リンク。日本語で保存すると全 12 言語に自動翻訳されます。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * フッター上部の editorial 見出し横に出る一文。
   */
  tagline?: string | null;
  studioLocation?: string | null;
  /**
   * フッター中段のリンク列 (最大 4 列)。
   */
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * フッターに表示する SNS アイコン。
   */
  socialLinks?:
    | {
        platform: 'twitter' | 'instagram' | 'facebook' | 'linkedin' | 'line' | 'youtube' | 'github';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * コピーライト行の横に出るリンク (プライバシー / 特商法 等)。
   */
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 例: Paradigm合同会社 · All rights reserved (年は自動付与)。
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
        businessHours?: T;
      };
  social?:
    | T
    | {
        twitter?: T;
        instagram?: T;
        facebook?: T;
        linkedin?: T;
        line?: T;
      };
  maintenance?:
    | T
    | {
        maintenanceMode?: T;
        maintenanceMessage?: T;
      };
  seo?:
    | T
    | {
        defaultMetaTitle?: T;
        defaultMetaDescription?: T;
        keywords?: T;
        defaultOgImage?: T;
        favicon?: T;
        twitterHandle?: T;
      };
  tracking?:
    | T
    | {
        gtmId?: T;
        ga4Id?: T;
        metaPixelId?: T;
        headScripts?: T;
        bodyScripts?: T;
      };
  announcement?:
    | T
    | {
        enabled?: T;
        message?: T;
        linkLabel?: T;
        linkHref?: T;
        variant?: T;
      };
  company?:
    | T
    | {
        legalName?: T;
        representativeName?: T;
        registrationNumber?: T;
        foundedYear?: T;
        postalCode?: T;
        address?: T;
      };
  umamiByLocale?:
    | T
    | {
        locale?: T;
        websiteId?: T;
        id?: T;
      };
  calendarByLocale?:
    | T
    | {
        locale?: T;
        url?: T;
        id?: T;
      };
  analytics?:
    | T
    | {
        umamiWebsiteId?: T;
        umamiWebsiteIdEn?: T;
      };
  calendarUrl?:
    | T
    | {
        ja?: T;
        en?: T;
      };
  theme?:
    | T
    | {
        colors?:
          | T
          | {
              paper?: T;
              paperDeep?: T;
              ink?: T;
              inkSoft?: T;
              inkMute?: T;
              line?: T;
              accent?: T;
              tech?: T;
              glow?: T;
            };
        fonts?:
          | T
          | {
              display?: T;
              body?: T;
            };
        radius?:
          | T
          | {
              sm?: T;
              md?: T;
              lg?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        enabled?: T;
        label?: T;
        href?: T;
      };
  showLocaleSwitcher?: T;
  showThemeToggle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  studioLocation?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}