BEGIN;

WITH profiles(profile) AS (
  VALUES
  ($profile${
    "slug":"greater-tokyo-real-estate-market",
    "title":"Greater Tokyo Real Estate Market: Foreign Investor Map for 2026",
    "summary":"A decision map for comparing Tokyo's 23 wards with Yokohama, Kawasaki, Saitama and Chiba using 2026 official land benchmarks, liquidity context, hazards and execution gates.",
    "category":"Greater Tokyo real estate","region":"Greater Tokyo","assetClass":"Residential / mixed-use","decisionStage":"Market allocation","readTime":"18 min","kicker":"GREATER TOKYO / MARKET ALLOCATION",
    "decisionQuestion":"Is Greater Tokyo one investable market—or a set of submarkets that require different return, risk and operating assumptions?",
    "answer":"Treat Greater Tokyo as a portfolio of distinct submarkets. The 2026 residential standard-site average was JPY 856,400 per m² across Tokyo's wards, versus JPY 319,400 in Kawasaki, JPY 266,000 in Yokohama, JPY 246,700 in Saitama City and JPY 149,700 in Chiba City. Those benchmarks describe location dispersion, not asset value. Allocate only after matching tenant demand, building evidence, parcel hazards, financing and the likely exit-buyer pool.",
    "priceFact":"JPY 856,400/m² Tokyo wards average","priceMeaning":"Tokyo's ward average was more than three times the Yokohama city average and more than five times Chiba City's average. A single Greater Tokyo acquisition hurdle therefore hides major differences in land basis, income yield and exit depth.",
    "growthFact":"Tokyo wards +9.0%; Yokohama +3.3%; Kawasaki +4.4%","growthMeaning":"The 2026 residential benchmark changes show different price momentum across the conurbation. The figures are simple averages of continuing standard sites, not expected returns.",
    "coveredMarkets":["Tokyo 23 wards","Tokyo Tama","Yokohama","Kawasaki","Saitama City","South Saitama","Chiba Bay","Kashiwa / Nagareyama / Narita"],
    "evidenceScope":"2026 MLIT residential standard-site averages for five Greater Tokyo anchors.",
    "evidencePoints":[{"market":"Tokyo wards","averagePriceYenPerSqm":856400,"annualChangePct":9.0,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Kawasaki","averagePriceYenPerSqm":319400,"annualChangePct":4.4,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Yokohama","averagePriceYenPerSqm":266000,"annualChangePct":3.3,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Saitama City","averagePriceYenPerSqm":246700,"annualChangePct":2.7,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Chiba City","averagePriceYenPerSqm":149700,"annualChangePct":5.8,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]}],
    "thesisLede":"The investable question is where a specific demand engine compensates for land basis, operating burden and exit risk.",
    "thesis":"Tokyo's core, commuter cities and bay-side markets share a rail-linked economy but not the same tenant base, price discovery or hazard profile. A defensible allocation starts with the intended income stream and buyer pool, then narrows to station catchments and building types. Comparing city averages is useful for triage; using them as an acquisition model is not.",
    "demand":"Map employment centres, household formation, education, tourism and logistics separately. A central office catchment, family rental corridor and distribution node can all show demand while responding differently to remote work, household affordability, visitor flows and transport disruption.",
    "supply":"Measure competing completions, redevelopment, obsolete stock, unit configuration and land availability by the same catchment used for demand. The spread between Tokyo and surrounding cities can reflect scarcity and income depth, but also a lower current yield and greater sensitivity to capital-market assumptions.",
    "riskLede":"The largest portfolio error is applying a Tokyo headline to an asset whose tenants, hazards and exit buyers are local.",
    "riskTitle":"False Greater Tokyo uniformity","downside":"A portfolio can appear diversified while repeating the same rail, flood, financing or tenant risk. Region-wide price momentum may also encourage buyers to accept thin income yield without documenting which micro-market can support rent and exit assumptions.",
    "riskAction":"Build separate investment boxes for core, inner commuter, outer commuter and bay/logistics markets; cap exposure by hazard, railway, tenant and buyer type, then require building-level evidence inside each box.",
    "relatedSlugs":["tokyo-multifamily-investment-due-diligence","buying-property-in-japan-as-a-foreigner","japan-real-estate-taxes-for-non-residents"]
  }$profile$::jsonb),
  ($profile${
    "slug":"tokyo-central-three-wards-real-estate-investment",
    "title":"Tokyo Central Three Wards Real Estate: Chiyoda, Chuo and Minato",
    "summary":"A foreign-investor screen for Chiyoda, Chuo and Minato residential, office and mixed-use assets using official price dispersion, redevelopment, tenancy and exit evidence.",
    "category":"Tokyo core real estate","region":"Tokyo — Chiyoda / Chuo / Minato","assetClass":"Prime residential / office","decisionStage":"Core allocation","readTime":"17 min","kicker":"TOKYO CORE / CENTRAL THREE WARDS",
    "decisionQuestion":"Does the Central Three Wards scarcity thesis support the proposed price after income, redevelopment and exit evidence are separated?",
    "answer":"Advance only if the asset earns its Central Three Wards premium through verified income, rights and buyer depth. MLIT's 2026 residential averages were JPY 3,631,400 per m² in Chiyoda, JPY 3,013,700 in Minato and JPY 1,930,000 in Chuo. The wide range inside the core makes a generic 'central Tokyo' comparable set indefensible. Match use, tenure, building age, station access and redevelopment exposure before pricing scarcity.",
    "priceFact":"Chiyoda JPY 3,631,400/m²; Minato JPY 3,013,700; Chuo JPY 1,930,000","priceMeaning":"Even the three core wards do not form one price band. Residential standard-site averages must be reconciled to the asset's exact use, tenure and operating income.",
    "growthFact":"Minato +16.6%; Chuo +13.8%; Chiyoda +10.7%","growthMeaning":"All three residential averages increased strongly in 2026, increasing the need to distinguish durable rent and buyer evidence from benchmark momentum.",
    "coveredMarkets":["Chiyoda","Chuo","Minato"],
    "evidenceScope":"2026 MLIT residential standard-site averages for Tokyo's Central Three Wards.",
    "evidencePoints":[{"market":"Chiyoda","averagePriceYenPerSqm":3631400,"annualChangePct":10.7,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Minato","averagePriceYenPerSqm":3013700,"annualChangePct":16.6,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Chuo","averagePriceYenPerSqm":1930000,"annualChangePct":13.8,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]}],
    "thesisLede":"Core scarcity matters only when the exact rights, income stream and replacement constraints are documented.",
    "thesis":"Chiyoda combines government and corporate centrality, Chuo combines office, retail and major residential redevelopment, and Minato combines international, office and high-end residential demand. These demand engines overlap but are not interchangeable. The investment memo should identify which one supports the asset and which buyer cohort can validate it at exit.",
    "demand":"Obtain tenant and buyer evidence by use: corporate and government-linked occupancy for offices, household and international demand for residential, and destination or neighbourhood evidence for retail. Avoid using luxury sales headlines to support ordinary rental assumptions or office transactions to price residential land.",
    "supply":"Redevelopment can enhance a district while adding competing space and changing pedestrian flows. Map planned completions, construction periods, view and access impacts, lease expiries and the asset's ability to compete after new stock delivers. Scarcity must be demonstrated for the exact product, not assumed from the ward name.",
    "riskLede":"At core pricing, small errors in income normalization or exit cap rate can erase a large share of equity value.",
    "riskTitle":"Core-premium overpayment","downside":"Strong benchmark growth can compress current income yield and encourage a residual-land narrative that is not available to the buyer because of tenure, zoning, floor-area, tenant or redevelopment constraints.",
    "riskAction":"Separate in-place income value, vacant-possession value and any redevelopment option; obtain planning, tenant, engineering and legal evidence for each and assign zero value to an option that is not executable.",
    "relatedSlugs":["tokyo-multifamily-investment-due-diligence","japan-real-estate-taxes-for-non-residents","greater-tokyo-real-estate-market"]
  }$profile$::jsonb),
  ($profile${
    "slug":"shinjuku-shibuya-real-estate-investment",
    "title":"Shinjuku and Shibuya Real Estate Investment Due Diligence",
    "summary":"An evidence-led comparison of Shinjuku and Shibuya mixed-use, rental and office investments covering station-scale redevelopment, tenant demand, construction and exit risk.",
    "category":"Tokyo gateway real estate","region":"Tokyo — Shinjuku / Shibuya","assetClass":"Mixed-use / rental / office","decisionStage":"Submarket selection","readTime":"16 min","kicker":"TOKYO WEST CORE / GATEWAY DISTRICTS",
    "decisionQuestion":"Which west-core gateway offers the stronger evidence-adjusted case for the proposed asset and holding period?",
    "answer":"Do not choose between Shinjuku and Shibuya from brand or benchmark growth alone. MLIT's 2026 residential averages were JPY 1,131,600 per m² in Shinjuku and JPY 1,874,100 in Shibuya, with annual changes of 11.2% and 11.0%. Price the exact station catchment, tenant segment, construction interface and exit buyer; major redevelopment can improve a district while disrupting access or adding competing space during the hold.",
    "priceFact":"Shibuya JPY 1,874,100/m² vs Shinjuku JPY 1,131,600","priceMeaning":"The official residential averages show a material basis difference despite both being west-core gateway markets. Asset use and micro-location can widen or reverse that relationship.",
    "growthFact":"Shinjuku +11.2%; Shibuya +11.0%","growthMeaning":"Similar 2026 residential benchmark momentum does not mean equivalent rental yield, tenant durability, redevelopment exposure or exit liquidity.",
    "coveredMarkets":["Shinjuku","Shibuya"],
    "evidenceScope":"2026 MLIT residential standard-site averages for Shinjuku and Shibuya.",
    "evidencePoints":[{"market":"Shinjuku","averagePriceYenPerSqm":1131600,"annualChangePct":11.2,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Shibuya","averagePriceYenPerSqm":1874100,"annualChangePct":11.0,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]}],
    "thesisLede":"Both wards are gateway markets, but the asset must connect to a specific employment, entertainment, residential or visitor demand engine.",
    "thesis":"Shinjuku's scale spans corporate, government, retail, hospitality and multiple residential neighbourhoods; Shibuya's thesis often leans more heavily on technology, media, retail, entertainment and premium residential demand. Define the tenant and buyer segment first, then use only the station exits and neighbourhoods relevant to it.",
    "demand":"Test day and night populations, lease enquiry, tenant churn and completed transactions through the construction calendar. Demand that looks deep at ward level can be weak for an oversized unit, secondary office floorplate or access route affected by a major project.",
    "supply":"Track office, residential, hotel and retail delivery separately. New mixed-use schemes may raise district quality but also reset tenant expectations for age, efficiency, seismic standard, amenities and public realm. Budget the capital required for older stock to remain competitive.",
    "riskLede":"The key downside is paying today for a future district benefit while absorbing the construction, competition and leasing risk first.",
    "riskTitle":"Redevelopment timing mismatch","downside":"A multi-year station or district project can change pedestrian access, noise, views, competing floor area and tenant behaviour before the anticipated uplift is realized. A short hold may capture disruption rather than benefit.",
    "riskAction":"Build a dated project map, construction-interface plan and lease-expiry schedule; model the hold through disruption and delivery, and do not count an exit premium without identified buyers and completed comparables.",
    "relatedSlugs":["tokyo-central-three-wards-real-estate-investment","tokyo-multifamily-investment-due-diligence","greater-tokyo-real-estate-market"]
  }$profile$::jsonb),
  ($profile${
    "slug":"bunkyo-toshima-real-estate-investment",
    "title":"Bunkyo and Toshima Real Estate Investment: Education, Medical and Ikebukuro Demand",
    "summary":"A rental and mixed-use investment screen for Bunkyo and Toshima that separates education, medical, family and Ikebukuro gateway demand from building and price risk.",
    "category":"Tokyo rental real estate","region":"Tokyo — Bunkyo / Toshima","assetClass":"Rental residential / mixed-use","decisionStage":"Income underwriting","readTime":"16 min","kicker":"TOKYO INNER NORTH / RENTAL DEMAND",
    "decisionQuestion":"Can education, medical and gateway demand support the proposed rent and exit assumptions after stock condition and submarket differences?",
    "answer":"Treat Bunkyo and Toshima as complementary rather than interchangeable. The 2026 residential standard-site averages were JPY 1,448,100 per m² in Bunkyo and JPY 912,100 in Toshima; annual changes were 13.8% and 12.9%. Verify whether the building serves family, student, medical, professional or Ikebukuro-linked demand and whether its unit mix, age and management match that segment.",
    "priceFact":"Bunkyo JPY 1,448,100/m²; Toshima JPY 912,100","priceMeaning":"The official averages show a substantial basis gap. A cross-ward comparable must explain school, station, product, tenure and neighbourhood differences.",
    "growthFact":"Bunkyo +13.8%; Toshima +12.9%","growthMeaning":"Strong residential benchmark growth raises the bar for proving rent support and future buyer depth rather than relying on location labels.",
    "coveredMarkets":["Bunkyo","Toshima","Ikebukuro"],
    "evidenceScope":"2026 MLIT residential standard-site averages for Bunkyo and Toshima.",
    "evidencePoints":[{"market":"Bunkyo","averagePriceYenPerSqm":1448100,"annualChangePct":13.8,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Toshima","averagePriceYenPerSqm":912100,"annualChangePct":12.9,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]}],
    "thesisLede":"Durable institutions can support demand, but only the right unit, lease and walking-distance band captures it.",
    "thesis":"Bunkyo's education, medical and established residential profile differs from Toshima's Ikebukuro-centred gateway, commercial and denser rental markets. The thesis should state the target household or tenant, the institution or transport node that anchors it, and the alternative neighbourhoods competing for the same demand.",
    "demand":"Segment family, professional, student and short-stay demand rather than averaging them. Test lease length, seasonality, guarantor profile, turnover cost and achieved—not advertised—rent by unit size and building age.",
    "supply":"Older condominium and rental stock can offer location but carry seismic, equipment, reserve and layout disadvantages. Compare planned and completed supply, then cost the upgrades needed to compete with newer product without assuming all renovation spend converts to rent.",
    "riskLede":"Institutional proximity can be overcapitalized when the unit or lease does not match the people using that institution.",
    "riskTitle":"Demand-segment mismatch","downside":"A building marketed as education- or medical-led can still face high turnover, weak family fit or limited rent growth if unit size, access, noise, management or guarantor requirements do not match the target tenant.",
    "riskAction":"Reconstruct twelve to twenty-four months of enquiries, applications, achieved rents, renewal and move-out reasons by unit; compare the exact product with competing buildings inside the same walking-distance band.",
    "relatedSlugs":["shinjuku-shibuya-real-estate-investment","tokyo-multifamily-investment-due-diligence","greater-tokyo-real-estate-market"]
  }$profile$::jsonb),
  ($profile${
    "slug":"shinagawa-meguro-ota-real-estate-investment",
    "title":"Shinagawa, Meguro and Ota Real Estate Investment Due Diligence",
    "summary":"A south-Tokyo investment framework for premium residential, office-linked rentals, airport access and industrial-residential interfaces across Shinagawa, Meguro and Ota.",
    "category":"Tokyo south real estate","region":"Tokyo — Shinagawa / Meguro / Ota","assetClass":"Residential / mixed-use","decisionStage":"Submarket underwriting","readTime":"17 min","kicker":"TOKYO SOUTH / CONNECTIVITY AND PRODUCT",
    "decisionQuestion":"Does south-Tokyo connectivity produce verifiable tenant and exit demand for this asset, after hazard and product differences?",
    "answer":"Underwrite each south-Tokyo demand engine separately. The 2026 residential averages were JPY 1,404,500 per m² in Meguro, JPY 1,244,100 in Shinagawa and JPY 647,600 in Ota, with annual changes of 13.7%, 13.9% and 7.9%. Premium residential, major-station employment, airport access and industrial-residential transition areas require different rents, capex and buyer assumptions.",
    "priceFact":"Meguro JPY 1,404,500/m²; Shinagawa JPY 1,244,100; Ota JPY 647,600","priceMeaning":"The price dispersion rejects a single south-Tokyo land or rent assumption. Ward averages also contain neighbourhoods with very different elevation, access and use.",
    "growthFact":"Shinagawa +13.9%; Meguro +13.7%; Ota +7.9%","growthMeaning":"2026 residential benchmark momentum was strong but uneven, requiring asset-level proof of rent, condition and connectivity benefits.",
    "coveredMarkets":["Shinagawa","Meguro","Ota"],
    "evidenceScope":"2026 MLIT residential standard-site averages for Shinagawa, Meguro and Ota.",
    "evidencePoints":[{"market":"Meguro","averagePriceYenPerSqm":1404500,"annualChangePct":13.7,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Shinagawa","averagePriceYenPerSqm":1244100,"annualChangePct":13.9,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Ota","averagePriceYenPerSqm":647600,"annualChangePct":7.9,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]}],
    "thesisLede":"Connectivity creates value only when the building, tenant and walking route convert it into repeatable occupancy and exit demand.",
    "thesis":"Meguro often carries a premium residential thesis, Shinagawa combines residential neighbourhoods with major employment and transport nodes, and Ota spans airport-linked, industrial and broad residential demand. Define whether the asset competes on prestige, commute, airport access, affordability or operating use before selecting comparables.",
    "demand":"Measure tenant origin, workplace or airport link, household profile and achieved rent by station and unit type. An express connection or major terminal has limited value if the walking route, transfer pattern, noise or unit design does not fit the target tenant.",
    "supply":"Assess premium new supply, older stock near stations, conversion potential and industrial-residential land-use interfaces. Review title, zoning, approved use, noise, vibration, easements and major capital systems; avoid pricing a conversion until feasibility and tenant vacancy are documented.",
    "riskLede":"South-Tokyo averages can conceal low-elevation, aviation, industrial and older-building risks that alter financing and exit demand.",
    "riskTitle":"Connectivity premium without site fit","downside":"An acquisition can pay for station or airport proximity while underestimating noise, walking quality, flood or liquefaction exposure, industrial adjacency, redevelopment works or the capital needed for the building to serve the target tenant.",
    "riskAction":"Complete day/night route checks, official hazard exports, noise and use review, engineering inspection and tenant interview evidence; compare only assets with the same connectivity benefit and externalities.",
    "relatedSlugs":["tokyo-central-three-wards-real-estate-investment","tokyo-multifamily-investment-due-diligence","greater-tokyo-real-estate-market"]
  }$profile$::jsonb),
  ($profile${
    "slug":"setagaya-nakano-suginami-real-estate-investment",
    "title":"Setagaya, Nakano and Suginami Rental Real Estate Investment",
    "summary":"A family and commuter rental screen for Setagaya, Nakano and Suginami covering station catchments, unit mix, older stock, operating evidence and price dispersion.",
    "category":"Tokyo family rental","region":"Tokyo — Setagaya / Nakano / Suginami","assetClass":"Multifamily / rental residential","decisionStage":"Income underwriting","readTime":"16 min","kicker":"TOKYO WEST RESIDENTIAL / FAMILY AND COMMUTER",
    "decisionQuestion":"Can the proposed west-Tokyo rental asset defend occupancy and NOI at its price across a full tenant and capital cycle?",
    "answer":"Use station catchments and unit-level operations, not a west-Tokyo label. The 2026 residential averages were JPY 782,700 per m² in Nakano, JPY 779,900 in Setagaya and JPY 703,200 in Suginami, while annual changes ranged from 7.0% to 9.0%. Similar averages can hide major differences in commute, unit size, family fit, building age and exit-buyer demand.",
    "priceFact":"Nakano JPY 782,700/m²; Setagaya JPY 779,900; Suginami JPY 703,200","priceMeaning":"The averages are relatively close, making station, product, condition and lease evidence more important than ward-level pricing shorthand.",
    "growthFact":"Nakano +9.0%; Suginami +8.2%; Setagaya +7.0%","growthMeaning":"Different 2026 momentum inside a similar price band should prompt a micro-market supply and demand check, not a mechanical repricing.",
    "coveredMarkets":["Setagaya","Nakano","Suginami"],
    "evidenceScope":"2026 MLIT residential standard-site averages for Setagaya, Nakano and Suginami.",
    "evidencePoints":[{"market":"Nakano","averagePriceYenPerSqm":782700,"annualChangePct":9.0,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Setagaya","averagePriceYenPerSqm":779900,"annualChangePct":7.0,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Suginami","averagePriceYenPerSqm":703200,"annualChangePct":8.2,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]}],
    "thesisLede":"West-Tokyo rental resilience depends on the exact railway, walk, household segment and building product.",
    "thesis":"These wards contain family-oriented neighbourhoods, dense commuter stations, low-rise housing and apartment corridors. The investment box should specify the railway and station, walk time, unit mix, school and household relevance, and whether the likely exit buyer values stable income, redevelopment or owner occupation.",
    "demand":"Rebuild the rent roll by new lease, renewal, household type and unit size. Confirm commuting alternatives, bicycle and bus access, local amenities and the reasons tenants leave. A high ward population does not prove demand for a small, dark or poorly managed unit.",
    "supply":"Older wood and reinforced-concrete stock, small-lot ownership and new station-area projects create different capex and competition. Verify seismic status, reserve history, equipment replacement, legal access and unit layouts; compare the cost of repositioning with achievable rent, not asking rent.",
    "riskLede":"The common downside is paying a scarcity price for average stock whose NOI cannot absorb maintenance and tenant turnover.",
    "riskTitle":"Family-demand and capex mismatch","downside":"An older building can retain occupancy yet deliver weak cash flow when layouts, equipment, sound, access or management require recurring concessions and capital work. Ward-level price growth can mask that operating drag.",
    "riskAction":"Build unit cohorts for achieved rent, vacancy days, turnover cost and repair history; obtain a ten-year building plan and stress family and single-person demand separately.",
    "relatedSlugs":["tokyo-multifamily-investment-due-diligence","shinjuku-shibuya-real-estate-investment","greater-tokyo-real-estate-market"]
  }$profile$::jsonb),
  ($profile${
    "slug":"koto-sumida-taito-real-estate-investment",
    "title":"Koto, Sumida and Taito Real Estate Investment: East-Core and Waterfront Diligence",
    "summary":"An east-core Tokyo screen for rental, hospitality and mixed-use assets across Koto, Sumida and Taito, with tourism, waterfront, supply and hazard evidence.",
    "category":"Tokyo east-core real estate","region":"Tokyo — Koto / Sumida / Taito","assetClass":"Residential / hospitality / mixed-use","decisionStage":"Submarket underwriting","readTime":"17 min","kicker":"TOKYO EAST CORE / WATERFRONT AND VISITOR DEMAND",
    "decisionQuestion":"Does east-core demand compensate for waterfront, visitor, supply and building-specific risk at the proposed basis?",
    "answer":"Separate Koto's waterfront and large-project exposure, Sumida's residential and tourism-linked districts, and Taito's dense visitor, commercial and traditional neighbourhoods. The 2026 residential averages were JPY 661,500 per m² in Koto, JPY 613,300 in Sumida and JPY 1,320,800 in Taito; annual changes were 11.9%, 13.2% and 14.2%. These figures require parcel hazard and use-specific operating evidence before they inform a deal.",
    "priceFact":"Taito JPY 1,320,800/m²; Koto JPY 661,500; Sumida JPY 613,300","priceMeaning":"Taito's average was roughly double the other two, reflecting different urban form and location mix. Do not combine waterfront residential and dense visitor districts into one comparable set.",
    "growthFact":"Taito +14.2%; Sumida +13.2%; Koto +11.9%","growthMeaning":"Strong 2026 residential benchmark changes increase both opportunity and overpayment risk in districts with material new supply or hazard exposure.",
    "coveredMarkets":["Koto","Sumida","Taito"],
    "evidenceScope":"2026 MLIT residential standard-site averages for Koto, Sumida and Taito.",
    "evidencePoints":[{"market":"Taito","averagePriceYenPerSqm":1320800,"annualChangePct":14.2,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Koto","averagePriceYenPerSqm":661500,"annualChangePct":11.9,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Sumida","averagePriceYenPerSqm":613300,"annualChangePct":13.2,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]}],
    "thesisLede":"East-core value comes from distinct residential, visitor and waterfront demand—not from an undifferentiated east-Tokyo discount.",
    "thesis":"Taito can depend on visitor, commercial and dense urban demand; Sumida spans established neighbourhoods and tourism-linked locations; Koto includes waterfront towers, family districts, logistics interfaces and large redevelopment. Define the intended use and tenant before comparing basis or growth.",
    "demand":"Separate long-term household rent, short-stay or hotel operations, retail footfall and owner-occupier demand. Obtain monthly and channel-level evidence where visitor demand matters, and building-level leasing data where residential demand is the thesis.",
    "supply":"Map tower completions, hotel rooms, converted stock and public-realm or transport projects. Review management rules and legal use carefully: a residential building's location does not create permission or operational capacity for lodging.",
    "riskLede":"Water, reclaimed-land, crowding and operating-use risks can be more important than the ward's average price change.",
    "riskTitle":"Waterfront and use-right blind spot","downside":"Flood, storm-surge or liquefaction exposure can affect downtime, insurance and buyer appetite, while lodging or retail income can fail if the approved use, building rules, staffing or neighbourhood operations do not support it.",
    "riskAction":"Complete parcel hazard and elevation review, building-rule and permit verification, monthly operating evidence and an insurance quote before capitalizing any visitor or waterfront premium.",
    "relatedSlugs":["osaka-hotel-investment-due-diligence","tokyo-multifamily-investment-due-diligence","greater-tokyo-real-estate-market"]
  }$profile$::jsonb),
  ($profile${
    "slug":"kita-arakawa-itabashi-nerima-real-estate-investment",
    "title":"Kita, Arakawa, Itabashi and Nerima Rental Real Estate Investment",
    "summary":"A north and northwest Tokyo multifamily screen covering affordability, commuter demand, older stock, railway catchments, river risk and exit liquidity.",
    "category":"Tokyo commuter rental","region":"Tokyo — Kita / Arakawa / Itabashi / Nerima","assetClass":"Multifamily / rental residential","decisionStage":"Yield and risk screen","readTime":"17 min","kicker":"TOKYO NORTH / AFFORDABILITY AND INCOME",
    "decisionQuestion":"Does a higher-income-yield thesis survive building condition, railway, tenant and flood evidence in north Tokyo?",
    "answer":"A north-Tokyo yield thesis must be station- and building-specific. The 2026 residential averages were JPY 742,000 per m² in Kita, JPY 718,700 in Arakawa, JPY 553,600 in Itabashi and JPY 480,500 in Nerima. Annual changes ranged from 6.2% to 11.8%. Lower land basis than the core can improve income yield, but older stock, river exposure and micro-location exit demand can consume the spread.",
    "priceFact":"Kita JPY 742,000/m²; Arakawa JPY 718,700; Itabashi JPY 553,600; Nerima JPY 480,500","priceMeaning":"The cluster spans a wide basis and should be divided by railway, river and product rather than treated as one affordable market.",
    "growthFact":"Arakawa +11.8%; Kita +11.6%; Itabashi +8.5%; Nerima +6.2%","growthMeaning":"2026 momentum was uneven. Higher growth does not remove building, hazard or tenant-income constraints.",
    "coveredMarkets":["Kita","Arakawa","Itabashi","Nerima"],
    "evidenceScope":"2026 MLIT residential standard-site averages for Kita, Arakawa, Itabashi and Nerima.",
    "evidencePoints":[{"market":"Kita","averagePriceYenPerSqm":742000,"annualChangePct":11.6,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Arakawa","averagePriceYenPerSqm":718700,"annualChangePct":11.8,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Itabashi","averagePriceYenPerSqm":553600,"annualChangePct":8.5,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Nerima","averagePriceYenPerSqm":480500,"annualChangePct":6.2,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]}],
    "thesisLede":"The opportunity is income supported by commute and affordability, not a generic expectation that outer wards converge with central pricing.",
    "thesis":"Kita and Arakawa include major rail and dense urban nodes, while Itabashi and Nerima contain broad commuter and family submarkets with different rail access and housing form. State the rent-to-income, commute and product logic for the exact catchment and identify the buyer likely to purchase the stabilized asset.",
    "demand":"Test achieved rent, renewal, arrears, guarantor use and tenant origin by unit and railway. Affordability demand may be durable but rent growth can be constrained by household income and competing stock one or two stations farther out.",
    "supply":"Older apartments, small-lot buildings and varied seismic standards require a condition and legal-access screen. Quantify vacancy during renovation, exterior and equipment cycles, reserve adequacy and management intensity before treating current occupancy as stabilized.",
    "riskLede":"Apparent yield can be compensation for older stock, river exposure, weaker rent growth or a narrower exit pool.",
    "riskTitle":"Yield spread consumed by condition and hazard","downside":"A higher headline cap rate can disappear after realistic repairs, tenant turnover, insurance, flood mitigation and slower disposition. Ward-level growth does not guarantee a lender or future buyer accepts the same risk.",
    "riskAction":"Bridge advertised yield to normalized NOI with unit-level evidence, price a ten-year capital plan, export parcel hazards and obtain lender and buyer feedback before setting the bid.",
    "relatedSlugs":["setagaya-nakano-suginami-real-estate-investment","tokyo-multifamily-investment-due-diligence","greater-tokyo-real-estate-market"]
  }$profile$::jsonb),
  ($profile${
    "slug":"adachi-katsushika-edogawa-real-estate-investment",
    "title":"Adachi, Katsushika and Edogawa Real Estate Investment Due Diligence",
    "summary":"An east-outer Tokyo residential investment screen focused on affordability, family and commuter demand, river systems, building resilience and exit evidence.",
    "category":"Tokyo affordable rental","region":"Tokyo — Adachi / Katsushika / Edogawa","assetClass":"Rental residential / small multifamily","decisionStage":"Yield and hazard screen","readTime":"17 min","kicker":"TOKYO EAST OUTER / AFFORDABILITY AND RESILIENCE",
    "decisionQuestion":"Is the affordability-led income spread sufficient after river, building, rent-growth and exit risks are fully priced?",
    "answer":"Underwrite affordability and resilience together. The 2026 residential averages were JPY 441,100 per m² in Edogawa, JPY 410,800 in Adachi and JPY 387,500 in Katsushika, with annual changes of 5.7%, 6.3% and 5.6%. These lower bases can support income strategies, but exact river and inland-flood exposure, building condition, tenant affordability and exit financing must be evidenced parcel by parcel.",
    "priceFact":"Edogawa JPY 441,100/m²; Adachi JPY 410,800; Katsushika JPY 387,500","priceMeaning":"The official averages show a relatively tight outer-east price band, making railway, hazard, building condition and operating performance decisive.",
    "growthFact":"Adachi +6.3%; Edogawa +5.7%; Katsushika +5.6%","growthMeaning":"Positive 2026 changes do not reduce the need to price physical resilience and tenant-income limits.",
    "coveredMarkets":["Adachi","Katsushika","Edogawa"],
    "evidenceScope":"2026 MLIT residential standard-site averages for Adachi, Katsushika and Edogawa.",
    "evidencePoints":[{"market":"Edogawa","averagePriceYenPerSqm":441100,"annualChangePct":5.7,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Adachi","averagePriceYenPerSqm":410800,"annualChangePct":6.3,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Katsushika","averagePriceYenPerSqm":387500,"annualChangePct":5.6,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]}],
    "thesisLede":"Affordability can create durable occupancy, but the investment case must retain enough return to fund resilience and building work.",
    "thesis":"These wards offer broad commuter and family markets at lower land bases than inner Tokyo. Define the railway, walk, unit size and household budget that support occupancy. Do not assume affordability creates unlimited rent growth or that every location has the same emergency, evacuation and buyer profile.",
    "demand":"Use achieved rents, applicant income, guarantor outcomes, arrears, household size and renewal data. Test the tenant's alternatives along the railway and across the prefectural boundary; affordability is relative to commute, unit quality and total housing cost.",
    "supply":"Review older stock, small buildings, ground-floor exposure, equipment location and emergency access. A low basis can justify upgrades, but only when legal use, structure and achievable post-work rent are documented.",
    "riskLede":"Flood and disruption risk can affect the same tenants, operating cash flow, insurance and exit buyers simultaneously.",
    "riskTitle":"Correlated river and tenant resilience risk","downside":"A severe event can create repair cost, vacancy, access disruption and household stress at the same time. A portfolio concentrated in similar low-elevation catchments may not be diversified even across three wards.",
    "riskAction":"Map each parcel and critical equipment elevation, retain municipal evacuation evidence, obtain insurance terms, stress downtime and arrears, and cap exposure by river system and transport dependency.",
    "relatedSlugs":["kita-arakawa-itabashi-nerima-real-estate-investment","tokyo-multifamily-investment-due-diligence","greater-tokyo-real-estate-market"]
  }$profile$::jsonb),
  ($profile${
    "slug":"tokyo-tama-western-suburbs-real-estate-investment",
    "title":"Tokyo Tama and Western Suburbs Real Estate Investment",
    "summary":"A suburban Tokyo investment screen for Musashino, Mitaka, Tachikawa and Hachioji covering railway nodes, family and student demand, demographics, supply and exit liquidity.",
    "category":"Tokyo suburban real estate","region":"Tokyo — Tama / Musashino / Mitaka","assetClass":"Residential / neighbourhood mixed-use","decisionStage":"Corridor selection","readTime":"17 min","kicker":"TOKYO TAMA / RAILWAY CORRIDORS",
    "decisionQuestion":"Which western Tokyo node offers enough tenant and buyer depth to justify the basis and operating plan?",
    "answer":"Choose a railway and demand node before choosing a city label. The 2026 residential averages were JPY 692,200 per m² in Musashino, JPY 492,400 in Mitaka, JPY 308,400 in Tachikawa and JPY 131,300 in Hachioji; annual changes ranged from 3.9% to 7.0%. The large dispersion reflects different proximity, employment, education and urban roles. Match the building to the node's tenant and exit pool.",
    "priceFact":"Musashino JPY 692,200/m² to Hachioji JPY 131,300/m²","priceMeaning":"Western Tokyo spans premium inner-suburban and broad outer-suburban markets. A single Tama comparable set is not decision-grade.",
    "growthFact":"Tachikawa +7.0%; Musashino +5.6%; Mitaka +5.0%; Hachioji +3.9%","growthMeaning":"Different 2026 momentum should be tested against station access, local employment, household and student demand, and new supply.",
    "coveredMarkets":["Musashino","Mitaka","Tachikawa","Hachioji","Tama railway corridors"],
    "evidenceScope":"2026 MLIT residential standard-site averages for four western Tokyo anchors.",
    "evidencePoints":[{"market":"Musashino","averagePriceYenPerSqm":692200,"annualChangePct":5.6,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Mitaka","averagePriceYenPerSqm":492400,"annualChangePct":5.0,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Tachikawa","averagePriceYenPerSqm":308400,"annualChangePct":7.0,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]},{"market":"Hachioji","averagePriceYenPerSqm":131300,"annualChangePct":3.9,"sourceIds":["mlit-land-price-2026","mlit-land-growth-2026"]}],
    "thesisLede":"Western Tokyo is a hierarchy of nodes; proximity to a station is not equivalent to node-level employment, education and buyer depth.",
    "thesis":"Musashino and Mitaka can compete as premium inner-suburban residential markets, Tachikawa acts as a major western commercial and transport node, and Hachioji spans education, employment and broad outer-suburban housing. State whether the thesis depends on central commuting, local demand or both.",
    "demand":"Measure tenants and buyers by workplace, institution, household, unit type and railway. Test express frequency, last-train, bus and bicycle access and the effect of service disruption. Student demand needs enrolment, unit, guarantor and turnover evidence rather than an institution count.",
    "supply":"Map station-area redevelopment, condominium delivery, older rental stock and developable land. Lower basis may come with more supply elasticity and a narrower exit pool; quantify marketing periods and financing availability for the exact building size.",
    "riskLede":"Outer-node income can be stable while price and exit liquidity remain more sensitive to demographics, commute patterns and financing.",
    "riskTitle":"Node depth and exit-liquidity overestimate","downside":"A property can lease to a local segment yet remain difficult to sell at the assumed price because the buyer pool is small, the building is operationally intensive or alternative land and stock limit scarcity.",
    "riskAction":"Document local and central-commuter demand separately, collect failed and completed listings, interview lenders and managers, and underwrite a longer sale period without benchmark appreciation.",
    "relatedSlugs":["setagaya-nakano-suginami-real-estate-investment","tokyo-multifamily-investment-due-diligence","greater-tokyo-real-estate-market"]
  }$profile$::jsonb)
), records AS (
  SELECT
    profile ->> 'slug' AS slug,
    profile ->> 'title' AS title,
    profile ->> 'summary' AS summary,
    jsonb_build_object(
      'category', profile ->> 'category', 'region', profile ->> 'region',
      'assetClass', profile ->> 'assetClass', 'decisionStage', profile ->> 'decisionStage',
      'readTime', profile ->> 'readTime', 'sourceCount', 5
    ) AS preview,
    public.build_investor_metro_payload(profile) AS payload
  FROM profiles
)
INSERT INTO public.content_products (
  slug, locale, title, summary, content_type, access_model, price_usdc, network,
  preview, payload, source_url, license, version, is_active, published_at, updated_at
)
SELECT
  slug, 'en', title, summary, 'investor_brief', 'free', NULL, NULL, preview, payload,
  'https://paradigmjp.com/en/japan-opportunities/invest/' || slug,
  'Paradigm API Terms; attribution required. Not investment, legal, tax, brokerage or financial advice.',
  1, true, '2026-08-02T00:00:00Z'::timestamptz, now()
FROM records
ON CONFLICT (slug, locale) DO UPDATE SET
  title = EXCLUDED.title, summary = EXCLUDED.summary, content_type = EXCLUDED.content_type,
  access_model = EXCLUDED.access_model, preview = EXCLUDED.preview, payload = EXCLUDED.payload,
  source_url = EXCLUDED.source_url, license = EXCLUDED.license, version = EXCLUDED.version,
  is_active = EXCLUDED.is_active, published_at = EXCLUDED.published_at, updated_at = now();

COMMIT;
